SpawnRoleTextTranslation
ss220club/Bandastation pull request #112
Opened 2024-04-18 00:33 UTC by AloeNeverDie

## Что этот PR делает

Перевод текста при спавне за роль, а так же при выборе в лобби на русский язык.

## Почему это хорошо для игры

Нужен перевод.

fixes https://github.com/ss220club/Bandastation/issues/64

## Changelog

🆑
qol: Переведены раундстарт роли и горилла
🆑

2024-04-18 01:27 UTC, BR54FF requested changes

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/ai.dm
> +	supervisors = "вашими законы"
```suggestion
	supervisors = "вашими законами"
```

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/botanist.dm
> +	description = "Выращивайте растения для повара, медицины, и отдыха."
```suggestion
	description = "Выращивайте растения для повара, медицины и отдыха."
```
Перечисление кончается, вместо запятой уже есть И

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/captain.dm
> +		в муках пытаясь это сделать."
```suggestion
		в муках, пытаясь это сделать."
```
Деепричастие

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/lawyer.dm
> +		обеспечивайте безопасности в соответствии с действующими протоколами и космическим законодательством."
```suggestion
		обеспечивайте безопасность в соответствии с действующими протоколами и космическим законодательством."
```

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/medical_doctor.dm
> +	description = "Спасайте жизни, помогайте пострадавшим, где бы они не были, \
```suggestion
	description = "Спасайте жизни, помогайте пострадавшим, где бы они ни были, \
```

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/scientist.dm
> +	description = "Проводите эксперименты, открвайте новые технологии, кормите слаймов, создавайте бомбы."
```suggestion
	description = "Проводите эксперименты, открывайте новые технологии, кормите слаймов, создавайте бомбы."
```

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/station_trait/cargo_gorilla.dm
> +	to_chat(spawned, span_notice("Вы можете поднимать ящики кликая на них, и класть их на пол кликая по нему."))
```suggestion
	to_chat(spawned, span_notice("Вы можете поднимать ящики, кликая на них, и класть их на пол, кликая по нему."))
```

2024-04-18 01:27 UTC, BR54FF commented on code/modules/jobs/job_types/station_trait/human_ai.dm
> +	description = "Помогайте экипажу, открывайте шлюзы, следуйте своему своду законов, и координируйтесь с другими киборгами."
```suggestion
	description = "Помогайте экипажу, открывайте шлюзы, следуйте своему своду законов и координируйтесь с другими киборгами."
```

2024-04-18 01:27 UTC, BR54FF commented on code/modules/mob/dead/new_player/new_player.dm
> +			return "[jobtitle] не совместима с некоторыми ролями антагонистов выбранные вами."
```suggestion
			return "[jobtitle] несовместим с некоторыми выбранными вами ролями антагонистов.
```

2024-04-18 01:27 UTC, BR54FF commented on code/modules/mob/dead/new_player/new_player.dm
> +		tgui_alert(usr, "Возникла непредвиденная ошибка при выдаче роли выбранную вами. Если вы не можете зайти обратитесь к администрации.")
```suggestion
		tgui_alert(usr, "Возникла непредвиденная ошибка при выдаче роли, выбранной вами. Если вы не можете зайти, обратитесь к администрации.")
```

2024-04-18 16:37 UTC, larentoun requested changes

2024-04-18 16:37 UTC, larentoun commented on code/modules/bitrunning/job.dm
> +	description = "Путешествуйте по виртуальному миру в поисках снаряжения и лута. Расшифровывайте свои награды на станции."
```suggestion
	description = "Путешествуйте по виртуальному миру в поисках снаряжения и добычи. Расшифровывайте свои награды на станции."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/_job.dm
> +			может быть добавлен дополнительный доступ.")
"Поскольку эта станция изначально была укомплектована полным составом, вы будете снабжены только самым необходимым для работы может быть добавлен дополнительный доступ"

Надо исправлять

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/_job.dm
> +		return "<b>Для общения в радиоканале вашего департамента используйте префикс :h. Чтобы узнать все доступные каналы осмотрите наушник.</b>"
```suggestion
		return "<b>Для общения в радиоканале вашего отдела используйте префикс :h. Чтобы узнать все доступные каналы осмотрите наушник.</b>"
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/ai.dm
> +		minor_announce("[joining_mob] был загружен в пустое ядро ИИ с блюспейс сетью по адресу [AREACOORD(joining_mob)].")
```suggestion
		minor_announce("[joining_mob] был загружен в пустое ядро ИИ с блюспейс сетью в [AREACOORD(joining_mob)].")
```
Какой адрес? xdd

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/ai.dm
> +	return "<b>Для коммуникации используйте префикс :b, чтобы общаться с киборагми и другими ИИ.</b>"
```suggestion
	return "<b>Для коммуникации с киборгами и другими ИИ используйте префикс :b.</b>"
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/captain.dm
> +	description = "Вы ответственны за станцию, руководите главами, \
```suggestion
	description = "Будьте ответственны за станцию, руководите главами, \
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/captain.dm
> +	supervisors = "Официальными лицами Нанотрейзен"
```suggestion
	supervisors = "официальными лицами Нанотрейзен"
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/cargo_technician.dm
> +		а также кубы с наградами за поручения."
```suggestion
		а также кубы с наградами за заказы."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/chief_engineer.dm
> +		следите, чтобы кристалл Суперматерии не взорвался, обслуживайте телекоммуникации."
```suggestion
		чтобы кристалл Суперматерии не взорвался, а также обслуживайте телекоммуникации."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/head_of_security.dm
> +	description = "Руководите отделом службы безопасности, убедитесь, что они неподкупны, \
```suggestion
	description = "Руководите отделом службы безопасности, убедитесь в их неподкупности, \
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/head_of_security.dm
> +		следите за тем, чтобы все отделы охраняются."
```suggestion
		следите за тем, чтобы все отделы охранялись."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/lawyer.dm
> +		обеспечивайте безопасность в соответствии с действующими протоколами и космическим законодательством."
```suggestion
		убедитесь, что СБ следует СРП и КЗ."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/medical_doctor.dm
> +		проводите сканирование пациентов."
```suggestion
		проводите сканирование каждого встречного."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/roboticist.dm
> +	description = "Создавайте и обслуживайте роботов и ИИ, создавайте роботов."
```suggestion
	description = "Создавайте и обслуживайте роботов и ИИ, создавайте мехов."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/station_trait/bridge_assistant.dm
> +	description = "Наблюдайте за мостиком, управляйте консолями на нем и проводите дни, варя кофе для вышестоящих лиц."
```suggestion
	description = "Следите за мостиком, управляйте консолями на нем и проводите дни, варя кофе для вышестоящих лиц."
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/station_trait/human_ai.dm
> +	supervisors = "Капитаном, Директором Исследований и вашим сводом законов "
```suggestion
	supervisors = "Капитаном, Директором Исследований и вашим сводом законов"
```

2024-04-18 16:37 UTC, larentoun commented on code/modules/jobs/job_types/unassigned.dm
> +	title = "Безработный член экипажа"
Мы же нигде профки не переводили?

2024-04-18 16:59 UTC, AloeNeverDie commented on code/modules/bitrunning/job.dm
> +	description = "Путешествуйте по виртуальному миру в поисках снаряжения и лута. Расшифровывайте свои награды на станции."
Лут решили не трогать

2024-04-18 17:18 UTC, AloeNeverDie commented on code/modules/jobs/job_types/unassigned.dm
> +	title = "Безработный член экипажа"
Нет вроде, но это ошибок не вызывало

2024-04-18 17:36 UTC, larentoun commented on code/modules/jobs/job_types/unassigned.dm
> +	title = "Безработный член экипажа"
Ну, в ассок листах использовать кириллицу можно, если что, будет нашей первой овечкой

2024-04-18 18:25 UTC, AloeNeverDie commented on code/modules/jobs/job_types/unassigned.dm
> +	title = "Безработный член экипажа"
оставляем?

2024-04-18 19:37 UTC, larentoun approved these changes

2024-04-18 19:37 UTC, larentoun commented on code/modules/jobs/job_types/_job.dm
> +
```suggestion

```

2024-04-19 14:25 UTC, larentoun commented on code/modules/jobs/job_types/_job.dm
> +			.")
Вы строчку потеряли, можете вернуть обратно? 303 строка была пустая

2024-04-19 15:35 UTC, merged