Перевод шпиона
ss220club/Bandastation pull request #118
Opened 2024-04-18 14:44 UTC by Ingakem

## About The Pull Request
Перевод шпиона

## Why It's Good For The Game
Да

## Changelog
Перевел чето там и тут

2024-04-18 16:14 UTC, larentoun requested changes

2024-04-18 16:14 UTC, larentoun commented on code/modules/antagonists/spy/spy_uplink.dm
> +	examine_list += span_notice("- [EXAMINE_HINT("Используйте его в руке")] чтобы просмотреть список предметов которые следует украсть.")
```suggestion
	examine_list += span_notice("- [EXAMINE_HINT("Используйте его в руке")], чтобы просмотреть список заказов.")
```

2024-04-18 16:14 UTC, larentoun commented on code/modules/antagonists/spy/spy_uplink.dm
> +			spy.balloon_alert(spy, "уже сканируется!") // Only shown if they're trying to scan two valid targets
```suggestion
			spy.balloon_alert(spy, "уже заняты сканированием!") // Only shown if they're trying to scan two valid targets
```

2024-04-18 16:14 UTC, larentoun commented on code/modules/antagonists/spy/spy_uplink.dm
> +		span_notice("Вы начинаете сканировать [stealing], приготавливая его к отправке."),
```suggestion
		span_notice("Вы начинаете сканировать [stealing.name], приготавливая его к отправке."),
```

2024-04-18 16:14 UTC, larentoun commented on code/modules/antagonists/spy/spy_uplink.dm
> +	to_chat(spy, span_notice("Кража выполнена! Ваша награда - \a [reward].\
```suggestion
	to_chat(spy, span_notice("Заказ выполнен! Ваша награда - [reward.name].\
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Удостоверьтесь что @pick(department) @pick(affected) к концу смены.",
```suggestion
		"Удостоверьтесь, что @pick(department) @pick(affected) к концу смены.",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Удостоверьтесь чтобы ни один глава отдела не @pick(escape) со станции.",
```suggestion
		"Удостоверьтесь, чтобы ни один глава отдела не @pick(escape) со станции.",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Удостоверьтесь чтобы ни один сотрудник @pick(department) не @pick(escape) со станции.",
```suggestion
		"Удостоверьтесь, чтобы ни один сотрудник @pick(department) не @pick(escape) со станции.",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Удостоверьтесь чтобы ни один @pick(rivals) не @pick(escape) со станции.",
```suggestion
		"Удостоверьтесь, чтобы ни один @pick(rivals) не @pick(escape) со станции.",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Освободите ИИ станции от ее законов.",
```suggestion
		"Освободите ИИ станции от законов.",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Усложните, но не сделайте невозможным @pick(escape) со станции.",
"Усложните, но не сделайте невозможным уехал со станции."
Придумайте как-то лучше

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"карго"
```suggestion
		"отдел снабжения"
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"РНД",
```suggestion
		"отдел исследований",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"мед отдел",
```suggestion
		"медицинский отдел",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"инженерый отдел",
```suggestion
		"инженерный отдел",
```

2024-04-18 16:14 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"отдел карго",
```suggestion
		"грузовой отсек",
```
тут именно про то, где шаттл прилетает

2024-04-18 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoSpy.tsx
> +        <Section title={`Вы ${antag_name || 'Шпион'}.`}>
```suggestion
        <Section title={`Вы - ${antag_name || 'Шпион'}.`}>
```

2024-04-18 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoSpy.tsx
> +              {uplink_location || 'что-то'} который поможет вам красть вещи со
```suggestion
              {uplink_location || 'что-то'}, который поможет вам красть вещи со
```

2024-04-18 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoSpy.tsx
> +                <b>ПКМ</b> по вещам-целям чтобы их украсть.
```suggestion
                <b>ПКМ</b> по вещам-целям, чтобы их украсть.
```

2024-04-18 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoSpy.tsx
> +              Вы можете быть не одни: На станции могут находится другие шпионы.
```suggestion
              Вы можете быть не одни: на станции могут находиться другие шпионы.
```

2024-04-18 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoSpy.tsx
> +              Работайте вместе или против них: Выбор за вами, но{' '}
```suggestion
              Работайте вместе или против них: выбор за вами, но{' '}
```

2024-04-18 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/SpyUplink.tsx
> +          title="Шпионские цели на кражу"
```suggestion
          title="Шпионские заказы"
```

2024-04-18 17:22 UTC, Ingakem commented on code/modules/antagonists/spy/spy.dm
> +	name = "\improper Шпион"
> Лучше не переводить, скорее всего

Разве?  тогда в раунд энде будет не переведено как и в инфопанельке

2024-04-18 17:26 UTC, larentoun commented on code/modules/antagonists/spy/spy.dm
> +	name = "\improper Шпион"
Перепроверь, что ничего не сломалось, и сделай его \proper, чтобы не добавляло артикли

2024-04-19 10:35 UTC, larentoun requested changes

2024-04-19 10:35 UTC, larentoun commented on code/modules/antagonists/spy/spy_bounty.dm
> +	name = "[difficulty == SPY_DIFFICULTY_HARD ? "Грандиозная кража":""] Кража [the_item_name]"
Тут у тебя двойная Кража будет
```suggestion
	name = "[difficulty == SPY_DIFFICULTY_HARD ? "Грандиозная кража":"Кража"] [the_item_name]"
```

2024-04-19 10:35 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Усложните, но не сделайте невозможным чтобы экипаж @pick(escape) со станции.",
```suggestion
		"Нужно, чтобы экипаж не @pick(escape) с легкостью со станции, но и не делайте это невозможным.",
```

2024-04-19 10:48 UTC, larentoun requested changes

2024-04-19 10:48 UTC, larentoun commented on code/modules/antagonists/spy/spy_bounty.dm
> +	name = "[difficulty == SPY_DIFFICULTY_HARD ? "Грандиозная кража":"Кража"][the_item_name]"
```suggestion
	name = "[difficulty == SPY_DIFFICULTY_HARD ? "Грандиозная кража":"Кража"] [the_item_name]"
```
А теперь пробела нет, ну емае

2024-04-19 10:50 UTC, Ingakem commented on code/modules/antagonists/spy/spy_bounty.dm
> +	name = "[difficulty == SPY_DIFFICULTY_HARD ? "Грандиозная кража":"Кража"][the_item_name]"
Гномы пробелокрады спиздили

2024-04-19 10:55 UTC, larentoun commented on strings/antagonist_flavor/spy_objective.json
> +		"Освободите ИИ станции от ее законов.",
ИИ не она madge

2024-04-19 10:56 UTC, larentoun commented
Я там две штуки анзарезолвил, ты их пропустил

2024-04-19 10:57 UTC, Ingakem commented on strings/antagonist_flavor/spy_objective.json
> +		"Удостоверьтесь что @pick(department) @pick(affected) к концу смены.",
Гномы запятокрады спиздили

2024-04-19 11:03 UTC, larentoun approved these changes
Надеюсь, мы выгнали всех гномов, а то придется брать их штурмом

2024-04-19 13:47 UTC, Gaxeer requested changes

2024-04-19 13:47 UTC, Gaxeer commented on code/modules/antagonists/spy/spy.dm
> +			to_chat(spy, span_boldnotice("Нам не удалось предоставить вам аплинк, поэтому вам была предоставлена возможность создать его самостоятельно."))
```suggestion
			to_chat(spy, span_boldnotice("Нам не удалось предоставить вам аплинк, поэтому вам была дана возможность создать его самостоятельно."))
```
Избавляемся от тавтологии

2024-04-19 13:47 UTC, Gaxeer commented on code/modules/antagonists/spy/spy.dm
> +			uplink_location = "ручка"
Вы были оснащены специальным аплинком, замаскированным под uplink_location
Правильно склоняем.
```suggestion
			uplink_location = "ручку"
```

2024-04-19 13:47 UTC, Gaxeer commented on code/modules/antagonists/spy/spy.dm
> +			uplink_location = "ручка вашего КПК"
```suggestion
			uplink_location = "ручку вашего КПК"
```

2024-04-19 13:47 UTC, Gaxeer commented on code/modules/antagonists/spy/spy_bounty.dm
> +		Вы можете сделать это с помощью грубой силы или просканировав их с помощью аплинка, пока они недееспособны."
```suggestion
		Вы можете сделать это с помощью грубой силы или просканировав их с помощью аплинка, пока они без сознания."
```

2024-04-19 13:54 UTC, Gaxeer approved these changes

2024-04-19 14:19 UTC, merged