pet commands translate
ss220club/Bandastation pull request #124
Opened 2024-04-18 18:44 UTC by larentoun

## About The Pull Request

Перевод команды для петов

2024-04-18 20:25 UTC, dj-34 requested changes

2024-04-18 20:25 UTC, dj-34 commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("free", "loose", "гулять", "вон", "свобод", "брысь")
```suggestion
	speech_commands = list("free", "loose", "гулять", "вон", "свободен", "брысь")
```

2024-04-18 20:25 UTC, dj-34 commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("heel", "follow", "за мной", "след", "охран", "к ноге", "ко мне")
```suggestion
	speech_commands = list("heel", "follow", "за мной", "следуй", "охраняй", "к ноге", "ко мне")
```

2024-04-18 20:25 UTC, dj-34 commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands += list("good [parent.name]", "хорош")
chenahui

2024-04-18 20:25 UTC, dj-34 commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("attack", "sic", "kill", "апорт", "фас", "бить", "атак")
ты пьяный или кто
```suggestion
	speech_commands = list("attack", "sic", "kill", "апорт", "фас", "бить", "атакуй")
```

2024-04-18 20:25 UTC, dj-34 commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("breed", "consummate", "размножайся")
![image](https://github.com/ss220club/Bandastation/assets/20109643/b0fffe39-c894-4639-ad98-be27d65f0c24)

2024-04-18 20:25 UTC, dj-34 commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("shoot", "blast", "cast", "стреля", "выстрел", "пиу", "паф", "каст")
я твою маму пиу паф
```suggestion
	speech_commands = list("shoot", "blast", "cast", "стреляй", "выстрел", "пиу", "паф", "каст")
```

2024-04-18 20:28 UTC, larentoun commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("heel", "follow", "за мной", "след", "охран", "к ноге", "ко мне")
findtext находит просто комбинацию, не нужно полное слово. А так падежи учитываются - следуй, следуйте, следовать, охранять и тд

2024-04-18 20:29 UTC, larentoun commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands += list("good [parent.name]", "хорош")
хороший, хорошая

2024-04-18 20:29 UTC, larentoun commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("attack", "sic", "kill", "апорт", "фас", "бить", "атак")
атаковать, атака, атакуй

2024-04-18 20:29 UTC, larentoun commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands = list("shoot", "blast", "cast", "стреля", "выстрел", "пиу", "паф", "каст")
стрелять, стреляй, стреляйте

2024-04-19 07:52 UTC, Gaxeer commented on code/datums/components/pet_commands/pet_commands_basic.dm
> +	speech_commands += list("good [parent.name]", "хорош")
Чел, хорош

2024-04-19 13:43 UTC, merged