Cargo & bounty translate
ss220club/Bandastation pull request #130
Opened 2024-04-19 09:52 UTC by Chorden523

## About The Pull Request
Перевод карго консоли и баунти консоли.
Скинул пока чтобы не забыть что оно существует.

2024-04-20 09:13 UTC, Chorden523 commented
Первый тестовый версия доступна, аваитинг ревью

2024-04-20 11:24 UTC, larentoun requested changes
Первая партия. Надеюсь, гитхаб перестанет лагать, если я отправлю ее

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "Коммандор Джонсон в критическом состоянии после ещё одного пережитого сердечного приступа. Доктора говорят, что им нужно новое сердце как можно быстрее. Отправьте одно, быстро! Мы воз
```suggestion
	description = "Коммандор Джонсон в критическом состоянии после ещё одного пережитого сердечного приступа. Врачи говорят, что им нужно новое сердце как можно быстрее. Отправьте одно, быстро! Мы возьмём и кибернетическое, но только улучшенное."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "Недавний взрыв на Центральном Командовании оставил многих сотрудников с пробитыми лёгкими. Запасные лёгкие должны быть выданы. Мы возьмём кибернитические, если они понадобятся, но тол
```suggestion
	description = "Недавний взрыв на Центральном Командовании оставил многих сотрудников с пробитыми лёгкими. Отправьте нам несколько лишних экземпляров. Мы возьмём и кибернетические, но только улучшенные."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "Множество сотрудников станции 12 остались глухими в следствие неавторизованной клоунады. Отправьте им новые уши. Мы возьмём и кибернетические, если они нам понадобятся, но только если
```suggestion
	description = "Множество сотрудников станции 12 остались глухими в следствие неавторизованной клоунады. Отправьте им новые уши. Мы возьмём и кибернетические, но только улучшенные."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "Множество высокопоставленных дипломатов ЦентКома были госпитализированы с отказом печени после встречи с тремя послами Советского Союза. Помогите нам, ладно? Мы возьмём и кибернетичес
```suggestion
	description = "Множество высокопоставленных дипломатов ЦК были госпитализированы с отказом печени после встречи с послами Третьего Советского Союза. Помогите нам, ладно? Мы возьмём и кибернетические, но только улучшенные."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "Недавняя атака мимов экстремистов оставила экипаж станции 23 немыми. Отправьте несколько запасных языков."
```suggestion
	description = "Недавняя атака мимов экстремистов оставила экипаж станции 23 немыми. Отправьте несколько лишних языков."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "Федерация магов похитила у Нанотрейзен хвосты ящериц. В то время как ЦентКом разбирается с магами, не может ли станция припасти один из их хвостов?"
```suggestion
	description = "Федерация волшебников похитила у Нанотрейзен хвосты ящеров. Пока ЦК разбирается с волшебниками, не может ли станция отправить хвост из своих запасов?"
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "На Центральном Командовании кончились мощные очистители для труб. Не могли бы вы отправить кошачий хвост помощи нам?"
```suggestion
	description = "На Центральном Командовании кончились щетки для чистки сильнозагрязненных труб. Не выручите ли вы нас отправкой кошачьего хвоста?"
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/packs/vending_restock.dm
> +	group = "Пополнения торгоматов"
```suggestion
	group = "Пополнители вендоматов"
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "У СМО на ЦентКоме имеются проблемы с операциями на големах. Она просит одну бензопилу, пожалуйста."
```suggestion
	description = "У СМО на ЦК имеются проблемы с операциями на големах. Она просит одну бензопилу, пожалуйста."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "Коммандор Джексон ищет отличное дополнение для её коллекции экзотического оружия. Она вас наградит также за девятихвостого кота или девятихвостую ящерицу."
```suggestion
	description = "Коммандор Джексон ищет отличное дополнение для её коллекции экзотического оружия. Она вас наградит и за кошачий, и за ящерский девятихвост."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "После очередного взрывного инцидента на нашем ежегодном сырфесте на ЦентКоме, у нас лежит оргромная куча раненного экипажа. Пожалуйста отправьте нам свежий хирургический компьютер, ес
```suggestion
	description = "После очередного взрывного инцидента на нашем ежегодном сырфесте на ЦК, у нас лежит огромная куча раненного экипажа. Пожалуйста, отправьте нам свежий хирургический компьютер, когда это возможно."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/medical.dm
> +	description = "После недавнего притока инфицированного экипажа, мы видим, что маски не справляются в одиночку. Серебрянные операционный столы, к слову, могут сработать, отправьте нам один для исполь
```suggestion
	description = "После недавнего притока инфицированного экипажа, мы замечаем, что маски не справляются в одиночку. Серебрянные операционные столы, к слову, могут нам помочь, отправьте нам один для использования."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Коммандор Менков хочет поучавствовать в ежегодной Лавалендской регате. Он просит ваши корабли для самой быстрой лодки известной человеку."
```suggestion
	description = "Коммандор Менков хочет поучавствовать в ежегодной Лавалендской регате. Он просит ваши корабли для самой быстрой лодки, известной человеку."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Коммандор Менков хочет поучавствовать в ежегодной Лавалендской регате. Отправьте одну пару."
```suggestion
	description = "Коммандор Менков хочет поучавствовать в ежегодной Лавалендской регате. Для этого ему нужна пара вёсел."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Клоуны-марадёры украли все пожарные топоры со станции 12. Отправьте им костяной топор в качестве замены."
```suggestion
	description = "Клоуны-мародёры украли все пожарные топоры со станции 12. Отправьте им костяной топор в качестве замены."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Станция 14 в добровольном порядке призвала свой экипаж ящериц для для тестирования баллистической брони. Отправьте один комплект костяной брони."
```suggestion
	description = "Станция 14 в добровольном порядке призвала своих ящеров из экипажа для тестирования баллистической брони. Отправьте один комплект костяной брони."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Глава службы безопасности на станции 42 отметила свой день рождения вчера! Мы хотим подарить ей модный костяной шлем."
```suggestion
	description = "Глава службы безопасности на станции 42 завтра отмечает свой день рождения! Мы хотим подарить ей модный костяной шлем."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Директор исследований на станции 14 утверждает, что языческий костяной защищает его владельца. Отправьте им несколько для начала тестов."
```suggestion
	description = "Директор исследований на станции 14 утверждает, что языческие костяные талисманы защищают своих владельцев. Отправьте им несколько для начала тестов."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	name = "Миска грибов"
```suggestion
	name = "Грибная миска"
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Лейтенант Джеб уронил свою любимую миску грибов. Подбодрите его, отправив новую, хорошо?"
```suggestion
	description = "Лейтенант Джеб уронил свою любимую грибную миску. Подбодрите его, отправив новую, хорошо?"
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Наш ботаник утверждает, что он может перегнать вкусный ликёр из абсолютно любого растения. Давайте посмотрим, что будет делать с шляпами грибов из семьи Иноцибе."
```suggestion
	description = "Наш ботаник утверждает, что он может перегнать вкусный ликёр из абсолютно любого растения. Давайте посмотрим, что он будет делать с шляпками грибов из семьи Иноцибе."
```

2024-04-20 11:24 UTC, larentoun commented on code/modules/cargo/bounties/mining.dm
> +	description = "Листья гриба Порчини по слухам имеют целебные свойства. Наши исследователи хотят заполучить их для эксперимента."
```suggestion
	description = "Листья гриба Порчини имеют целебные свойства, если верить слухам. Наши исследователи хотят заполучить их для эксперимента."
```

2024-04-20 11:56 UTC, larentoun requested changes
Короче, я допроверю после того, как ты проведешь code/modules/cargo/bounties/assistant.dm через инструменты для проверки орфографии и пунктуации.

ЦентКом преврати в ЦК. Я устал.

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/reagent.dm
> +	description = "ЦентКом хочет пить! Отправьте посылку с [name] на ЦентКом для утоления жажды компании."
```suggestion
	description = "ЦК хочет пить! Отправьте посылку с [name] на ЦК для утоления жажды компании."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/reagent.dm
> +	description = "ЦентКом предлагает награду талантливым миксологам. Отправьте контейнер с [name] для получения награды."
```suggestion
	description = "ЦК предлагает награду талантливым миксологам. Отправьте контейнер с [name] для получения награды."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/reagent.dm
> +	description = "ЦентКом отчаянно нуждается в химикате под названием: [name]. Отправьте контейнер с ним для получения вознаграждения."
```suggestion
	description = "ЦК отчаянно нуждается в химикате под названием: [name]. Отправьте контейнер с ним для получения вознаграждения."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/reagent.dm
> +	description = "ЦентКом выплачивает премии за химикат под названием: [name]. Отправьте контейнер с ним для получения вознаграждения.."
```suggestion
	description = "ЦК выплачивает премии за химикат под названием: [name]. Отправьте контейнер с ним для получения вознаграждения.."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/reagent.dm
> +	description = "ЦентКому требуется [required_ammount] таблеток химиката под названием: [name], содержащих как минимум [wanted_vol] каждая. Отправьте контейнер с ними для получения вознаграждения."
```suggestion
	description = "ЦК требуется [required_ammount] таблеток химиката под названием: [name], содержащих как минимум [wanted_vol] каждая. Отправьте контейнер с ними для получения вознаграждения."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	description = "Научный руководитель Нанотрейзен охотится за редким и экзотическим предметом под названием: [name]. За его нахождение полагается награда."
```suggestion
	description = "Научный руководитель Нанотрейзен охотится за редким и экзотическим [name]. За его нахождение полагается награда."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "зелёный экстракт слайма"
```suggestion
	name = "зелёным экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "розовый экстракт слайма"
```suggestion
	name = "розовым экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "золотой экстракт слайма"
```suggestion
	name = "золотым экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "маслянный экстракт слайма"
```suggestion
	name = "масляным экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "чёрный экстракт слайма"
```suggestion
	name = "чёрным экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "светло-розовый экстракт слайма"
```suggestion
	name = "светло-розовым экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "адамантитовый экстракт слайма"
```suggestion
	name = "адамантитовым экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/slime.dm
> +	name = "Радужный экстракт слайма"
```suggestion
	name = "радужным экстрактом слайма"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/special.dm
> +	description = "Информация о синдикате высоко ценится на ЦентКоме. Если вы найдёте документы синдиката, отправьте их. Вы может спасёте жизни."
```suggestion
	description = "Информация о синдикате высоко ценится на ЦК. Если вы найдёте документы синдиката, отправьте их. Вы, может, спасёте жизни."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/special.dm
> +	description = "Отдел аномальных материалов Нанотрейзен отчаянно нуждается в адамантие. Отправьте большую партию и мы сделаем так, что вы не пожалеете."
```suggestion
	description = "Отдел аномальных материалов Нанотрейзен отчаянно нуждается в адамантите. Отправьте большую партию, и мы вас щедро вознаградим."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/special.dm
> +	description = "Недавно, у группы уборщиков кончился мусор для уборки и ЦентКом решил уволить их для уменьшения расходов. Отправьте поставку мусора, чтобы оставить их работать, и они вам дадут вам ма
```suggestion
	description = "Недавно, у группы уборщиков кончился мусор для уборки и ЦК решило уволить их для уменьшения расходов. Отправьте мусора, чтобы оставить их на должности, и они вам дадут вам маленькую компенсацию."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/orderconsole.dm
> +		человеческие останки, класифицированное ядерное оружие, почту, не доставленные ящики с заказами департаментов, бомбы синдиката, \
```suggestion
		человеческие останки, засекреченное ядерное оружие, почту, недоставленные ящики с заказами отделов, бомбы синдиката, \
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/orderconsole.dm
> +			user.visible_message(span_warning("[user] проводит [emag_card] по [src.name]!"))
```suggestion
			user.visible_message(span_warning("[user] проводит [emag_card.name] по [src.name]!"))
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/orderconsole.dm
> +			say("[src.name] отклоняет [id_card].")
```suggestion
			say("[src.name] отклоняет [id_card.name].")
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/orderconsole.dm
> +			say("На [id_card] недостаточно доступа для этой покупки.")
```suggestion
			say("На [id_card.name] недостаточно доступа для этой покупки.")
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/orderconsole.dm
> +			say("Только департамент, что заказал этот предмет может отменить заказ.")
```suggestion
			say("Только отдел, заказавший этот предмет, может отменить заказ.")
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/orderconsole.dm
> +					var/requisition_text = "<h2>[station_name()] Заявка на поставку</h2>"
```suggestion
					var/requisition_text = "<h2>[station_name()]: заявка на поставку</h2>"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Оказывается, что дискеты из BEPIS машины содержат экспериментальные узлы, занимающие мало места. Отправьте нам несколько, когда вы разберётесь с ними."
```suggestion
	description = "Оказывается, что дискеты, на которых BEPIS печатает эксперементальные узлы, занимают очень мало места. Отправьте нам несколько дискет, когда они будут готовы."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Наш отдел больших данных нуждается в более мощном оборудовании для игры в 'Разбомби Кубан Пи-', кхм, для тщательного мониторинга угроз в вашем секторе. Отправьте нам работающаю модуль
```suggestion
	description = "Наш отдел больших данных нуждается в более мощном оборудовании для игры в 'Разбомби Кубан Пи-', кхм, для тщательного мониторинга угроз в вашем секторе. Отправьте нам работающую модульную компьютерную консоль."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Нам нужно блюспейс ядро для помещения в Фазона. Отправьте одно нам, пожалуйста."
```suggestion
	description = "Нам нужно блюспейс ядро для помещения в Фазона. Пожалуйста, отправьте нам одно."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Мы пытаемся создать теслу пушку чтобы разобраться с молями. Отправьте нам флюкс ядро, пожалуйста."
```suggestion
	description = "Мы пытаемся создать теслу пушку, чтобы разобраться с молями. Отправьте нам флюкс ядро, пожалуйста."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Центральное РнД пытается обнаружить способ заставить мехов парить, отправьте гравитационное ядро."
```suggestion
	description = "Центральный НИО пытается обнаружить способ заставить мехов парить, отправьте гравитационное ядро."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Мы собираемся бросить ворктес ядро в червоточину и посмотреть что произойдёт. Отправьте одно."
```suggestion
	description = "Мы собираемся бросить ворктес ядро в червоточину и посмотреть, что произойдёт. Отправьте одно."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	name = "Переработанное галюцинагенное ядро"
```suggestion
	name = "Переработанное галлюциногенное ядро"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	name = "Переработанное биоскрамблер ядро"
```suggestion
	name = "Переработанное биоскрэмблер ядро"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Наш ящер уборщик потерял все свои конечности , отправьте нам биоскрамблер ядро для их замены."
```suggestion
	description = "Наш ящер уборщик потерял все свои конечности, отправьте нам биоскрэмблер ядро для их замены."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/science.dm
> +	description = "Мы пытаемся сохранить деньги на наших ежегодных реновациях ЦентКома. Отправьте нам пространственное ядро."
```suggestion
	description = "Мы пытаемся сохранить деньги на наших ежегодных реновациях ЦК. Отправьте нам пространственное ядро."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/security.dm
> +	description = "Транс-солнечная федерация не может TerraGov не смогла получить новую униформу для заключённых, так что если у вас есть запасная, то мы её возьмём с ваших рук."
```suggestion
	description = "TerraGov не смог получить новую униформу для заключённых, так что если у вас есть запасная, то мы её возьмём с ваших рук."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/security.dm
> +	description = "В результате ДТП с машиной с машиной клоуна, нам бы не помешало переправить автомобильные номера, созданные вашими заключёнными."
```suggestion
	description = "В результате ДТП с участием клоунской машины, нам бы пригодились автомобильные номера, созданные вашими заключёнными."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/security.dm
> +	name = "Наушники"
```suggestion
	name = "Противошумные наушники"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/security.dm
> +	description = "Центральное Командование устало от сообщений с вашей станции. Они запросила вас отправить несколько наушников для уменьшения раздражения."
```suggestion
	description = "Центральное Командование устало от сообщений с вашей станции. Они запросила вас отправить несколько противошумных наушников для уменьшения раздражения."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/security.dm
> +	description = "Проведите рутинную инспекцию безопасности, используя N-спектральный сканнер в следующей зоне на станции:"
```suggestion
	description = "Проведите рутинную инспекцию безопасности, используя сканнер N-spect в следующей зоне на станции:"
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/assistant.dm
> +	description = "Нанотрейзен интересуется странными объектами. Найдите один в технических туннелях и отправьте сразу же на ЦентКом."
```suggestion
	description = "Нанотрейзен интересуется странными объектами. Найдите один в технических тоннелях и отправьте сразу же на ЦК."
```

2024-04-20 11:56 UTC, larentoun commented on code/modules/cargo/bounties/assistant.dm
> +	description = "Нанотрейзен установило что ходьба расточительна. Отправьте скутер на ЦентКом для ускорения операций."
```suggestion
	description = "Нанотрейзен установило, что ходьба расточительна. Отправьте скутер на ЦК для ускорения операций."
```

2024-04-23 12:06 UTC, Chorden523 commented on tgui/packages/tgui/interfaces/CivCargoHoldTerminal.jsx
> +                  {pad ? 'Онлайн' : 'Не обнаружен'}
> Может, "Работает", "Готово"?

Я больше склоняюсь к "Функционирует"

2024-04-23 12:26 UTC, Chorden523 commented on code/modules/cargo/bounties/chef.dm
> +	description = "Нанотрейзен хочет улучшить отношения с её дочерней компанией, Японотрейзен. Отправьте Тяван-муси немедленно."
> Тавян?

Залезал в вики, там было Тяван-Муси, решил взять его

2024-04-23 12:30 UTC, Chorden523 commented on code/modules/cargo/bounties/chef.dm
> +	description = "Убери весь шашлык со станции, и ты станешь едою. Отправьте на ЦентКом для удаления из помещения."
Будем думать значит как лучше

2024-04-23 13:24 UTC, Chorden523 commented
Вроде всё прогнал, как надо было

2024-04-23 15:25 UTC, larentoun requested changes
Гораздо лучше. Посмотри линтер, он ругается на некоторые файлы. Открой их и нажми сохрани файл, должен Prettier сработать

2024-04-23 15:25 UTC, larentoun commented on code/game/machinery/civilian_bounties.dm
> +		status_report += "Заказ выполнен! Передайте ваш баунти куб-награду в отдел снабжения, чтобы получить денежную выплату."
```suggestion
		status_report += "Заказ выполнен! Передайте ваш куб-награду в отдел снабжения, чтобы получить денежную выплату."
```

2024-04-23 15:25 UTC, larentoun commented on code/modules/cargo/bounties/assistant.dm
> +	description = "Один из учёных на ЦК заинтересован в тестировании продуктов на шкуре обезьян. Ваша задача состоит в том чтобы получить шкуру и отправить её."
```suggestion
	description = "Один из учёных на ЦК заинтересован в тестировании продуктов на шкуре обезьян. Ваша задача состоит в том, чтобы получить шкуру и отправить её."
```

2024-04-23 15:25 UTC, larentoun commented on code/modules/cargo/bounties/assistant.dm
> +	description = "Дети доктора Джонса снова съели все наши мелки. Пожалуйста отправьте нам свои."
```suggestion
	description = "Дети доктора Джонса снова съели все наши мелки. Пожалуйста, отправьте нам свои."
```

2024-04-23 15:25 UTC, larentoun commented on code/modules/cargo/bounties/assistant.dm
> +	name = "Канистра воды"
```suggestion
	name = "Бак с водой"
```

2024-04-23 15:25 UTC, larentoun commented on code/modules/cargo/bounties/assistant.dm
> +	description = "Мы выясняем как сильно мы можем запускать осколки суперматтерии из пневматической пушки. Отправьте нам одну как только возможно."
```suggestion
	description = "Мы выясняем, как сильно мы можем запускать осколки суперматтерии из пневматической пушки. Отправьте нам одну как можно скорее."
```

2024-04-23 15:25 UTC, larentoun commented on tgui/packages/tgui/interfaces/Cargo.jsx
> +        <LabeledList.Item label="Сообщение от Центрального Командования">{message}</LabeledList.Item>
```suggestion
        <LabeledList.Item label="Сообщение от ЦК">{message}</LabeledList.Item>
```

2024-04-23 15:25 UTC, larentoun commented on tgui/packages/tgui/interfaces/Cargo.jsx
> +            )) || <Box color="bad">Отдан в займ Центральному Командованию</Box>}
```suggestion
            )) || <Box color="bad">Отдан в займ для ЦК</Box>}
```

2024-04-23 15:37 UTC, dj-34 commented on code/modules/cargo/bounties/assistant.dm
> +	description = "Дети доктора Джонса снова съели все наши мелки. Пожалуйста отправьте нам свои."
Перевод name'ингов? Харам...

2024-04-26 13:31 UTC, larentoun commented
Перевожу в драфт. Как будет готово - открывай для ревью.

Там обновили интерфейс у карго консоли, потому, ПР немного сломался.

2024-04-29 22:11 UTC, larentoun commented
У тебя конфликт в файлах

2024-05-06 00:33 UTC, closed without merging