перевёл указанный файл с учётом правок
ss220club/Bandastation pull request #183
Opened 2024-04-20 21:14 UTC by VaskaPepelov

## About The Pull Request

перевёл файл фобий....
## Why It's Good For The Game

туплю и сру..... сори....

2024-04-20 21:15 UTC, VaskaPepelov commented
фух..... С третьей попытки только вроде сделал как надо, таков путь джуна.........

2024-04-23 14:34 UTC, VaskaPepelov commented
балин, понял, увидел

2024-04-23 14:39 UTC, VaskaPepelov commented
когда убирал окончания слов лишнюю запятую вставил....

2024-04-23 15:07 UTC, larentoun requested changes
Оставь английские варианты тоже, так как игромеханически мы не всё перевели, чтобы оно работало корректно

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"плав",
```suggestion
		"плавн",

```

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"скрежет",
оставь gnash тоже, так как это делают карпы при атаке

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"скольз"
подскольз тоже

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"ЭЙИ",
неиспользуемый мем

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"гсб",
и англ, и рус оставляй для глав

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"эскадрон смерти",
добавь еще деды

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"центком",
```suggestion
		"цк",

```

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"нанотрайзен",
```suggestion
		"нанотрейзен",

```

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"скольз"
подскольз тоже

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"ассистент",
ассистос тоже

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"смг",
пп тоже

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"антагонист",
антаг тоже сожрет это

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"искуственный интелект",
```suggestion
		"искуственный интеллект",

```

2024-04-23 15:07 UTC, larentoun commented on strings/phobia.json
> +		"сек",
не добавил "охран" и "офицер"

2024-04-23 15:21 UTC, VaskaPepelov commented
будет сделано

2024-04-23 15:21 UTC, VaskaPepelov commented on strings/phobia.json
> +		"искуственный интелект",
(:

2024-04-23 15:25 UTC, VaskaPepelov commented on strings/phobia.json
> +		"ЭЙИ",
В чате советовали оставить, но вам виднее.

2024-04-23 15:41 UTC, VaskaPepelov commented on strings/phobia.json
> +		"ласт",
Тут отсылка на ксеногорничную Lusty поэтому Ласт потому что навряд ли её имя будут адаптировать, хотя окончание я наверное зря убрал.

2024-04-23 16:09 UTC, VaskaPepelov commented
кхм.... не увидел одно сообщение, сейчас доделаю.....

2024-04-23 16:21 UTC, VaskaPepelov commented
вот теперь точно всё учёл

2024-04-24 19:47 UTC, larentoun commented
Уберешь из драфта, как будет готово к ревью

2024-05-02 11:17 UTC, larentoun commented
Не стейл. Не стейл ведь?

2024-05-05 18:12 UTC, VaskaPepelov commented
просмотрел всежим взглядом, вроде всё как надо

2024-06-05 00:51 UTC, closed without merging

2024-06-05 14:01 UTC, larentoun commented
Это печально