Translation of bot phrases
ss220club/Bandastation pull request #204
Opened 2024-04-22 15:22 UTC by HardexZ

## About The Pull Request

Перевод фраз ботов

## Why It's Good For The Game

Перевод круто

## Changelog

:cl:
qol: Перевод фраз ботиков
/:cl:

2024-04-22 17:19 UTC, dj-34 requested changes

2024-04-22 17:19 UTC, dj-34 commented on code/__DEFINES/robots.dm
> +#define HYGIENEBOT_VOICED_ARSEHOLE "Дай, блядь, я тебя почищу!"
```suggestion
#define HYGIENEBOT_VOICED_ARSEHOLE "Просто, блядь, позволь мне вымыть тебя, засранец!"
```

2024-04-22 17:19 UTC, dj-34 commented on code/__DEFINES/robots.dm
> +#define HYGIENEBOT_VOICED_FUCKING_FINALLY "Блять наконец-то."
```suggestion
#define HYGIENEBOT_VOICED_FUCKING_FINALLY "Блять, наконец-то."
```

2024-04-22 17:19 UTC, dj-34 commented on code/__DEFINES/robots.dm
> +#define HYGIENEBOT_VOICED_DEGENERATE "Ну, блядь, пора тебе, дегенерат."
```suggestion
#define HYGIENEBOT_VOICED_DEGENERATE "Давно пора, блядь, ты, дегенерат."
```

2024-04-22 17:19 UTC, dj-34 commented on code/__DEFINES/robots.dm
> +#define MEDIBOT_VOICED_NOT_A_GAME "Выключи компютер. Это не игра."
```suggestion
#define MEDIBOT_VOICED_NOT_A_GAME "Выключи компьютер. Это не игра."
```

2024-04-22 17:19 UTC, dj-34 commented on code/__DEFINES/robots.dm
> +#define MEDIBOT_VOICED_GOOD_PERSON "Ты хороший человек."
У нас на станции не только люди (к сожалению)
```suggestion
#define MEDIBOT_VOICED_GOOD_PERSON "Ты хороший."
```

2024-04-22 17:19 UTC, dj-34 commented on code/__DEFINES/robots.dm
> +#define MEDIBOT_VOICED_PUT_BACK	"Пожалуста верите меня на место."
```suggestion
#define MEDIBOT_VOICED_PUT_BACK	"Пожалуйста, верните меня на место."
```

2024-04-23 07:10 UTC, Gaevtyr commented on code/__DEFINES/robots.dm
> +#define MEDIBOT_VOICED_BEHAVIOUR_REPORTED "Я должил о вашем поведении, хорошего дня."
Должил= Доложил

2024-04-23 11:16 UTC, Gaxeer requested changes

2024-04-23 11:16 UTC, Gaxeer commented on code/__DEFINES/robots.dm
> +#define BEEPSKY_VOICED_SECURE_DAY "Безопасного дня вам!"
```suggestion
#define BEEPSKY_VOICED_SECURE_DAY "Желаю вам безопасного дня!"
```

2024-04-23 11:16 UTC, Gaxeer commented on code/__DEFINES/robots.dm
> +#define FIREBOT_VOICED_STOP_DROP "Остановитесь, упадите и катитесь!"
```suggestion
#define FIREBOT_VOICED_STOP_DROP "Остановитесь, упадите и катайтесь на месте!"
```

2024-04-23 11:16 UTC, Gaxeer commented on code/__DEFINES/robots.dm
> +#define FIREBOT_VOICED_KEEP_COOL "Незапаривайтесь."
```suggestion
#define FIREBOT_VOICED_KEEP_COOL "Сохраняйте спокойствие."
```

2024-04-23 15:36 UTC, dj-34 approved these changes

2024-04-29 14:26 UTC, Gaxeer commented on code/__DEFINES/robots.dm
> +#define FIREBOT_VOICED_ONLY_YOU "Только вы можете предотвратить пожары на станциях."
```suggestion
#define FIREBOT_VOICED_ONLY_YOU "Только вы можете предотвратить пожары на станции."
```

2024-04-29 14:27 UTC, Gaxeer approved these changes

2024-04-29 14:27 UTC, merged