SurgeryTranslate
ss220club/Bandastation pull request #224
Opened 2024-04-26 17:44 UTC by AloeNeverDie

## Что этот PR делает

Перевод хирургии и операций в целом, пока что ПР в разработке, скоро доделаю

## Почему это хорошо для игры

Нужен перевод.

## Changelog

🆑
qol: Перевод хирургии
🆑

---------

2024-04-27 13:42 UTC, awkwardsocialist commented on code/modules/surgery/autopsy.dm
> +	name = "Исследуйте труп (сканер для аутопсии)"
```suggestion
	name = "Проведите вскрытие (сканер аутопсии)"
```

2024-04-27 13:43 UTC, awkwardsocialist commented on code/modules/surgery/autopsy.dm
> +		span_warning("[user] облажался, оставив ушиб на груди [target]!"),
А если пол женский?

2024-04-27 13:46 UTC, awkwardsocialist commented on code/modules/surgery/blood_filter.dm
> +		span_notice("[tool.name] сигнализирует, когда прекращает перекачивать кровь у [target]."),
```suggestion
		span_notice("[tool.name] сигнализирует, что закончил перекачивать кровь у [target]."),
```

2024-04-27 13:46 UTC, awkwardsocialist commented on code/modules/surgery/blood_filter.dm
> +		span_notice("[tool.name] сигнализирует, когда прекращает перекачивать кровь."),
```suggestion
		span_notice("[tool.name] сигнализирует, что закончил перекачивать кровь."),
```

2024-04-27 13:49 UTC, awkwardsocialist commented on code/modules/surgery/bone_mending.dm
> +	name = "Устранение перелома кости (закрытый)"
```suggestion
	name = "Сращивание перелома (трещины) кости"
```

2024-04-27 13:50 UTC, awkwardsocialist commented on code/modules/surgery/bone_mending.dm
> +	name = "Устранение перелома кости (открытый)"
```suggestion
	name = "Сращивание открытого перелома кости"
```

2024-04-27 13:54 UTC, awkwardsocialist commented on code/modules/surgery/bone_mending.dm
> +	name = "Устраните открытый перелом кости (костоправ/костный гель)"
Лента на паста

2024-04-27 13:55 UTC, AloeNeverDie commented on code/modules/surgery/autopsy.dm
> +		span_warning("[user] облажался, оставив ушиб на груди [target]!"),
Увы? Нейтральное слово для обоих гендеров пока не придумал

2024-04-27 13:59 UTC, awkwardsocialist commented on code/modules/surgery/brain_surgery.dm
> +	name = "Операция на мозг"
```suggestion
	name = "Операция на мозге"
```

2024-04-27 14:08 UTC, AloeNeverDie commented on code/modules/surgery/bone_mending.dm
> +	name = "Устраните открытый перелом кости (костоправ/костный гель)"
Поменял, залью со след комитом

2024-04-27 15:03 UTC, awkwardsocialist requested changes

2024-04-27 15:03 UTC, awkwardsocialist commented on code/modules/surgery/organic_steps.dm
> +				span_notice("Вокруг [human_target]'s [parse_zone(target_zone)] образуется лужа крови."),
's. Также лужа крови не вокруг него самого, а вокруг надреза внутри таргета.

2024-04-27 15:03 UTC, awkwardsocialist commented on code/modules/surgery/organic_steps.dm
> +	display_pain(target, "Вы чувствуете, как вас <i>осторожный</i> колющий удар в [parse_zone(target_zone)].")
Что-то с согласованием предложения случилось

2024-04-27 15:03 UTC, awkwardsocialist commented on code/modules/surgery/organic_steps.dm
> +	display_pain(target, "Вы чувствуете сильную жгучую боль, распространяющуюся по всей [parse_zone(target_zone)], когда кожа возвращается в прежнее состояние!")
```suggestion
	display_pain(target, "Вы чувствуете сильную жгучую боль, распространяющуюся по всей [parse_zone(target_zone)], по мере того, как кожа возвращается в прежнее состояние!")
```

2024-04-27 16:08 UTC, AloeNeverDie commented on code/modules/surgery/burn_dressing.dm
> +		display_pain(target, "Ожоги в [parse_zone(user.zone_selected)] адски зудят!")
Ну, решил так оставить, если кто-то ещё выразит мнение поменять - поменяю

2024-04-27 17:51 UTC, awkwardsocialist commented on code/modules/surgery/autopsy.dm
> +		span_warning("[user] облажался, оставив ушиб на груди [target]!"),
> Увы? Нейтральное слово для обоих гендеров пока не придумал

"Ошибается" может вполне зайти

2024-04-28 08:56 UTC, awkwardsocialist commented on code/modules/surgery/mechanic_steps.dm
> +	display_pain(target, "Вы ощущаете как начинаете получать показания датчиков из [parse_zone(target_zone)], после того, как панель закрутили обратно.", TRUE)
Не могу suggestion сделать, перед как запятая пропущена

2024-04-28 08:57 UTC, awkwardsocialist commented on code/modules/surgery/mechanic_steps.dm
> +	name = "открытойте люк (рука)"
```suggestion
	name = "откройте люк (рука)"
```

2024-04-28 09:02 UTC, awkwardsocialist commented on code/modules/surgery/mechanic_steps.dm
> +	display_pain(target, "Вы получаете последние показания датчиков из вашей [parse_zone(target_zone)], когда открывается люк.", TRUE)
```suggestion
	display_pain(target, "Вы перестаёте получать показания датчиков из вашей [parse_zone(target_zone)], по мере того как открывается люк.", TRUE)
```

2024-04-28 09:04 UTC, awkwardsocialist commented on code/modules/surgery/revival.dm
> +	target.visible_message(span_warning("...[target.p_they()] бьется в конвульсиях [target.p_s()], то замирает."))
```suggestion
	target.visible_message(span_warning("...[target.p_they()] бьется в конвульсиях [target.p_s()], после чего замирает."))
```

2024-04-28 09:06 UTC, awkwardsocialist commented on code/modules/surgery/stomachpump.dm
> +	name = "промывание желудка (рука)"
```suggestion
	name = "промойте желудок (рука)"
```

2024-04-28 09:08 UTC, awkwardsocialist commented on code/modules/surgery/surgery_step.dm
> +			screwedmessage = " У вас почти получилось."
```suggestion
			screwedmessage = "А ведь у вас почти получилось."
```

2024-04-28 09:10 UTC, awkwardsocialist commented on code/modules/surgery/surgery_step.dm
> +		var/you_feel = pick("легкая боль", "ваше тело напрягается", "тревожное ощущение")
```suggestion
		var/you_feel = pick("легкую боль", ", как ваше тело напрягается", "тревожное ощущение")
```
Согласуй с следующей строкой

2024-04-28 09:10 UTC, awkwardsocialist commented on code/modules/surgery/surgery_step.dm
> +		target.show_message(vague_message, MSG_VISUAL, span_notice("Вы чувствуете [you_feel], как вас оперируют."))
```suggestion
				vague_message = span_notice("Вы чувствуете [you_feel], по мере того как вас оперируют.")
		target.show_message(vague_message, MSG_VISUAL, span_notice("Вы чувствуете [you_feel], по мере того как вас оперируют."))
```

2024-04-28 09:19 UTC, awkwardsocialist commented on code/modules/surgery/bone_mending.dm
> +			span_notice("[user] приступает к устранению перелома [target]'s [parse_zone(user.zone_selected)]."),
's остались

2024-04-28 09:19 UTC, awkwardsocialist commented on code/modules/surgery/bone_mending.dm
> +			span_notice("[user] успешно восстанавил кость в [parse_zone(target_zone)] у [target]!"),
```suggestion
			span_notice("Вы успешно восстановили кость в [parse_zone(target_zone)] у [target]."),
			span_notice("[user] успешно восстановил кость в [parse_zone(target_zone)] у [target] при помощи [tool.name]!"),
			span_notice("[user] успешно восстановил кость в [parse_zone(target_zone)] у [target]!"),
```

2024-04-28 09:19 UTC, awkwardsocialist commented on code/modules/surgery/bone_mending.dm
> +		log_combat(user, target, "успешно восстанавил кость в", addition="COMBAT MODE: [uppertext(user.combat_mode)]")
```suggestion
		log_combat(user, target, "успешно восстановил кость в", addition="COMBAT MODE: [uppertext(user.combat_mode)]")
```

2024-04-28 17:28 UTC, awkwardsocialist approved these changes

2024-04-29 14:32 UTC, merged