Волшебный перевод Спейс Визарда
ss220club/Bandastation pull request #229
Opened 2024-04-27 18:50 UTC by Ingakem

## About The Pull Request
Перевод чаклуна

## Why It's Good For The Game
Потому что, потому

## Changelog

:cl:
Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод Перевод 
/:cl:

2024-04-28 19:04 UTC, larentoun requested changes
Пока поверхностно так

2024-04-28 19:04 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoWizard.tsx
> +                  Вы - Космический Маг!
У нас они будут Волшебниками, потому что Федерация космических волшебников. Там снизу поправишь

2024-04-29 22:25 UTC, larentoun commented
Я там на апстрим кое-что залил, будет конфликт. Как обновишься, пингани еще раз

2024-04-30 19:13 UTC, larentoun commented
Ты дефайны забыл перевести

2024-05-01 13:51 UTC, larentoun requested changes
У тебя в учениках в .dm файле переведены названия заклинаний, а в .tsx нет. Определись.

Также, "wizard garb" лучше перевести как "одеяния волшебника", а не "одежда волшебника". Я не выделял их в обзоре.

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/assistance.dm
> +	desc = "Арканный посох, способный стрелять зарядами эльдрической энергии, которые заставляют оживать неодушевленные предметы. Эта магия не действует на машины.."
```suggestion
	desc = "Арканный посох, способный стрелять зарядами эльдрической энергии, которые заставляют оживать неодушевленные предметы. Эта магия не действует на машины."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/assistance.dm
> +		Заклинание Artificer позволяет создавать арканные машины для пойманных душ, которыми они могут управлять."
```suggestion
		Заклинание Artificer позволяет создавать магические машины для пойманных душ, которыми они могут управлять."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/assistance.dm
> +	desc = "Камень некроманта способен воскресить трех мертвецов в виде рабов скелетов, которыми вы можете командовать."
```suggestion
	desc = "Камень некроманта способен воскресить трех мертвецов в скелетов-рабов, подчиненных вам."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/assistance.dm
> +		похожи на демонов резни, но они не убивают своих жертв навсегда \
```suggestion
		похожи на демонов резни, но они не убивают своих жертв навсегда, \
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Выкованный из эльдрической энергии, пакетик чистой силы, \
```suggestion
	desc = "Выкованный из мистической энергии, пакетик чистой силы, \
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Выкованный из эльдрической энергии, пакетик чистой силы, \
Может не "пакетик", а сгусток? Куча? Как в игре выглядит спрайт посмотри и опиши его - пакетик звучит супер странно

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Вызовите вокруг себя несколько ловушек. Они нанесут урон и разозлят любых врагов, которые на них наступят."
Скорее не "разозлят", а превратят в берсерка? Надо слово подобрать и проверить, что делает заклинание

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +		мгновенно вызывая рой пчел в ваше местоположение. Эти пчелы НЕ дружелюбны ко всем."
```suggestion
		мгновенно вызывая рой пчел в ваше местоположение. Эти пчелы НЕ дружелюбны к кому-либо."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Мощная защитная руна, она дает восемь дополнительных зарядов к силовому щиту боевого мага."
```suggestion
	desc = "Мощная защитная руна, предоставляющая восемь дополнительных зарядов к силовому щиту боевого мага."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/mobility.dm
> +	desc = "Особый посох, способный превращать твердые стены в украшенные двери. Пригодится для передвижения при отсутствии другого транспорта. Не работает со стеклом."
```suggestion
	desc = "Особый посох, способный превращать твердые стены в украшенные двери. Пригодится для передвижения при отсутствии другого вида передвижения. Не работает со стеклом."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/offensive.dm
> +	desc = "Выпустите в противников поток арканной энергии с помощью этого (мощного) заклинания. Наносит гораздо больше урона, чем Lesser Summon Guns, но не сбивает цели с ног. Для использования требуют
```suggestion
	desc = "Выпустите в противников поток магической энергии с помощью этого (мощного) заклинания. Наносит гораздо больше урона, чем Lesser Summon Guns, но не сбивает цели с ног. Для использования требуются обе свободные руки. Изучив это заклинание, вы не сможете выучить Lesser Summon Gun."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/offensive.dm
> +	desc = "Садистское заклинание сангвиника, наносящее многочисленные тяжелые кровоточащие раны по всему телу жертвы."
```suggestion
	desc = "Садистско-кровожадное заклинание, наносящее многочисленные тяжелые кровоточащие раны по всему телу жертвы."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/offensive.dm
> +	desc = "Меч, способный стрелять вспышками энергии, которые отрывают конечности у цели."
```suggestion
	desc = "Меч, способный стрелять вспышками энергии, отрывающими конечности у цели."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/summons.dm
> +	desc = "Нет ничего плохого в том, чтобы вооружить команду сумасшедших, которые только и ждут повода, чтобы убить вас.. \
```suggestion
	desc = "Нет ничего плохого в том, чтобы вооружить команду сумасшедших, которые только и ждут повода, чтобы убить вас. \
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/spellbook_entries/summons.dm
> +		Велика вероятность, что они первыми перестреляют друг друга."
```suggestion
		Но велика вероятность, что они сперва перестреляют друг друга."
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
> +		to_chat(user, span_notice("Вы привязываете [src] к себе."))
```suggestion
		to_chat(user, span_notice("Вы привязываете [src.name] к себе."))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
> +			to_chat(user, span_warning("Если бы вас поймают за подглядыванием в книгу заклинаний вашего учителя, вас скорее всего, отчислять из Академии волшебников. Лучше не стоит."))
```suggestion
			to_chat(user, span_warning("Если вас поймают за подглядыванием в книгу заклинаний вашего учителя, то, скорее всего, отчислят из Академии волшебников. Лучше не стоит."))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
> +			to_chat(user, span_warning("[src] не признает вас своим владельцем и отказывается открываться!"))
```suggestion
			to_chat(user, span_warning("Вы не признаетесь владельцем [src.name], и она не собирается открываться!"))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
> +			to_chat(user, span_warning("[src] похоже, не хочет возмещаться [O]."))
```suggestion
			to_chat(user, span_warning("Похоже, что [src.name] не хочет возвращать очки за [O.name]."))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
> +			to_chat(user, span_warning("Вы не можете вернуть [src]."))
```suggestion
			to_chat(user, span_warning("Вы не можете вернуть очки за [src.name]."))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
> +			to_chat(user, span_warning("[src] похоже, не хочет возмещаться [O]."))
```suggestion
			to_chat(user, span_warning("Похоже, что [src.name] не хочет возвращать очки за [O.name]."))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/equipment/wizard_spellbook.dm
> +			to_chat(user, span_warning("Вы не можете вернуть [O]."))
```suggestion
			to_chat(user, span_warning("Вы не можете вернуть очки за [O.name]."))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/grand_ritual/grand_ritual.dm
> +	target_turf.balloon_alert(owner, "вызываем руна...")
```suggestion
	target_turf.balloon_alert(owner, "вызываем руну...")
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/grand_ritual/grand_ritual.dm
> +			to_chat(owner, span_revenbignotice("ДА! СЫР! СЫР ДЛЯ ВСЕХ! ТАКОЙ ГРАНДИОЗНЫЙ ПРАЗДНИК! ТЫ ПОЛУЧИШЬ СВОЙ ПРИЗ, МОЙ ЧЕМПИОН!!!"))
```suggestion
			to_chat(owner, span_revenbignotice("ДА! СЫР! СЫР ДЛЯ ВСЕХ! ТАКОЙ ГРАНДИОЗНЫЙ ПРАЗДНИК! ТЫ ПОЛУЧИШЬ СВОЙ ПРИЗ, МОЙ ЧЕМПИОН!!"))
```

2024-05-01 13:51 UTC, larentoun commented on code/modules/antagonists/wizard/grand_ritual/grand_rune.dm
> +		list("Свифткаст! Хастега! Abjurer's Ward 2! Продление 4! Продвинутое усиление Тенсера! Защита от добра! Усиление эффекта 3! Аркановое ус...",
```suggestion
		list("Свифткаст! Хастега! Ограждающее поле 2! Продление 4! Продвинутое усиление Тенсера! Защита от добра! Усиление эффекта 3! Аркановое ус...",
```

2024-05-01 13:51 UTC, larentoun commented on tgui/packages/tgui/interfaces/Spellbook.tsx
> +        content="Наборы снаряжения одобренные волшебниками"
```suggestion
        content="Наборы снаряжения, одобренные волшебниками"
```

2024-05-01 13:51 UTC, larentoun commented on tgui/packages/tgui/interfaces/Spellbook.tsx
> +              {entry.cost} очко
```suggestion
              {entry.cost} очков
```

2024-05-01 13:51 UTC, larentoun commented on tgui/packages/tgui/interfaces/Spellbook.tsx
> +      return 'Вглядываем';
```suggestion
      return 'Вглядывание';
```

2024-05-01 17:13 UTC, Ingakem commented on code/modules/antagonists/wizard/equipment/spellbook_entries/defensive.dm
> +	desc = "Вызовите вокруг себя несколько ловушек. Они нанесут урон и разозлят любых врагов, которые на них наступят."
Это спелл который спавнит в радиусе от волшебника ели заметные трапы, которые наносят различный урон от типа ловушки и станят, поэтому и разозлят тех кто на них встанет

2024-05-02 00:18 UTC, larentoun approved these changes
LGTM, fast-merge

2024-05-02 00:18 UTC, merged