TranslateForgottenQuirk
ss220club/Bandastation pull request #230
Opened 2024-04-28 03:30 UTC by AloeNeverDie

## About The Pull Request

Забыл перевести данную черту.

## Why It's Good For The Game

Надо, чтобы все было переведено.

2024-04-28 09:24 UTC, Gaxeer requested changes

2024-04-28 09:24 UTC, Gaxeer commented on code/datums/quirks/negative_quirks/anosmia.dm
> +	desc = "По какой-то причине вы ничего не чувствуете."
```suggestion
	desc = "По какой-то причине вы не чувствуете запахи."
```

2024-04-28 09:24 UTC, Gaxeer commented on code/datums/quirks/negative_quirks/anosmia.dm
> +	gain_text = span_notice("Вы обнаруживаете, что не можете ничего почувствовать!")
```suggestion
	gain_text = span_notice("Вы обнаруживаете, что перестали чувствовать запахи!")
```

2024-04-28 09:24 UTC, Gaxeer commented on code/datums/quirks/negative_quirks/anosmia.dm
> +	medical_record_text = "Пациент потерял чувство обоняния."
```suggestion
	medical_record_text = "Пациент страдает потерей обоняния."
```

2024-04-29 14:12 UTC, larentoun approved these changes

2024-04-29 14:12 UTC, merged