Translate-engineering
ss220club/Bandastation pull request #235
Opened 2024-04-28 18:47 UTC by Dlonir

## About The Pull Request
Перевод газов атмоса в информационной консоли

2024-04-29 14:08 UTC, larentoun requested changes
Почему бублик пропал из названия HFR. Гипер-торусовый термоядерный реактор, ведь форма бублика (торуса), ну.

Прошелся поверхностно. Название газов - не имена собственные в русском языке, насколько я понимаю, пиши их со строчной.

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	Сделайте ваше охлаждение, поместите внутрь замедлителя газы с высокой теплоёмкостью (гиперноблиум поможет справиться с этой проблемой)<BR><BR>\
```suggestion
	Усильте ваше охлаждение, поместите внутрь замедлителя газы с высокой теплоёмкостью (гипер-ноблиум поможет справиться с этой проблемой)<BR><BR>\
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	-Вы не можете запустить реактор, если уровень мощности превышает 0.<BR>\
Точно не "выключить"? Похоже на опечатку в английском

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	-Из термоядерной смеси нельзя удалить газы, за исключением Геалия и Антиноблия.<BR>\
```suggestion
	-Из термоядерной смеси нельзя удалить газы, за исключением гелия и анти-ноблиума.<BR>\
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	-Гиперноблиум значительно уменьшит мощность вашей смеси.<BR>\
```suggestion
	-Гипер-ноблиум значительно уменьшит мощность вашей смеси.<BR>\
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	-Антиноблиум значительно УВЕЛИЧИТ мощность вашей смеси.<BR>\
```suggestion
	-Анти-ноблиум значительно УВЕЛИЧИТ мощность вашей смеси.<BR>\
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	используйте более продвинутые руководства, чтобы понять, как различные газы будут действовать в качестве замедлителя."
```suggestion
	Используйте более продвинутые руководства, чтобы понять, как различные газы будут действовать в качестве замедлителя."
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/electrolyzer/electrolyzer_reactions.dm
> +	name = "Электролиз Гиперноблиума"
```suggestion
	name = "Электролиз гипер-ноблиума"
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/electrolyzer/electrolyzer_reactions.dm
> +	desc = "Превращение Гиперноблиума в Антиноблиум"
```suggestion
	desc = "Превращение гипер-ноблиума в анти-ноблиум"
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/electrolyzer/electrolyzer_reactions.dm
> +		/datum/gas/hypernoblium = "1 моль Гиперноблиума будет затрачено в ходе реакции",
```suggestion
		/datum/gas/hypernoblium = "1 моль гипер-ноблиума будет затрачено в ходе реакции",
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/electrolyzer/electrolyzer_reactions.dm
> +		/datum/gas/antinoblium = "0.5 моль Антиноблиума будет образовано в ходе реакции",
```suggestion
		/datum/gas/antinoblium = "0.5 моль анти-ноблиума будет образовано в ходе реакции",
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/electrolyzer/electrolyzer_reactions.dm
> +		"Температура" = "Может произойти только при температуре ниже 150 Кельвинов..",
```suggestion
		"Температура" = "Может произойти только при температуре ниже 150 Кельвинов.",
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/electrolyzer/electrolyzer_reactions.dm
> +		"Энергия" = "91.2321 kJ тепловой энергии выделяется на моль потребленного BZ.",
```suggestion
		"Энергия" = "91.2321 кДж тепловой энергии выделяется на моль потребленного BZ.",
```

2024-04-29 14:08 UTC, larentoun commented on code/modules/atmospherics/machinery/components/electrolyzer/electrolyzer_reactions.dm
> +		/datum/gas/oxygen = "На один моль потребленного БЗ образуется 0,2 моль кислорода.",
```suggestion
		/datum/gas/oxygen = "На один моль потребленного BZ образуется 0,2 моль кислорода.",
```

2024-04-30 17:40 UTC, Dlonir commented on tgui/packages/tgui/interfaces/common/AtmosHandbook.tsx
> +          <Box mb="0.5em">{'Ход реакции:'}</Box>
Ну потому что там как раз описывается о том, что происходит при прохождении определённой реакции: Что затрачивается, что получается, условия для неё.
И как мне показалось именно "Ход" будет лучше звучать и логичнее чем факторы реакции

2024-04-30 17:44 UTC, Dlonir commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	default_raw_text = "<B>Как безопасно работать с Термоядерным реактором</B><BR>\
Я вот тут не понял что за ТМ и решил убрать, т.к. не несёт никакой смысловой нагрузки по сути оно. Разве оно необходимо?

2024-04-30 17:47 UTC, Dlonir commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	Если heat output не уменьшается, попробуйте менять magnetic costrictors до тех пор, пока heat output не станет падать. \
Ну тут же речь идёт про температуру на выходе "Heat output" и мне показалось странным, что температура становится негативной т.к. она по кельвинам не может быть отрицательной, вот и перевёл как "Уменьшение"

2024-04-30 17:53 UTC, Dlonir commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	-Вы не можете запустить реактор, если уровень мощности превышает 0.<BR>\
Ну тут да, кажется будто бы должно быть именно запустить. Хотя когда я запускал ради тесте ХФР то при уровне 3 и когда я его отключил - я не смог именно заново его включить. Поэтому я решил пока не менять на "выключить" а оставить как есть, ибо непонятно баг или нет

2024-04-30 19:11 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	default_raw_text = "<B>Как безопасно работать с Термоядерным реактором</B><BR>\
Это просто смешнявка

2024-04-30 19:12 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	Если heat output не уменьшается, попробуйте менять magnetic costrictors до тех пор, пока heat output не станет падать. \
Просто вопрос про то, какие числы оно показывает. Возможно, отрицательное значение как раз и есть "уменьшение". Я HFR не настраивал

2024-05-19 13:01 UTC, larentoun requested changes
БЗ или BZ - определись

так же пробегись по остальным газам - англ или рус

2024-05-22 16:22 UTC, larentoun commented
Синхронизируй еще с этим, или это вдобавок https://github.com/ss220club/Bandastation/pull/227/files

2024-05-22 17:10 UTC, larentoun requested changes

2024-05-22 17:10 UTC, larentoun commented on code/modules/atmospherics/machinery/components/fusion/hfr_parts.dm
> +	-Вы не можете запустить реактор, если уровень мощности превышает 0.<BR>\
Нет, тут именно, что кнопка "выключить" перестает работать. Точно опечатка на инглише

2024-06-16 00:56 UTC, closed without merging