перевод мафии
ss220club/Bandastation pull request #255
Opened 2024-05-06 15:16 UTC by Kar4es

## About The Pull Request
Перевел мафию. Теперь непонятная хуйня будет еще непонятнее.

## Changelog

:cl:
/:cl:

2024-05-14 09:01 UTC, larentoun requested changes
Для начала поправь все `ability_action`.

"Вы (null/более не) готовитесь ([ДЕЙСТВИЕ]) ([ЦЕЛЬ]).":
"Вы готовитесь расследовать Вася Петкин."
"Вы готовитесь защищаться."
"Вы более не готовитесь брутально убивать Иван Иванович."

2024-05-14 09:01 UTC, larentoun commented on code/modules/mafia/abilities/abilities.dm
> +		feedback_text = replacetext(feedback_text, "%WILL_PERFORM%", "сейчас")
```suggestion
		feedback_text = replacetext(feedback_text, "%WILL_PERFORM%", "")
```

2024-06-10 07:45 UTC, Gaxeer approved these changes

2024-06-10 07:45 UTC, Gaxeer commented
Конфликт исправь

2024-06-12 11:55 UTC, larentoun requested changes
Исправь ability_action

Что значит "вы готовитесь общайтесь с духами"?

2024-06-12 11:55 UTC, larentoun commented on code/modules/mafia/abilities/investigative/pray.dm
> +	ability_action = "общайтесь с духами"
```suggestion
	ability_action = "общаться с духами"
```

2024-06-12 11:55 UTC, larentoun commented on code/modules/mafia/abilities/investigative/pray.dm
> +	host_role.send_message_to_player(span_warning("Вы вызывали дух [target_role.body.real_name] и узнали, что его роль была <b>[target_role.name]<b>."))
```suggestion
	host_role.send_message_to_player(span_warning("Вы призвали дух [target_role.body.real_name] и узнали, что его роль была <b>[target_role.name]<b>."))
```

2024-06-12 11:55 UTC, larentoun commented on code/modules/mafia/abilities/investigative/reveal.dm
> +	ability_action = "психологическая оценка"
```suggestion
	ability_action = "психологически оценить"
```

2024-06-15 12:11 UTC, merged

2024-06-18 09:55 UTC, larentoun commented
Это ужасный перевод...

2024-06-19 05:43 UTC, Kar4es commented
> Это ужасный перевод...

Я чет посмотрел в игре на это дело, и... Нихуя не понял зачем существуют ability_action у большинства абилок. Они показываются только у некоторых ролей, в игре же видно только name этих абилок

2024-06-19 05:44 UTC, Kar4es commented
> Это ужасный перевод...

По факту ингейм это все выглядит нормально, за исключением того что я не перевел основные надписи в игре, которые в чат пишутся или на экране возникают

2024-06-19 05:45 UTC, Kar4es commented
Собственно наверно я поэтому и перевел так странно, ибо не понимал логики этой хуйни