Новая раса для TG SS220 – Вульпочки 🦊
ss220club/Bandastation pull request #267
Opened 2024-05-17 10:10 UTC by Nlaysi

## About The Pull Request

ПР добавляют новую [расу вульпканинов](https://wiki.ss220.club/index.php/%D0%92%D1%83%D0%BB%D1%8C%D0%BF%D0%BA%D0%B0%D0%BD%D0%B8%D0%BD), доступную при создании персонажа

![image](https://github.com/ss220club/Bandastation/assets/62209572/cf80ffd1-0143-4dea-a000-79b8c8b5fa3e)

## Why It's Good For The Game

На TG маленькое разнообразие рас, поэтому необходимо перенести расы с парадайза. Вульпкане одна из самых популярных и интересных рас с развитым лором и хорошим отыгрышем игроков. Добавление этой расы разнообразит игровой геймплей, создаст множество РП ситуаций и привлечет новых игроков.

![image](https://github.com/ss220club/Bandastation/assets/62209572/31e5822a-6823-4a90-962d-bc86d340d155)

## Changelog

:cl:
add: Новая раунд-стартовая раса "Вульпканин"
/:cl:

2024-05-17 10:11 UTC, AyIong commented
Да заебали с этими вульпами...

2024-05-17 10:31 UTC, PhantornRU requested changes

2024-05-17 10:31 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/_species.dm
> +					accessory = SSaccessories.vulpkanin_facial_hair_list[source.dna.features["vulpkanin_facial_hair"]]
Не модульная часть. Плохо. С другими файлами ниже также. По хорошему для такого создается отдельный файл, т.к. в дальнейшем еще будет работа с леерами. + таким методом сложнее выискивать изменения и ошибки.

2024-05-17 10:31 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/_species.dm
> +							accessory_overlay.color = source.facial_hair_color
Тоже самое, нужно подзадолбаться, но запихнуть в модуль

2024-05-17 10:31 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/dummy.dm
> +    //target.dna.features["tail_markings"] = get_consistent_feature_entry(SSaccessories.vulpkanin_tail_markings_list)
???

2024-05-17 10:34 UTC, PhantornRU commented
Откуда портировал и почему не указал, если портировал?

Например сейчас я хочу заняться портированием с MonkeyStation. Поэтому по хорошему твой модуль нужно подготовить под будущий модуль, чтобы потом не пришлось всё переиначивать и переделывать. От того и вопрос, сам ли ты делал этот порт?
https://github.com/ss220club/Bandastation/pull/223

В чате разработки в дискорде тебя нету, что плохо.

2024-05-17 10:42 UTC, Deultus commented
Вульпкане одна из самых "интересных" с "развитым лором и хорошим отыгрышем"  "создаст множество РП ситуаций и привлечет новых игроков" Анегдот дня

2024-05-17 11:04 UTC, PhantornRU commented
> Вульпкане одна из самых "интересных" с "развитым лором и хорошим отыгрышем" "создаст множество РП ситуаций и привлечет новых игроков" Анегдот дня

а ты кто? Я не помню тебя в разработчиках. Гитхаб здесь не для кыков. Лучше бы помог перенести ништяки, коль умеешь им пользоваться.

2024-05-17 11:06 UTC, PhantornRU commented
В общем. По ПРу.
Жду ответов по прошлым вопросам. Также сразу пометки:
Разбери всё по папкам, по возможности перенеси сразу ТАЯР, чтобы ты понял о чем речь и сразу сделал всё как полагается.
С модульностью поможем-объясним.

Обратись к Ащиа за плашкой и зайди к нам в кодерский канал, поможем разобраться что куда (да, мы заманиваем тебя в подвал)

2024-05-17 11:20 UTC, Furrior commented on modular_bandastation/species/code/_defines.dm
> +#define HEAD_FACIAL_HAIR_VULPKANIN (1<<101)
Это переполненное число будет.

2024-05-17 11:20 UTC, Furrior commented on modular_bandastation/species/code/dna.dm
> +	. = ..()
Выглядит, будто, лучше сначала вызвать родитель и его потом дополнять

2024-05-17 11:20 UTC, Furrior commented on modular_bandastation/species/code/dna.dm
> +		dna.features["vulpkanin_facial_hair"] = GLOB.vulpkanin_facial_hair_list[deconstruct_block(get_uni_feature_block(dna.unique_features, DNA_VULPKANIN_FACIAL_HAIR), GLOB.vulpkanin_facial_hair_list.len)
Засунуть это в switch, чтоб не было повторных проверок

2024-05-17 11:37 UTC, Nlaysi commented
> Откуда портировал и почему не указал, если портировал?
> 
> Например сейчас я хочу заняться портированием с MonkeyStation. Поэтому по хорошему твой модуль нужно подготовить под будущий модуль, чтобы потом не пришлось всё переиначивать и переделывать. От того и вопрос, сам ли ты делал этот порт? #223
> 
> В чате разработки в дискорде тебя нету, что плохо.

Я только спрайты вульп брал [вот отсюда](https://github.com/Alecksohs/ParadiseSpriteEdits), немного доработав, человек перерисовал спрайты для парадайза под мультиплай. А порт я сам делал да

2024-05-17 11:43 UTC, Nlaysi commented
> > Вульпкане одна из самых "интересных" с "развитым лором и хорошим отыгрышем" "создаст множество РП ситуаций и привлечет новых игроков" Анегдот дня
> 
> а ты кто? Я не помню тебя в разработчиках. Гитхаб здесь не для кыков. Лучше бы помог перенести ништяки, коль умеешь им пользоваться.

а что бы вмержили, типа надо обязательно разрабом быть? не знал...

2024-05-17 12:31 UTC, PhantornRU commented on modular_bandastation/species/code/language.dm
> +// 	return ..()
???

2024-05-17 12:44 UTC, Deultus commented on modular_bandastation/species/code/vulpkanin/_vulpkanin.dm
> +	stunmod = 0.9
Вот был бы модификатор холода 0.5  а тепла =3.5, Ксенос сразу на 2 головы лучше стал бы

2024-05-17 14:25 UTC, PhantornRU commented on modular_bandastation/species/code/vulpkanin/_vulpkanin.dm
> +	stunmod = 0.9
не переусердствуй, слишком большой модификатор.
За 0.5 тут разве что 1.8/2 был бы норм

2024-05-17 14:26 UTC, larentoun commented
Это реально??

Добавь в описание ПРа особенности расы. Если это просто рескин Хумана - аппрува не будет.

Добавь в описание ПРа то, откуда ты портировал или брал ассеты.

2024-05-17 18:18 UTC, VaskaPepelov commented
Не надо вульп на тиге, по крайней мере без строгой привязки к их лору на уровне кода. Как выразился ХМЮ в дискорд канале, чтобы при выборе тех или иных кланов были уникальные причёски или цвета шкуры, и чтобы эти самые цвета были хоть сколько то натуральными.

"На TG маленькое разнообразие рас, поэтому необходимо перенести расы с парадайза. Вульпкане одна из самых популярных и интересных рас с развитым лором и хорошим отыгрышем игроков. Добавление этой расы разнообразит игровой геймплей, создаст множество РП ситуаций и привлечет новых игроков."

1) На тг и вправду мало рас но в отличии от пары каждая  крайне разнится от того же хумана значительно сильнее, этим тиге и вывозит.
2)Да самая популярная, да её текущий лор действительно интересный и продуманный, но хороший отыгрышь? мы точно на одном сервере играем? чуть ли не две трети игроков на вульпах берут их потому что "Гыгыгыгы фури", при том даже не подозревают о каком то там лоре, и ещё обязательно выберут цвет меха как блевотно кислотно синий, или розовый, или зелёный( что кстати буквально показано на скрине в пре лол)
3) Насчёт рп ситуаций, мрп - это инициатива от кого-то, следовательно хорошее рп идёт исключительно с подачи "хороших" и заряженных на рп игроков, как расписано в пункте два рассчитывать на это не стоит, банально потому что таких вытесняют рофлеры "гыгыгы фури, давай ты меня помоешь в душе а потом устроим жоскую лизню в дормах, я кстати капитан"
4) новых игроков привлекает механ и стример а не раса с крайне сомнительной репутацией.

Я не против добавления вульп, вообще, новая раса это всегда хорошо, но если мы хотим мрп и отсутствие сморщенного от кринжа ебла у обычных работяг, это нужно вводить грамотно и правильно, с учётом всех расписанных выше проблем. Делайте что хотите но мой мнение заключается в том что их внедрение в текущем виде принесёт мало хорошего в наш уютненький билдик.

постскриптум

Вырежьте феленидов к едрене фене.

2024-05-17 19:02 UTC, Deultus commented on modular_bandastation/species/code/vulpkanin/_vulpkanin.dm
> +	stunmod = 0.9
Лучше вообще не трогать модификатор, можно сделать так, чтобы у вульп  температура тела автоматически не падала после нагрева, что логично, игрокам придется искать что-то, что могло бы охладить их (к примеру чай со льдом). Правда я не помню, что конкретно за это отвечает

2024-05-22 10:48 UTC, larentoun requested changes
Думаю, что стоит убрать модификаторы урона, поднять порог холода и понизить порог жары.

Тебе ревью уже накидали, и вижу, что ты еще не закончил. Перевожу в драфт

2024-05-23 11:00 UTC, larentoun commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +
Любимая еда: meat, raw, seafood,
Не любимая еда: dairy, nuts, gross
Токсичная еда: grain, sugar, alcohol, toxic

Получается, в нейтральных остаются: vegetables, junkfood, fruit, fried, pineapple, breakfast, cloth, oranges, bugs, gore, stone

2024-05-23 11:00 UTC, larentoun commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +	hunger_modifier = 1.5
Слишком сильный модификатор

2024-05-23 11:02 UTC, larentoun commented
В орган легких дай повышенный резист к холоду и к жаре

В печени уменьши толерантность к алкоголю

2024-05-23 11:03 UTC, larentoun commented
Большие уши - большой урон по ушам

2024-05-23 11:16 UTC, larentoun commented
Глаза чуть лучше видят в темноте (удаленный трейт) - https://github.com/tgstation/tgstation/pull/83356, значение LIGHTING_CUTOFF_REAL_LOW, но получают глаза, как у молей. Флэшбенг тайм.

Disclaimer: Не уверен, что стоит добавлять ночное зрение раундстартом

2024-05-23 11:19 UTC, larentoun commented
Уменьши им зарплату до 0.8

2024-05-23 11:31 UTC, Nlaysi commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +
По лору: ```Особенности питания
Из-за строения желудка вульпканины предпочитают белковую пищу, особенно мясо. Растительная еда им не подходит, так как **плохо усваивается и вызывает дискомфорт**. В отличие от людей, вульпканины не нуждаются в клетчатке и могут питаться исключительно мясом без опасности для здоровья.``` специально так сделано что бы вульпы просили мясо у поваров

2024-05-23 11:33 UTC, Nlaysi commented
> Глаза чуть лучше видят в темноте (удаленный трейт) - [tgstation#83356](https://github.com/tgstation/tgstation/pull/83356), значение LIGHTING_CUTOFF_REAL_LOW, но получают глаза, как у молей. Флэшбенг тайм.
> 
> Disclaimer: Не уверен, что стоит добавлять ночное зрение раундстартом

я тоже не уверен в этой трейте, пока бы не добавлял, и логичнее если уж добавлять то для таяр

2024-05-23 13:17 UTC, larentoun commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +
Можешь муню спросить, имхо, лисо-люди должны иметь более менее лисо-диету

2024-05-26 17:32 UTC, larentoun requested changes
Пустые файлы зачем нам?

Поверхностно пробежался глазами

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/_species.dm
> +	author = "nlaysi"
Очень странное "разделение". Раздели "общие" пункты и вульпские, либо поправь тут

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/dna.dm
> +	GLOB.total_uf_len_by_block += populate_total_uf_len_by_block_modular(GLOB.total_uf_len_by_block[DNA_FEATURE_BLOCKS])
Почему это в world, а не в том же пост-инит модпака?

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +		/obj/item/organ/external/tail/vulpkanin = "Default",
Default? Так называется хвост?

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +	bodytemp_cold_damage_limit = BODYTEMP_COLD_DAMAGE_LIMIT - 15
Шерсть лучше должна защищать от холода и горячести. Сделай так, чтобы вульпам вообще можно было спокойно ходить на айсмуне, прикола ради.

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +/datum/species/vulpkanin/create_pref_unique_perks()
create_pref_temperature_perks() где?

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/human/sprite_accessories/hair.dm
> +	//glasses_over = 1
Зачем коммент? Убирай везде их

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/language.dm
> +	"bin","ket","jarl","vulf","einech","cresthz","azunein","ghzth")
Можно и на кириллицу перевести

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/surgery/bodyparts/vulpkanin_bodyparts.dm
> +	wing_types = list(/obj/item/organ/external/wings/functional/dragon)
Мне, конечно, тоже симпатизируют такие крылья, но почему у мохнатых вульпканинов такие крылья, а не стандартные ангельские?

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/surgery/organs/external/vulpkanin_external.dm
> +	dna_block = 18
Вот тут и кусают тебя дефайны.
Нужно дефайны с модуля вытащить в кор, чтобы мы знали, когда добавляется новый дефайн на оффах.

2024-05-26 17:32 UTC, larentoun commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +	desc = "длинный и более чувствительный язык, может различить больше вкусов"
```suggestion
	desc = "Длинный и более чувствительный язык, может различить больше вкусов"
```

2024-05-26 17:32 UTC, larentoun commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
> +  name: 'Tail',
Всё на русский

2024-05-29 03:11 UTC, VaskaPepelov commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +	bodytemp_cold_damage_limit = BODYTEMP_COLD_DAMAGE_LIMIT - 15
Б - баланс, будет мета вульп теперь

2024-05-29 16:50 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +	bodytemp_cold_damage_limit = BODYTEMP_COLD_DAMAGE_LIMIT - 15
Вульпам много чего нельзя делать, такое как пить квадсек и есть донки

2024-05-30 13:48 UTC, larentoun requested changes

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/emote_panel/code/emote_verbs.dm
> +/mob/living/carbon/human/species/vulpkanin/proc/emote_growl()
Просто хуманские сделай

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +	. = ..()
Не нужно ..(), и нужна проверка на юзера

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +		return FALSE
Оно и так возвращает FALSE по-умолчанию, думаю, можно явно не обозначать это?

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +	message_mime = "делает вид что воет."
```suggestion
	message_mime = "делает вид, что воет."
```

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +	. = ..()
```suggestion
```

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +	if(is_species(user, /datum/species/vulpkanin))
Почему проверка на расу, а не на орган?

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +	. = ..()
```suggestion
```
Проверку на хумана/карбона, скорее всего нужна

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/_species.dm
> +	author = "nlaysi"
Я бы разделил следующим образом.

То, что относится ко всем новым добавляем расам оставлять в /code, а то, что относится только к вульпам, куда-нибудь в /code/vulpkanin?

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/dna.dm
> +	. = ..()
```suggestion
```

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/human/human.dm
> +	var/vulpcolors = list(
Почему оно находится именно здесь?

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +/datum/action/cooldown/vulpkanin/proc/colorize_string(name, sat_shift = 1, lum_shift = 1)
Это копипаста с рунчата?

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +	if(ishuman(target))
Нужен ду-афтер обязательно

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +	name = "\improper Vulpkanin"
Почему не на русском?

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +			SPECIES_PERK_DESC = "[plural_form] могут различать больше запахов.",
"... и запоминать их"

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +			SPECIES_PERK_DESC = "[plural_form] быстрее тратят полезные вещества и проголадываются",
```suggestion
			SPECIES_PERK_DESC = "[plural_form] быстрее тратят полезные вещества, потому чаще хотят есть.",
```

2024-05-30 13:48 UTC, larentoun commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +	desc = "Большие ушки позволяют легче слышать шепот"
```suggestion
	desc = "Большие ушки позволяют легче слышать шепот."
```

2024-05-30 13:48 UTC, larentoun commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
> +  name: 'Раскраска хвоста',
```suggestion
  name: 'Хвост - раскраска',
```

2024-05-30 13:48 UTC, larentoun commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
> +  name: 'Цвет хвоста',
```suggestion
  name: 'Хвост - цвет',
```

2024-05-30 13:48 UTC, larentoun commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
> +  name: 'Волосы на лице',
```suggestion
  name: 'Волосы на лице - цвет',
```

2024-06-02 11:30 UTC, larentoun commented
У вас конфликт

2024-06-02 11:58 UTC, larentoun commented
По поводу ушей: это и положительный, и отрицательный эффект. Либо продублируй, а лучше сделай нейтральным

2024-06-02 12:00 UTC, larentoun commented
В описании расы не указана пониженная зарплата

2024-06-02 12:00 UTC, larentoun commented
Нет варианта для digitigrade, а следует

2024-06-02 12:02 UTC, larentoun commented
Нет звуков крика и смеха

2024-06-02 12:07 UTC, larentoun commented
У вульпской абилки нет бэкграунда??

2024-06-02 12:25 UTC, larentoun requested changes

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +	desc = "Вы обнюхиваете предмет и определяете кто с ним взаимодействовал. Вы можете запомнить запах определённого человека обнюхав его."
```suggestion
	desc = "Вы обнюхиваете предмет и определяете, кто с ним взаимодействовал. Также, вы можете запомнить запах определённого человека, обнюхав его."
```

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +		if(do_after(owner, 1.5 SECONDS, target = target))
Маловато времени, чтобы на реакции успеть, когда печатаешь текст. Советую 2.5-3 секунды. Лучше 3.

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +				fingerprint_output[h]["Color"] = colorize_string(A.dna.unique_enzymes + A.dna.unique_identity)
Ты меня тут немного потерял. Зачем мы это делаем каждый раз при использовании абилки? Что эта функция вообще делает??

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +	if(fingerprint_output.len > 0)
используй length()

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +	if(blood_output.len > 0)
length()

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +	inherent_biotypes = MOB_ORGANIC|MOB_HUMANOID
Оно и так в /datum/species по-умолчанию такое, можешь убрать

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/human/sprite_accessories/hair.dm
> +/// VULPKANIN HAIR
Вульпы могут и хуманские прически использовать. Так и задумано?

2024-06-02 12:25 UTC, larentoun commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +	alcohol_tolerance = ALCOHOL_RATE * 1.5
В описании написано "на 150%", а тут на 50%. Может, увеличим до 2.5?

2024-06-02 12:30 UTC, larentoun commented
Вопрос в целом по поводу ДНК и features. Возможно ли это вынести в какой-то свой датум, чтобы мы не трогали апстримовский список?

А именно интересуют проки в dna.dm. Можем ли сделать свое dna2 только с нашими фичами? Чтобы в будущем было меньше проблем с дефайнами

2024-06-02 12:34 UTC, Gaxeer requested changes

2024-06-02 12:34 UTC, Gaxeer commented on modular_bandastation/species/code/human/species/species.dm
> +		return FALSE
Убери эту проверку, чтобы дать возомжность эту абилку выдавать кому угодно, если вдруг захочется.

2024-06-02 12:34 UTC, Gaxeer commented on modular_bandastation/species/code/human/species/species.dm
> +	background_icon_state = "frame"
Убери ненужное наследование `/datum/action/cooldown/vulpkanin`  и замени просто на `/datum/action/cooldown/sniff`

2024-06-02 12:34 UTC, Gaxeer commented on modular_bandastation/species/code/human/species/species.dm
> +	for(var/mob/living/carbon/human/A in GLOB.human_list)
```suggestion
	for(var/mob/living/carbon/human/A as anything in GLOB.human_list)
```

2024-06-02 12:34 UTC, Gaxeer commented on modular_bandastation/species/code/human/species/species.dm
> +				fingerprint_output[h]["Color"] = colorize_string(A.dna.unique_enzymes + A.dna.unique_identity)
```suggestion
		if(!A.dna)
			continue
			
		if(A.dna.unique_enzymes in blood)
			blood_output[A.dna.unique_enzymes] = list()
			blood_output[A.dna.unique_enzymes]["Gender"] = A.gender
			blood_output[A.dna.unique_enzymes]["Species"] = A.dna.species.name
			blood_output[A.dna.unique_enzymes]["Color"] = colorize_string(A.dna.unique_enzymes + A.dna.unique_identity)
		var/h = md5(A.dna.unique_identity)
		if(h in fingerprints)
			fingerprint_output[h] = list()
			fingerprint_output[h]["Gender"] = A.gender
			fingerprint_output[h]["Species"] = A.dna.species.name
			fingerprint_output[h]["Color"] = colorize_string(A.dna.unique_enzymes + A.dna.unique_identity)
```

2024-06-02 14:46 UTC, larentoun commented
Морды длинные - маски не натягиваются

2024-06-02 15:53 UTC, larentoun commented
Изменения хвоста не обновляют окраску
![image](https://github.com/ss220club/Bandastation/assets/31931237/51d1c54e-52ff-47a8-a703-d7de294fb7b9)

2024-06-07 06:31 UTC, PhantornRU commented
Касаемо "НЮХА". Нужны изменения:
- Если на лицо надета маска или сигарета - запрещать нюх.
- Сигареты перебивают запах, собсно поэтому если вульпа курит - у неё перебивается запах. Можно навешивать даже продолжительный дебаф под 2-5 минут для восстановления при прекращении курения.

Продвинутая реализация, если возможно:
- Квирк на "курильщиков". Если вульпа видит курильщиков - дебаф к муду, а также запрет на нюх, якобы "сигареты перебивают запахи".

2024-06-17 10:01 UTC, PhantornRU commented on modular_bandastation/species/code/human/species/species.dm
> +			return "#[num2hex(c, 2)][num2hex(m, 2)][num2hex(x, 2)]"
Очень страшная штука.

2024-06-17 10:01 UTC, PhantornRU requested changes
Ладно, нужно будет моменты доработать и можно будет вытаскивать из ТМа.

2024-06-30 11:27 UTC, Gaxeer commented on modular_bandastation/species/code/human/species/species.dm
> +/obj/item/clothing/mask/cigarette/handle_reagents(seconds_per_tick)
```suggestion
/obj/item/cigarette/handle_reagents(seconds_per_tick)
```

2024-07-19 21:15 UTC, Gaxeer commented on modular_bandastation/species/code/human/species/species.dm
> +			return "#[num2hex(c, 2)][num2hex(m, 2)][num2hex(x, 2)]"
Эту страшную штуку на оффах вынесли в отдельный глобальный прок. Ждем когда вмержат.

2024-07-25 11:46 UTC, larentoun commented
Эм, зачем нам инфюзиться в вульпу? Инфьзы используются не для изменения рас, откатывай

2024-07-25 11:48 UTC, larentoun commented
Более подробно опиши все особенности и способности в описании ПРа, и обнови информацию в нем

2024-07-25 19:59 UTC, Nlaysi commented
> Эм, зачем нам инфюзиться в вульпу? Инфьзы используются не для изменения рас, откатывай

Просто надо как то иметь возможность превратится в вульпу, в ходе раунда

2024-07-26 13:11 UTC, larentoun commented
> > Эм, зачем нам инфюзиться в вульпу? Инфьзы используются не для изменения рас, откатывай
> 
> Просто надо как то иметь возможность превратится в вульпу, в ходе раунда

Можешь просто заменить все части тела. Расы, как само понятие, скоро будут удалены.

2024-07-28 17:55 UTC, larentoun commented
> > Эм, зачем нам инфюзиться в вульпу? Инфьзы используются не для изменения рас, откатывай
> 
> Просто надо как то иметь возможность превратится в вульпу, в ходе раунда

Это можно сделать через ксенобио, как минимум

2024-09-01 12:59 UTC, dj-34 commented
боже выпили это урчание

2024-10-15 08:05 UTC, PhantornRU submitted a review, later dismissed

2024-10-15 08:05 UTC, PhantornRU commented on modular_bandastation/species/code/preferences/species_features/vulpkanin.dm
> +	icon_with_markings.Crop(15, 38, 15 + 31, 7)
Вот это бы вынести бы в отдельные переменные, но с другой стороны... А как. Хммм.

2024-10-15 08:05 UTC, PhantornRU commented on modular_bandastation/species/code/preferences/species_features/vulpkanin.dm
> +	icon_with_markings.Crop(15, 64, 15 + 31, 64 - 31)
Тоже самое. Если можно - то гуд. Если нет - то ок.

2024-10-15 08:05 UTC, PhantornRU commented on modular_bandastation/species/code/human/species/species.dm
> +				fingerprint_output[i]["Name"] = sniffed_species_ui[i]
```suggestion
			if(!sniffed_species_ui[i])
				continue
			fingerprint_output[i]["Name"] = sniffed_species_ui[i]
```

2024-10-15 08:05 UTC, PhantornRU commented on modular_bandastation/species/code/human/species/species.dm
> +				blood_output[i]["Name"] = sniffed_species_ue[i]
```suggestion
		for(var/i in blood)
			if(!sniffed_species_ue[i])
				continue
			blood_output[i]["Name"] = sniffed_species_ue[i]
```

2024-10-15 08:05 UTC, PhantornRU commented on modular_bandastation/species/code/human/species/species.dm
> +		if(do_after(owner, 2 SECONDS, target = target))
2 секунды вынеси в качестве отдельной переменной в снифе

2024-10-26 10:58 UTC, larentoun requested changes
Проблем не так уж и много, скоро мерж

2024-10-26 10:58 UTC, larentoun commented on config/bandastation/bandastation_config.txt
> +## Bandastation Races
```suggestion
## Bandastation Races
```

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +	message_param = "нюхает %t."
убери эти изменения

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +		return 'modular_bandastation/emote_panel/audio/male/sniff_male.ogg'
```suggestion
	if(user.gender == FEMALE)
		return 'modular_bandastation/emote_panel/audio/female/sniff_female.ogg'
	return 'modular_bandastation/emote_panel/audio/male/sniff_male.ogg'
```

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +		return TRUE && ..()
```suggestion
		return ..()
```

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +/datum/emote/living/carbon/human/vulpkanin/howl
Добавь тут везде `name` - отображается в Emote Panel

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/clothing/human_update_icons.dm
> +/mob/living/carbon/human/update_worn_mask(update_obscured = TRUE)
Добавь все оверрайды в кор-код с нужным комментом, типо // BANDASTATION EDIT START - Vulps. Примеры уже есть в коде.

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/clothing/mod.dm
> +/obj/item/mod/module/generate_worn_overlay(mutable_appearance/standing)
Тоже в кор код убери

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +	RegisterSignal(granted_to, "testsig", PROC_REF(smoke))
В сигналы

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +		owner.emote("sniff", message = target.name, intentional = TRUE)
```suggestion
		owner.emote("sniff", message = target.declent_ru(ACCUSATIVE), intentional = TRUE)
```

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +		owner.emote("sniff")
intentional где?

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/human/species/species.dm
> +	if(!fingerprints && !blood)
Точно ли должно быть условие И, а на ИЛИ?
```suggestion
	if(!length(fingerprints) && !length(blood))
```

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +/datum/species/vulpkanin/get_sneeze_sound(mob/living/carbon/human/human)
Добавь больше звуков, например для `sigh`

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +		var/datum/bodypart_overlay/simple/body_marking/markings = new markings_type()
По-моему, стоит создать в ините всех частей тел глобал, чтобы не создавать каждый раз датумы, а обращаться к уже созданным.

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/code/human/species_type/vulpkanin.dm
> +			var/datum/bodypart_overlay/simple/body_marking/overlay = new markings_type ()
И ты их, кстати, не удаляешь. Точно стоит не создавать, а обращаться уже к созданному списку.

2024-10-26 10:58 UTC, larentoun commented on modular_bandastation/species/_species.dme
> +#ifndef MODPACK_SPECIES
А это тут зачем?

2024-11-17 20:23 UTC, larentoun requested changes

2024-11-17 20:23 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +/datum/emote/living/sniffle
если это только вульпканский, убери к вульпам (видовой) модуль

2024-11-17 20:23 UTC, larentoun commented on modular_bandastation/emote_panel/code/emotes.dm
> +	message_mime = "бесшумно шмыгает носом."
ловушка копипастера

2024-11-27 18:26 UTC, larentoun requested changes
Ждём, пока и прошлые замечания по ревью завершишь

2024-11-27 18:26 UTC, larentoun commented on tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
> +
1. Почему это не внизу под комментом BANDASTATION EDIT
2. Почему бы не использовать тот же преф, что и feature_lizard_legs? В чём принципиальная разница?

2024-11-27 18:28 UTC, larentoun commented on config/bandastation/bandastation_config.txt
> +ROUNDSTART_RACES vulpkanin
Чтобы убрать конфликты, перемести
```suggestion
## Bandastation Races
ROUNDSTART_RACES vulpkanin

#MIN_THREAT_TO_ROUNDSTART_PERCENT 30
#MAX_THREAT_TO_ROUNDSTART_PERCENT 60
#MIN_THREAT_LEVEL 20
```

2024-12-03 03:31 UTC, dj-34 commented
ну че там, долго еще?

2024-12-24 02:33 UTC, dj-34 commented on modular_bandastation/species/_species.dm
> +	desc = "Добавление архитектуры для новых видов и конфигурирования существующих"
Оно понятно что модпак
```suggestion
	name = "Species"
	desc = "Добавление архитектуры для новых видов и конфигурирования существующих."
```

2024-12-24 02:33 UTC, dj-34 commented on modular_bandastation/species/_species.dm
> +	author = "nlaysi"
Зачем создавать подраздел модпака под расу? Как-то бессмысленно и лишь засоряет список.
```suggestion
```

2024-12-24 02:33 UTC, dj-34 commented on modular_bandastation/species/code/surgery/organs/internal/vulpkanin_internal.dm
> +	desc = "Длинный и более чувствительный язык, может различить больше вкусов"
Все name на английском, с маленькой буквы, если это объект и не имя собственное (пробегись по коду посмотри есть ли где-то еще), перевод делается через ru_names. В конце desc не забывать знак препинания.
```suggestion
	name = "long tongue"
	desc = "Длинный и более чувствительный язык, может различить больше вкусов."
```

2024-12-25 13:14 UTC, Gaxeer approved these changes
Лучше дочинить всем вместе, чем дрочить нляси вечно

2024-12-25 13:22 UTC, merged