Translation: Changeling
ss220club/Bandastation pull request #268
Opened 2024-05-17 17:52 UTC by Ingakem

## About The Pull Request
Перевод генокрада и его способностей

## Why It's Good For The Game
Da

## Changelog

![image](https://github.com/ss220club/Bandastation/assets/146962612/9ca9d2d0-476c-4ee9-b8e2-326bc16eef00)
![image](https://github.com/ss220club/Bandastation/assets/146962612/7a81d41f-93b0-463c-aa13-496107a7dca2)

2024-05-17 17:54 UTC, larentoun commented
360 строк...

Here we go again.

2024-05-17 17:58 UTC, dj-34 commented on code/modules/antagonists/changeling/changeling.dm
> +	roundend_category = "Генокрадами"
ты проверял за что оно отвечает и нужно ли это переводить?

2024-05-17 17:58 UTC, dj-34 commented on code/modules/antagonists/changeling/changeling.dm
> +	suicide_cry = "ЗА УЛЕЙ!!"
Taa, у генок есть улей? chenahui

2024-05-17 17:58 UTC, dj-34 commented on code/modules/antagonists/changeling/changeling.dm
> +		parts += span_greentext("Генокрад был успешен!")
Куда ебать провалился
```suggestion
		parts += span_greentext("Генокрад выполнил свои задания!")
```

2024-05-17 17:58 UTC, dj-34 commented on code/modules/antagonists/changeling/changeling.dm
> +		parts += span_redtext("Генокрад провалился.")
```suggestion
		parts += span_redtext("Генокрад потерпел неудачу.")
```

2024-05-17 18:00 UTC, Ingakem commented on code/modules/antagonists/changeling/changeling.dm
> +	roundend_category = "Генокрадами"
Да

2024-05-20 12:03 UTC, larentoun requested changes
Стандартизируй transform в "трансформировать".

Также, пытайся предметы держать в именительной форме, примеры я привожу в ревью, прошу обращать на это внимание.

Ну и заменяй различные p_theirs() на какие-нибудь нейтральные или множественные формы

2024-05-20 12:03 UTC, larentoun commented on code/modules/antagonists/changeling/powers/mutations.dm
> +			H.visible_message(span_warning("С жутким хрустом [H] превращает щит [H.p_their()] в руку!"), span_notice("Мы ассимилируем наш щит в наше тело"), "<span class='italics>Вы слышите, как рвется и разр
```suggestion
			H.visible_message(span_warning("С жутким хрустом [H] превращает свой щит в руку!"), span_notice("Мы ассимилируем наш щит обратно в тело"), "<span class='italics>Вы слышите, как рвется и разрывается органическая масса!</span>")
```

2024-05-20 12:03 UTC, larentoun commented on code/modules/antagonists/changeling/powers/mutations.dm
> +		loc.visible_message(span_warning("Плоть [loc.name]\'s чернеет, быстро превращаясь в твердую, хитиновую массу!"), span_warning("Мы закаляем свою плоть, создавая броню!"), span_hear("Вы слышите, как
```suggestion
		loc.visible_message(span_warning("Плоть [loc.name] чернеет, быстро превращаясь в твердую, хитиновую массу!"), span_warning("Мы закаляем свою плоть, создавая броню!"), span_hear("Вы слышите, как рвется и разрывается органическая масса!"))
```

2024-05-20 12:03 UTC, larentoun commented on code/modules/antagonists/changeling/powers/mutations.dm
> +	visible_message(span_boldwarning("Когда [user] запихивает [attacking_item] в [src], [src] начинает мутировать."))
```suggestion
	visible_message(span_boldwarning("Когда в [src.name] [user] запихивает [attacking_item.name], [src.name] начинает мутировать."))
```

2024-05-20 12:03 UTC, larentoun commented on code/modules/antagonists/changeling/powers/mutations.dm
> +			user.visible_message(span_warning("С отвратительным хрустом, [user] превращает [user.p_their()] [weapon_name_simple] в руку!"), span_notice("Мы ассимилируем [weapon_name_simple] обратно в наше тел
```suggestion
			user.visible_message(span_warning("С отвратительным хрустом, [user] превращает [weapon_name_simple] в руку!"), span_notice("Мы ассимилируем [weapon_name_simple] обратно в наше тело."), "<span class='italics>Вы слышите, как рвется и разрывается органическая масса!</span>")
```

2024-05-20 12:13 UTC, Ingakem commented on code/modules/antagonists/changeling/powers/absorb.dm
> +				owner.visible_message(span_warning("[owner] вытягивает пробоцис!"), span_notice("Мы вытягиваем пробоцис."))
> Reference
Нету, я просто не хотел писать хоботок или жало и решил что так прикольнеe :clueless:

2024-05-20 17:49 UTC, larentoun approved these changes
Надеюсь, ты там стандартизировал, что я просил

2024-05-20 17:49 UTC, larentoun commented on code/modules/antagonists/changeling/changeling.dm
> +		to_chat(owner.current, "Упс. Приобретение силы генокрада не удалась, пожалуйста, сообщите об этой ошибке кодеру!")
```suggestion
		to_chat(owner.current, "Упс. Приобретение силы генокрада не удалось, пожалуйста, сообщите об этой ошибке кодеру!")
```

2024-05-20 17:49 UTC, larentoun commented on code/modules/antagonists/changeling/changeling.dm
> +		to_chat(owner.current, span_warning("Мы слишком заняты реформированием себя, чтобы переадаптироваться прямо сейчас!"))
```suggestion
		to_chat(owner.current, span_warning("Мы слишком заняты переформированием себя, чтобы переадаптироваться прямо сейчас!"))
```
Будет ли это корректнее?

2024-05-20 18:06 UTC, Ingakem commented on code/modules/antagonists/changeling/changeling.dm
> +		to_chat(owner.current, span_warning("Мы слишком заняты реформированием себя, чтобы переадаптироваться прямо сейчас!"))
Да вроде так тоже понятно и нормально

2024-05-21 14:54 UTC, merged