Surgery merge translation fix
ss220club/Bandastation pull request #274
Opened 2024-05-19 18:55 UTC by AloeNeverDie

## About The Pull Request

Возврат перевода хирургии, который слетел после мержа

## Why It's Good For The Game

Да

## Changelog

Вернул перевод хирургии

:cl:
fix: перевод хирургии опять на месте
/:cl:

2024-05-19 19:02 UTC, Gaxeer approved these changes

2024-05-20 11:01 UTC, larentoun commented on code/modules/surgery/bone_mending.dm
> +			span_notice("[user] приступает к устранению перелома в [target.parse_zone_with_bodypart(user.zone_selected)] у[target] ."),
```suggestion
			span_notice("[user] приступает к устранению перелома в [target.parse_zone_with_bodypart(user.zone_selected)] у [target] ."),
```

2024-05-20 11:01 UTC, larentoun commented on code/modules/surgery/bone_mending.dm
> +		display_pain(target, "Ваш [target.parse_zone_with_bodypart(user.zone_selected)] испытывает сильную боль!")
```suggestion
		display_pain(target, "Ваша [target.parse_zone_with_bodypart(user.zone_selected)] испытывает сильную боль!")
```

2024-05-20 11:02 UTC, larentoun commented on code/modules/surgery/limb_augmentation.dm
> +			span_notice("[user] начинает аугментировать [target.parse_zone_with_bodypart(user.zone_selected)] у [target] with [aug]."),
```suggestion
			span_notice("[user] начинает аугментировать [target.parse_zone_with_bodypart(user.zone_selected)] у [target] с помощью [aug.name]."),
```

2024-05-20 11:02 UTC, larentoun commented on code/modules/surgery/limb_augmentation.dm
> +			span_notice("Вы начинаете аугментировать [target.parse_zone_with_bodypart(user.zone_selected)] у [target] ..."),
```suggestion
			span_notice("Вы начинаете аугментировать [target.parse_zone_with_bodypart(user.zone_selected)] у [target]..."),
```

2024-05-20 11:02 UTC, larentoun commented on code/modules/surgery/limb_augmentation.dm
> +			span_notice("[user] начинает аугментировать [target.parse_zone_with_bodypart(user.zone_selected)] у [target] ."),
```suggestion
			span_notice("[user] начинает аугментировать [target.parse_zone_with_bodypart(user.zone_selected)] у [target]."),
```

2024-05-20 11:02 UTC, larentoun commented on code/modules/surgery/limb_augmentation.dm
> +					span_warning("Вы не смогли заменить [target.parse_zone_with_bodypart(target_zone)] у [target] ! Тело отвергает [tool.name]!"),
```suggestion
					span_warning("Вы не смогли заменить [target.parse_zone_with_bodypart(target_zone)] у [target]! Тело отвергает [tool.name]!"),
```

2024-05-20 11:02 UTC, larentoun commented on code/modules/surgery/limb_augmentation.dm
> +					span_warning("[user] не смог заменить [target.parse_zone_with_bodypart(target_zone)] у [target] !"),
```suggestion
					span_warning("[user] не смог заменить [target.parse_zone_with_bodypart(target_zone)] у [target]!"),
```

2024-05-20 11:03 UTC, larentoun commented on code/modules/surgery/limb_augmentation.dm
> +					span_warning("[user] не смог заменить [target.parse_zone_with_bodypart(target_zone)] у [target] !"),
```suggestion
					span_warning("[user] не смог заменить [target.parse_zone_with_bodypart(target_zone)] у [target]!"),
```

2024-05-20 11:03 UTC, larentoun commented on code/modules/surgery/organ_manipulation.dm
> +			display_pain(target, "Ваш [target.parse_zone_with_bodypart(target_zone)] болит, пока [tool.name] приживается к телу!")
```suggestion
			display_pain(target, "Ваша [target.parse_zone_with_bodypart(target_zone)] болит, пока [tool.name] приживается к телу!")
```

2024-05-20 11:04 UTC, larentoun commented on code/modules/surgery/organ_manipulation.dm
> +			log_combat(user, target, "хирургически удалил [target_organ.name] из", addition="COMBAT MODE: [uppertext(user.combat_mode)]")
не переводи логи

2024-05-20 11:04 UTC, larentoun commented on code/modules/surgery/organic_steps.dm
> +	display_pain(target, "Ваш [target.parse_zone_with_bodypart(target_zone)] прижигается!")
```suggestion
	display_pain(target, "Ваша [target.parse_zone_with_bodypart(target_zone)] прижигается!")
```

2024-05-21 11:06 UTC, AloeNeverDie commented on code/modules/surgery/organ_manipulation.dm
> +			log_combat(user, target, "хирургически удалил [target_organ.name] из", addition="COMBAT MODE: [uppertext(user.combat_mode)]")
Вернул оригинал

2024-05-21 13:23 UTC, larentoun commented on code/__HELPERS/mobs.dm
> +			return "><i>грудь</i>"
```suggestion
			return "<i>грудь</i>"
```
Опечатка?

2024-05-21 13:24 UTC, larentoun commented on code/modules/surgery/amputation.dm
> +	display_pain(target, "Вы больше не чувствуете свою отрезанную конечность - [target.parse_zone_with_bodypart(target_zone)]!")
```suggestion
	display_pain(target, "Вы больше не чувствуете свою отрезанную [target.parse_zone_with_bodypart(target_zone)]!")
```
Думаю, можно вернуться сюда

2024-05-21 13:26 UTC, larentoun requested changes

2024-05-21 13:26 UTC, larentoun commented on code/modules/surgery/bone_mending.dm
> +			span_notice("Вы приступаете к устранению перелома в [target.parse_zone_with_bodypart(user.zone_selected)] у [target] ..."),
```suggestion
			span_notice("Вы приступаете к устранению перелома в [target.parse_zone_with_bodypart(user.zone_selected)] у [target]..."),
```

2024-05-21 13:26 UTC, larentoun commented on code/modules/surgery/organic_steps.dm
> +		span_notice("[user] вскрывает [target.parse_zone_with_bodypart(target_zone)] у [target] !"),
```suggestion
		span_notice("[user] вскрывает [target.parse_zone_with_bodypart(target_zone)] у [target]!"),
```

2024-05-21 13:26 UTC, larentoun commented on code/modules/surgery/organic_steps.dm
> +		span_notice("[user] вскрывает [target.parse_zone_with_bodypart(target_zone)] у [target] !"),
```suggestion
		span_notice("[user] вскрывает [target.parse_zone_with_bodypart(target_zone)] у [target]!"),
```

2024-05-21 13:46 UTC, larentoun approved these changes
lgtm

2024-05-21 14:54 UTC, merged