Перевод кухонной машинерии
ss220club/Bandastation pull request #292
Opened 2024-06-05 04:58 UTC by Kar4es

## About The Pull Request
периважу куханую машинерию

:cl:
fix: Кухня на правильном русском языке
/:cl:

2024-06-17 06:16 UTC, Kar4es commented
не забыть бы холодосик полностью перевести

2024-06-17 08:31 UTC, Kar4es commented
@larentoun ревью бы...

2024-06-18 09:56 UTC, larentoun commented
> @larentoun ревью бы...

Я боюсь ревьювить после твоей мафии.

2024-06-18 09:57 UTC, larentoun commented
Исправишь перевод мафии - я сделаю ревью здесь

2024-06-18 11:17 UTC, Kar4es commented
> Исправишь перевод мафии - я сделаю ревью здесь

мафия вмержена уже, я её вообще дропнуть хотел

2024-06-18 11:17 UTC, Kar4es commented
> > Исправишь перевод мафии - я сделаю ревью здесь
> 
> мафия вмержена уже, я её вообще дропнуть хотел

гахер по итогу попросил твои правки вбахать и мержанул

2024-06-18 17:56 UTC, larentoun commented
> > > Исправишь перевод мафии - я сделаю ревью здесь
> > 
> > 
> > мафия вмержена уже, я её вообще дропнуть хотел
> 
> гахер по итогу попросил твои правки вбахать и мержанул

Всё ещё, ты не выполнил мою просьбу пройтись по всем абилкам и исправить. Мне за тебя код писать?

2024-06-18 17:57 UTC, larentoun commented
> > Исправишь перевод мафии - я сделаю ревью здесь
> 
> мафия вмержена уже, я её вообще дропнуть хотел

Ревертать смысла нет, но перевод просто ужасен. "Вы готовитесь Разговаривайте с духами, чтобы узнать бла-бла"

2024-06-18 18:06 UTC, awkwardsocialist reviewed
Я посмотрел первые два файла, **и мне не понравилось**, как твой личный ревьювер говорю тебе: **плохо**. Если потом будет время, посмотрю оставшиеся файлы, чтобы не висеть мертвым в  pending пока оставлю ревью так

2024-06-19 07:20 UTC, Kar4es commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +			balloon_alert(user, "чашка заполнена!")
как "Чашек достаточно" пойдет? А то немного хз как это правильно записать

2024-07-04 10:11 UTC, larentoun requested changes
Пока тут довольно глобальные проблемы с артиклями и падежами. Сначала необходимо решить их, так как я уверен, что это не было соблюдено. В последнем комменте попытался подробнее указать на проблемы, и как их можно решить.

2024-07-04 10:11 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			blind_message = span_notice("Вы чувствуете какой-то приятный запах..."),
```suggestion
			blind_message = span_notice("Вы чувствуете приятный запах..."),
```
Почему два разных перевода на одно и то же сообщение %)

2024-07-04 10:11 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("[parent] может быть [span_bold("запечен")] в несколько [initial(bake_result.name)].")
Смотри. Проблема всё та же.

"Булочка может быть запечен". Неправильно стоит род. Необходимо пытаться переформулировать предложение, чтобы не терялся смысл, но наши предметы теперь стояли в именительном падеже. Если это невозможно, то попробуй хотя бы ставить их в италик, показывая более в игровом формате, что с падежами мы не выиграли. "Можно запечь _булочка_" против "Можно запечь булочка". Возможно, вкусовщина.

Вторая проблема. У тебя название предмета стоит в начале предложения. Оно не будет автоматически начинаться с заглавной буквы.

Третья проблема. Тут используется ссылка на датум `parent`, а не на атом. Было бы неплохо каким-то образом решить эту проблему, либо используя рефакторы, либо посмотреть, правда ли `source == parent`? Раскрой эту тему, ведь тогда у нас получится не "Булочка может быть", и не "булочка может быть", а целая "The булочка может быть".

2024-07-04 10:15 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("[parent] может быть [span_bold("запечен")] в несколько [initial(bake_result.name)].")
Для первой проблемы, можно было вообще убрать указание на `parent`? Нужно внимательно посмотреть в игре, нельзя ли просто заменить это всё на "Выпекается в [initial(bake_result.name)]" или тому подобное?

2024-07-04 10:15 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("[parent] может быть [span_bold("запечен")] в несколько [initial(bake_result.name)].")
Мы не должны переводить в лоб, потому что Английский язык гораздо скуднее, чем Русский язык.

2024-07-04 10:38 UTC, Kar4es commented on code/datums/components/bakeable.dm
> +			blind_message = span_notice("Вы чувствуете какой-то приятный запах..."),
потому что для слепого вариант... Можно и убрать

2024-07-11 06:24 UTC, msw7007 commented on code/datums/components/bakeable.dm
> +			blind_message = span_notice("Вы чувствуете какой-то приятный запах..."),
Оставим, просто его переиначим

2024-07-12 11:38 UTC, larentoun requested changes
Если что-то стоит в начале предложения, стоит к нему применять capitalize(), как в примерах выше

2024-07-12 11:38 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			span_notice("Вы чувствует как [used_oven.name] источает приятный запах."),
```suggestion
			span_notice("Вы чувствуете, как [used_oven.name] источает приятный запах."),
```

2024-07-12 11:38 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			span_warning("Вы чувствует как [used_oven.name] испускает горелое зловоние."),
```suggestion
			span_warning("Вы чувствуете, как [used_oven.name] испускает горелое зловоние."),
```

2024-07-12 11:38 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("Это [parent.name]. [initial(bake_result.name)] могут [span_bold("готовиться")] из нее.")
Я не уверен, что это компилируется. `parent` является просто датумом, у него почти нет переменных никаких.

Так как это сигнал, нам повезло. Скорее всего, `source` и является нашим `parent`.
```suggestion
				examine_list += span_notice("Это [source.name], и [initial(bake_result.name)] могут [span_bold("готовиться")] из нее.")
```

2024-07-12 11:38 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("Это [parent.name]. [span_bold("Готовится")] в [initial(bake_result.name)].")
```suggestion
				examine_list += span_notice("Это [source.name]. [span_bold("Готовится")] в [initial(bake_result.name)].")
```

2024-07-12 11:38 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			examine_list += span_notice("Наверное, [parent.name] нужно выпекать немного дольше!")
```suggestion
			examine_list += span_notice("Наверное, [source.name] нужно выпекать немного дольше!")
```

2024-07-12 11:38 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			examine_list += span_notice("Кажется, что [parent.name] почти готов!")
```suggestion
			examine_list += span_notice("Кажется, что [source.name] почти готов!")
```

2024-07-12 11:38 UTC, larentoun commented on code/datums/components/bakeable.dm
> +		examine_list += span_danger("[parent.name] не стоит засовывать в духовку.")
```suggestion
		examine_list += span_danger("Кажется, что [source.name] не стоит засовывать в духовку.")
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		. += "Вы сможете разглядеть [frying] в масле."
```suggestion
		. += "Вы сможете разглядеть [frying.name] в масле."
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +			to_chat(user, span_warning("Не в чем растворять [weapon]!"))
```suggestion
			to_chat(user, span_warning("Не в чем растворять [weapon.name]!"))
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		to_chat(user, span_userdanger("Ваши кулинарные способности не дотягивают до легендарной техники Doublefry."))
```suggestion
		to_chat(user, span_userdanger("Ваши кулинарные способности не дотягивают до легендарной техники Двойножарки."))
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		audible_message(span_notice("[src.name] звенит!"))
```suggestion
		audible_message(span_notice("[capitalize(src.name)] звенит!"))
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		visible_message(span_warning("[src.name] источает едкий запах!"), ignored_mobs = asomnia_hadders)
```suggestion
		visible_message(span_warning("[capitalize(src.name)] источает едкий запах!"), ignored_mobs = asomnia_hadders)
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +	to_chat(user, span_notice("Вы кладете [frying_item] в [src]."))
```suggestion
	to_chat(user, span_notice("Вы кладете [frying_item.name] в [src.name]."))
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +	visible_message(span_userdanger("[src.name] взрывается в результате энтропийной реакции!"))
```suggestion
	visible_message(span_userdanger("[capitalize(src.name)] взрывается в результате энтропийной реакции!"))
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		visible_message(span_userdanger("[src.name] начинает пылать... О нет..."))
```suggestion
		visible_message(span_userdanger("[capitalize(src.name)] начинает пылать... О нет..."))
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +			dunking_target.visible_message(span_userdanger("[dunking_target.name] взрывается от энтропийной разницы! Блять!"))
```suggestion
			dunking_target.visible_message(span_userdanger("[capitalize(dunking_target.name)] взрывается от энтропийной разницы! Блять!"))
```

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +			dunking_target.investigate_log("has been gibbed by entropic difference (being dunked into [src.name]).", INVESTIGATE_DEATHS)
```suggestion
			dunking_target.investigate_log("has been gibbed by entropic difference (being dunked into [src]).", INVESTIGATE_DEATHS)
```
не трогаем логи

2024-07-12 11:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +			log_combat(user, dunking_target, "blew up", null, "by dunking them into [src.name]")
```suggestion
			log_combat(user, dunking_target, "blew up", null, "by dunking them into [src]")
```

2024-07-16 05:06 UTC, msw7007 commented
Проверить бы

2024-07-19 11:51 UTC, larentoun requested changes
Пока что те же проблемы - нет капитализации для `.name` в начале предложения

2024-07-19 11:51 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			span_notice("Вы чувствуете как [used_oven.name] источает приятный запах."),
```suggestion
			span_notice("Вы чувствуете, как [used_oven.name] источает приятный запах."),
```

2024-07-19 11:51 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			span_warning("Вы чувствуете как [used_oven.name] испускает горелое зловоние."),
```suggestion
			span_warning("Вы чувствуете, как [used_oven.name] испускает горелое зловоние."),
```

2024-07-19 11:51 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("Это [sourceobj.name]. [initial(bake_result.name)] могут [span_bold("готовиться")] из нее.")
`atom/source` и является уже `parent`. Посмотри сигнал COMSIG_ATOM_EXAMINE.

2024-07-19 11:51 UTC, larentoun commented on code/modules/food_and_drinks/machinery/food_cart.dm
> +	visible_message(span_notice("[src.name] втягивает все свои распакованные части."))
```suggestion
	visible_message(span_notice("[capitalize(src.name)] втягивает все свои распакованные части."))
```

2024-10-04 15:53 UTC, closed without merging