Kvas
ss220club/Bandastation pull request #301
Opened 2024-06-14 15:39 UTC by HardexZ

Квас портированный с массметы. Щитспаун онли.

:cl:
add: Квас
/:cl:

2024-06-15 08:28 UTC, PhantornRU requested changes

2024-06-15 08:28 UTC, PhantornRU commented on modular_bandastation/drinks/_drinks.dm
> +	author = "Massmeta(code+sprite), HardexZ(модуль)"
```suggestion
	author = "HardexZ"
```

2024-06-15 08:28 UTC, PhantornRU commented on modular_bandastation/drinks/code/drinks.dm
> +	name = "Стакан кваса"
```suggestion
	name = "стакан кваса"
```

2024-06-15 08:28 UTC, PhantornRU commented on modular_bandastation/drinks/code/drinks.dm
> +	desc = "Стакан с квасом."
В описании можно было б и отсылку бахнуть или описание подлинее. Иначе оно бесполезно. Ибо повторы - нехорошо. Поменяй это.

2024-06-15 08:28 UTC, PhantornRU commented on modular_bandastation/drinks/code/drinks.dm
> +	desc = "Желтая бочка с напитком богов."
Тоже можно побольше описания добавить

2024-06-30 10:26 UTC, Gaxeer approved these changes

2024-06-30 10:27 UTC, merged