Loadout restrictions (removal and donation tier)
ss220club/Bandastation pull request #403
Opened 2024-07-17 10:00 UTC by larentoun

## About The Pull Request

Добавляет поддержку удаления предметов из лодаута без изменения кор кода.
Добавляет поддержку тир-уровней для предметов.

## Changelog

:cl:
add: PayToWin RP in loadouts
/:cl:

2024-07-19 13:48 UTC, Gaxeer commented
Что мы еще планирум сувать в этот `player220` ? Дискорд?

2024-07-19 14:44 UTC, larentoun commented
> Что мы еще планирум сувать в этот `player220` ? Дискорд? Если для дискорда у нас отдельная таблица будет, то я бы переименовал эту таблицу в что-то более подходящее. Например. `player_donation`

Без понятия, можно и переименовать, если надо?

2024-07-22 17:23 UTC, Gaxeer requested changes

2024-07-22 17:23 UTC, Gaxeer commented on SQL/bandastation/bandastation_update.sql
> +/*!40101 SET character_set_client = utf8 */;
```suggestion
```

2024-07-22 17:23 UTC, Gaxeer commented on SQL/bandastation/bandastation_update.sql
> +/*!40101 SET character_set_client = @saved_cs_client */;
```suggestion
```

2024-07-22 19:32 UTC, Gaxeer approved these changes

2024-07-23 03:58 UTC, dj-34 reviewed
А почему донатор левел в лодауте? У нас же тиры используются не только для лодаута, но и для чата, голоса

2024-07-23 08:20 UTC, larentoun commented
> А почему донатор левел в лодауте, а не отдельным модулем? У нас же тиры используются не только для лодаута, но и для чата, голоса

Пока что нет поддержки для ТТС тиров. Да и пока не знаю более подходящего места, кроме как плодить ещё один модуль только с одним файлом

2024-07-23 10:58 UTC, Gaxeer commented on modular_bandastation/loadout/code/client.dm
> +#define TIER1 220
```suggestion
#define DONATION_TIER1 220
```
Более описательным должно быть 🤓

2024-07-23 11:05 UTC, Gaxeer requested changes

2024-07-23 11:05 UTC, Gaxeer commented on modular_bandastation/loadout/code/client.dm
> +/client/proc/get_donator_level_db()
```suggestion
/client/proc/get_donator_level_from_db()
```

2024-07-23 11:05 UTC, Gaxeer commented on modular_bandastation/loadout/code/client.dm
> +	donator_level = max(donator_level, get_donator_level_db(), get_donator_level_admin())
```suggestion
	donator_level = max(donator_level, get_donator_level_from_db(), get_donator_level_admin())
```

2024-07-23 11:05 UTC, Gaxeer commented on modular_bandastation/loadout/code/client.dm
> +/client/proc/update_donator_level()
```suggestion
/client/proc/get_donator_level()
```

2024-07-23 11:05 UTC, Gaxeer commented on modular_bandastation/loadout/code/client.dm
> +	/// Call `proc/update_donator_level()` instead to get a value when possible.
```suggestion
	/// Call `proc/get_donator_level()` instead to get a value when possible.
```

2024-07-24 11:05 UTC, Furrior commented on modular_bandastation/loadout/code/categories/accessories.dm
> +/datum/loadout_item/accessory/pride/is_available()
Буквально 1984

2024-07-24 11:17 UTC, Gaxeer approved these changes

2024-07-24 11:21 UTC, merged