DNA Translate
ss220club/Bandastation pull request #421
Opened 2024-07-18 22:14 UTC by azym76

## About The Pull Request

Переведены новые гены и сообщения их активации. 
## Why It's Good For The Game

Всё на привычном языке
## Changelog

:cl:
add: Перевод генов
fix: Убрано дублирование гигантизма

/:cl:

2024-07-18 22:15 UTC, dj-34 reviewed
В переводе ни в коем случае не трогаем код (вырезать/добавлять).

2024-07-18 22:18 UTC, azym76 commented
> В переводе ни в коем случае не трогаем код (вырезать/добавлять).

Сделал как сказал Гахер, ибо косяк при мерже оффов был как понял.

2024-07-19 11:46 UTC, larentoun commented on code/datums/mutations/body.dm
> -	owner.visible_message(span_danger("[owner] suddenly shrinks!"), span_notice("Everything around you seems to grow.."))
Неправильно. Перевод нужно было запихать сюда, а на 472-й строке убрать

2024-07-19 14:48 UTC, larentoun commented on code/datums/mutations/body.dm
> +	name = "Gigantism"//negative version of dwarfism
```suggestion
	name = "Gigantism" //negative version of dwarfism
```

2024-07-20 09:12 UTC, larentoun requested changes

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/active.dm
> +	text_gain_indication = span_notice("Ты чувствуешь себя наканенным!")
наканенным?

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/adaptation.dm
> +	desc = "Странная мутация, которая адаптирует иммунную систему организма к высоокой и низкой температуре. Не защищает от высокого и низкого давления."
```suggestion
	desc = "Странная мутация, которая даёт невосприимчивость к урону от высокой и низкой температур. Не защищает от высокого и низкого давления."
```

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/adaptation.dm
> +	text_gain_indication = span_notice("Твоё тело ощущает, комфортную комнатную температуру.")
```suggestion
	text_gain_indication = span_notice("Твоё тело ощущает комфорто-комнатную температуру.")
```

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/body.dm
> +	owner.visible_message(span_danger("[owner] неожиданно становится выше!"), span_notice("У тебя появляется странное желание бороться с маленькими людьми с рогатками. Или стоит сыграть в баскентбол?"))
```suggestion
	owner.visible_message(span_danger("[owner] неожиданно становится выше!"), span_notice("У тебя появляется странное желание бороться с маленькими людьми с рогатками. Или стоит сыграть в баскетбол?"))
```

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/body.dm
> +
```suggestion

```

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/hot.dm
> +	desc = "Притягивает позитивную энергию  из окружения, чтобы повысить температуру вокруг субъекта."
```suggestion
	desc = "Притягивает положительную энергию окружения для повышения температуры вокруг субъекта."
```

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/reach.dm
> +	text_gain_indication = span_warning("Твои руки становятся, как у моряка Попая!")
Так как раз-таки наоборот, руки слабее становятся

2024-07-20 09:12 UTC, larentoun commented on code/datums/mutations/speech.dm
> +	desc = "чел, что такое ЖЕЛАНИЕ, твои слова чувак..........."
```suggestion
	desc = "чел что ЖЕЛАЮТ твои слова чувак..........."
```

2024-07-20 09:49 UTC, azym76 commented on code/datums/mutations/active.dm
> +	text_gain_indication = span_notice("Ты чувствуешь себя наканенным!")
Опечатался, на накаченным поменял.

2024-07-20 10:01 UTC, azym76 commented on code/datums/mutations/reach.dm
> +	text_gain_indication = span_warning("Твои руки становятся, как у моряка Попая!")
Тут нужно подумать тогда, ибо в оригинале отсылка на Армстронга. Вижу два варианта для перевода попытаться сохранить оригинал или найти подходящего человека для локализации.

2024-07-20 11:40 UTC, larentoun commented on code/datums/mutations/reach.dm
> +	text_gain_indication = span_warning("Твои руки становятся, как у моряка Попая!")
Можно и своё придумать, "Твои руки теперь длинные спагетти", там

2024-07-20 13:15 UTC, larentoun requested changes

2024-07-20 13:15 UTC, larentoun commented on code/datums/mutations/hulk.dm
> +	desc = "Данная мутация вызвана смешиванием генов халка. Она сильно влияет на речевые центры мозга обладателя мутицаии."
```suggestion
	desc = "Данная мутация вызвана смешиванием генов халка. Она сильно влияет на речевые центры мозга обладателя мутации."
```

2024-07-20 13:48 UTC, larentoun approved these changes
Вроде норм?

2024-07-22 17:14 UTC, merged