Перевод осмотра персонажа
ss220club/Bandastation pull request #424
Opened 2024-07-19 13:17 UTC by Chorden523

## About The Pull Request
Переводит осмотр персонажа и всё что с ним связано. fixes#416
По поводу перевода дефайнов для <code>human грудь</code> и <code>alien грудь</code> я пока не решился как именно следует это делать.

2024-07-19 13:27 UTC, Gaxeer requested changes

2024-07-19 13:27 UTC, Gaxeer commented on code/modules/mob/living/carbon/human/human_defense.dm
> +				combined_msg += span_danger("Ваши мысли затуманены и находятся где-то в далеке.")
```suggestion
				combined_msg += span_danger("Ваши мысли затуманены и находятся где-то далеко.")
```

2024-07-19 13:27 UTC, Gaxeer commented on code/modules/mob/living/carbon/human/human_defense.dm
> +				combined_msg += span_danger("Вы чувствуете головокружение.")
```suggestion
				combined_msg += span_danger("У вас кружится голова.")
```

2024-07-19 13:27 UTC, Gaxeer commented on code/modules/mob/living/carbon/human/human_defense.dm
> +				combined_msg += span_danger("Вы чувствуете тошноту.")
```suggestion
				combined_msg += span_danger("Вас тошнит.")
```

2024-07-20 09:43 UTC, larentoun commented
Скриншоты

2024-07-20 09:45 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +					span_notice("[user] вставляет [src] в свой пустой сокет, и [src] встаёт на место!"))
а тут `.name` забыли для `src`?

2024-07-20 13:13 UTC, larentoun requested changes
Обновишь скриншоты?

2024-07-20 13:13 UTC, larentoun commented on code/modules/mob/living/carbon/human/human_defense.dm
> +		var/bleed_text = "<span class='danger'>Вы истекаете кровью из своей"
```suggestion
		var/bleed_text = "<span class='danger'>Вы истекаете кровью из: "
```

2024-07-20 13:13 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +				check_list += "\t [span_danger("Ваша [name] страдает от [wound.a_or_from] [LOWER_TEXT(wound.name)].")]"
```suggestion
				check_list += "\t [span_danger("Ваша [name] страдает от: [LOWER_TEXT(wound.name)].")]"
```
Сюда нужно будет вернуться в будущем, когда будет переводить вунды. Замени снизу так же

2024-07-20 13:13 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +		var/stuck_word = embedded_thing.is_embed_harmless() ? "проникает" : "впился"
Разве не `прилип`? И скриншот приложи к тому, как это выглядит

2024-07-20 13:13 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			to_chat(user, span_warning("Внутри [src] ничего не осталось!"))
```suggestion
			to_chat(user, span_warning("Внутри [src.name] ничего не осталось!"))
```

2024-07-20 13:13 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +		user.visible_message(span_warning("[user] начинает вскрывать [src]."),\
```suggestion
		user.visible_message(span_warning("[user] начинает вскрывать: [src.name]."),\
```

2024-07-20 13:13 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			span_notice("Вы начинаете вскрывать [src]..."))
```suggestion
			span_notice("Вы начинаете вскрывать: [src.name]..."))
```

2024-07-20 13:13 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			is_disabled += ", также"
```suggestion
			is_disabled += " и"
```

2024-07-20 13:13 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +			is_disabled += ", но зато"
```suggestion
			is_disabled += ", но в целом"
```

2024-07-20 13:58 UTC, Chorden523 commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +		var/stuck_word = embedded_thing.is_embed_harmless() ? "проникает" : "впился"
<code>впился</code> используется когда что-то наносящее урон, а <code>проникает</code> для нелетального.

2024-07-20 18:55 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +		check_list += "\t <a href='?src=[REF(examiner)];embedded_object=[REF(embedded_thing)];embedded_limb=[REF(src)]' class='warning'>[embedded_thing] [stuck_word] в вашу [name]!</a>"
```suggestion
		check_list += "\t <a href='?src=[REF(examiner)];embedded_object=[REF(embedded_thing)];embedded_limb=[REF(src)]' class='warning'>[capitalize(embedded_thing.name)] [stuck_word] в вашу [name]!</a>"
```

2024-07-20 18:56 UTC, larentoun commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +		var/stuck_word = embedded_thing.is_embed_harmless() ? "проникает" : "впился"
Из хармлесс имеется:
- Игрушка с "прилепи хвост корги"
- Скотч
- Игрушечные метательные звезды

И прочее, что именно прилипает. Надо заменить.

2024-07-20 18:59 UTC, Chorden523 commented on code/modules/surgery/bodyparts/_bodyparts.dm
> +		var/stuck_word = embedded_thing.is_embed_harmless() ? "проникает" : "впился"
Заменил и добавил проверку для предлога

2024-07-20 22:17 UTC, larentoun approved these changes

2024-07-20 22:17 UTC, merged