Перевод рандомных файлов с фразами
ss220club/Bandastation pull request #437
Opened 2024-07-20 18:34 UTC by AyIong

## About The Pull Request
Перевод рандомно выбранных json файлов со всякими фразами

TODO:

- [ ] steve
- [ ] splashes
- [ ] redpill
- [ ] ninja
- [ ] mother
- [ ] luchador_replacement
- [ ] memories?

## Why It's Good For The Game
Перевод, локализация, хуё-моё

2024-07-20 23:26 UTC, Gaxeer commented on strings/splashes.json
> +		"Теперь на 33% больше грейтада!",
```suggestion
		"Теперь на 33% больше грейтайда!",
```

2024-07-21 08:56 UTC, dj-34 requested changes

2024-07-21 08:56 UTC, dj-34 commented on strings/splashes.json
> +		"Центр предателей!",
Это-ж отсылка на Южный Централ, не?
```suggestion
		"Трейторский Централ!",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Почему везде пожарные сигнализации, но нет спринклеров?",
Речь идет про разбрызгиватели воды
```suggestion
		"Почему везде пожарные сигнализации, но нет системы пожаротушения?",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Всеми управляют ниточки за светящимся экраном.",
```suggestion
		"Всеми управляют с помощью ниточек за светящимся экраном.",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Как спасательная капсула может взять только двух человек обычно, но бесконечное количество людей, если они лежат?",
```suggestion
		"Как спасательная капсула, рассчитанная обычно на двух человек, может вместить бесконечное количество, если они все лягут?",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Как лотки в морге знают, есть ли душа ещё в теле?",
```suggestion
		"Как хранилища тел в морге знают, есть ли ещё душа в теле, или нет?",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Если магия реальна, почему мы её не исследуем?",
```suggestion
		"Если магия реальна, то почему мы её не исследуем?",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Если датчики так важны, почему они не включаются сразу в последнем режиме?",
```suggestion
		"Если датчики так важны, то почему они не включаются сразу в последний режим?",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Если бы два шахтёра были в Лаваленде и один из них убил другого киркой, разве это не было бы пиздецом?",
```suggestion
		"Если бы два шахтёра были на Лаваленде и один из них убил другого киркой, то разве это не было бы пиздецом?",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Если мы можем стирать одежду в раковине, зачем нам стиральные машины?",
```suggestion
		"Если мы можем стирать одежду в раковине, то зачем нам стиральные машины?",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/redpill.json
> +		"Разделение абсолютно.",
```suggestion
		"Сегрегация неминуема.",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/ninja.json
> +		"НЕТ БОЛИ, НЕТ ВЫГОДЫ. ХАХАХАХА!",
```suggestion
		"ТО ЧТО НАС НЕ УБИВАЕТ, ДЕЛАЕТ НАС СИЛЬНЕЕ. ХАХАХАХА!",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/ninja.json
> +		"МЕСТЬ ЗОВЁТ!",
```suggestion
		"ЖАЖДА МЕСТИ!",
```

2024-07-21 08:56 UTC, dj-34 commented on strings/mother.json
> +		"НАВЕЩАЕШЬ"
увы нет способов перевода лучше в данный момент, поэтому так
```suggestion
		"НЕ ХОДИШЬ К"
```

2024-07-21 11:19 UTC, AyIong commented on strings/splashes.json
> +		"Центр предателей!",
Сомнительно... но... оукей

2024-07-21 11:23 UTC, AyIong commented on strings/ninja.json
> +		"МЕСТЬ ЗОВЁТ!",
Месть зовёт как-то получше, имхо

2024-07-21 12:51 UTC, dj-34 approved these changes

2024-07-21 14:58 UTC, merged