New Robo clothing and wardrobe sprites
ss220club/Bandastation pull request #456
Opened 2024-07-24 15:15 UTC by AloeNeverDie

## Что этот PR делает

Добавляет новые шмотки для робототеха, новые шмотки в вендомат робо, а также заменяет стандартный костюм робототеха на новый вариант.

Автор спрайтов - fridhelm1

## Почему это хорошо для игры

Новые шмотки стильнее старых

## Изображение изменений

![image](https://github.com/user-attachments/assets/811bee48-7d6d-4873-814f-853202af9c59)
![image](https://github.com/user-attachments/assets/29d616ee-64f8-4b53-9493-969e1f985f7d)
![image](https://github.com/user-attachments/assets/c9e028e7-7651-4e44-b489-f54b3c1ea4d0)

## Тестирование

Провел все тесты на локалке, все работает.

## Changelog
:cl:
add: Добавлены новые шмотки для роботеха
tweek: Заменена форма рауднстарт на новую
/:cl:

2024-07-24 19:59 UTC, larentoun requested changes
что за _reborn

2024-07-24 19:59 UTC, larentoun commented on modular_bandastation/vending/vending.dm
> +	light_mask = null
зачем мы ставим в ините?

2024-07-24 19:59 UTC, larentoun commented on modular_bandastation/vending/vending.dm
> +		)
Это можно перенести в build_inventories(), пример есть где-то в модулях

2024-07-24 19:59 UTC, larentoun commented on modular_bandastation/job_outfits/roboticist.dm
> +// Roboticist's outfit
лишние комменты везде убери

2024-07-24 20:01 UTC, larentoun requested changes
А как так получилось, что это не модуль?

2024-07-24 20:03 UTC, AloeNeverDie commented
> что за _reborn

_reborn просто наименование, чтобы т.к. по сути все из одной коллекции, если надо могу на дефолт robo*name* сделать

2024-07-26 09:44 UTC, larentoun commented on modular_bandastation/objects/code/vending/vending.dm
> +	light_mask = null
Почему это в ините

2024-07-26 13:14 UTC, larentoun requested changes
Мне не нравится, альтернативная одежда роботеха не наследуется от одежды роботеха.

Главный вопрос. Это альтернатива или замена?

2024-07-26 13:15 UTC, Gaxeer approved these changes

2024-07-26 13:15 UTC, AloeNeverDie commented
Одежда старая полностью остается, просто раундстарт будет замена на новую, при желании можно купить старую в вендомате

2024-07-26 18:43 UTC, larentoun requested changes

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	inhand_icon_state = null
а почему нулл?

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS
Почему оно закрывает лицо?

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	body_parts_covered = CHEST|GROIN|LEGS|ARMS
Ноги точно тут должны быть?

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/clothing/suits/wintercoats.dm
> +	hoodtype = NONE
Почему зимняя одежда не имеет капюшона? Это её фича

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/clothing/under/jobs/rnd.dm
> +	icon_state = "robotics"
зачем повторять

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/clothing/suits/wintercoats.dm
> +	return NONE // Restrict user to zip and unzip coat
у тебя же ниже в файлах используется var/can_adjust, почему тут альт-клик?

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/job_outfits/roboticist.dm
> +/datum/outfit/job/roboticist
все еще не уверен, что стоит оставлять это раундстарт одеждой, пусть покупают

2024-07-26 18:43 UTC, larentoun commented on modular_bandastation/objects/code/vending/vending.dm
> +	products = new_products
А нельзя было пропусить этот пункт и сразу сделать products |= new_products?

2024-07-27 06:32 UTC, AloeNeverDie commented on modular_bandastation/objects/code/vending/vending.dm
> +	products = new_products
Нет, тогда в вендомате будет только новая одежда, смысл в том, чтобы новая одежда в вендомате была сверху, а не снизу

2024-07-27 06:32 UTC, AloeNeverDie commented on modular_bandastation/objects/code/job_outfits/roboticist.dm
> +/datum/outfit/job/roboticist
окей

2024-07-27 06:35 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/wintercoats.dm
> +	hoodtype = NONE
Потому что это пальто по сути, без капюшона

2024-07-27 06:36 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	inhand_icon_state = null
Везде в коде для inhand_icon_state прописывают null

2024-07-27 06:43 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS
Сделано как у других капюшонов, привер роба священника 
![image](https://github.com/user-attachments/assets/072a35b7-1842-494a-bbc1-7f1dbe7a851e)

2024-07-27 06:49 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	body_parts_covered = CHEST|GROIN|LEGS|ARMS
Убрал

2024-07-27 06:55 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/wintercoats.dm
> +	return NONE // Restrict user to zip and unzip coat
потому что var/can_adjust для wintertcoat не работает и предназначен для /clothing/under, либо я скиллишу и не знаю как его правильно добавить

2024-07-27 18:52 UTC, larentoun commented on modular_bandastation/objects/code/vending/vending.dm
> +	products = new_products
А почему она не должна быть снизу?

2024-07-27 18:53 UTC, larentoun commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS
Роба священника "сильнее", а у нас тут альтернатива зимним

2024-07-27 19:14 UTC, AloeNeverDie commented on modular_bandastation/objects/code/vending/vending.dm
> +	products = new_products
Хочется новые шмотки сверху иметь + человек (новичок), который зайдет в робо вендомат может заметить новую одежду сразу и получить мысль о том, что "О, крутая шмотка, куплю посмотрю её", что повысит шанс её покупки, а если она будет снизу - человек может даже и не увидеть.

2024-07-27 19:16 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS
Это просто пример, у того же культа так же, да и если внешне посмотреть - у человека скрыто лицо, уши и волосы 
![image](https://github.com/user-attachments/assets/5774949a-4e3d-4f3e-bdb0-859c1ce29258)

2024-07-27 19:17 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/cloaks.dm
> +	flags_inv = HIDEHAIR|HIDEFACE|HIDEEARS
Но если так надо, могу убрать, только скажи, по мне так норм в этом плане

2024-07-28 17:45 UTC, larentoun commented on modular_bandastation/objects/code/clothing/suits/wintercoats.dm
> +	return NONE // Restrict user to zip and unzip coat
А зачем тогда наследоваться от hooded тогда...

2024-07-28 17:47 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/wintercoats.dm
> +	return NONE // Restrict user to zip and unzip coat
Потому что зимние пальто?

2024-07-28 17:48 UTC, larentoun approved these changes

2024-07-28 17:48 UTC, AloeNeverDie commented on modular_bandastation/objects/code/clothing/suits/wintercoats.dm
> +	return NONE // Restrict user to zip and unzip coat
Да

2024-07-28 17:51 UTC, merged