Обновленная медицинская система: Шанс провалов
ss220club/BandaStation pull request #461
Opened 2024-07-25 20:29 UTC by msw7007

## About The Pull Request

Является одним из частей медицинской системы, влияющей на шанс провала.
Шанс изначально равен 50 процентов.
Снижается за счет: света, правильного инструмента, анестезии. 

На первом шаге, в дальнейшем при интеграции других модулей обновленной медицинской системы шанс будет так-же отдельно рассчитываться в случае различных антибиотиков, добавлять боль по механу боли, будет проходить расчет шанса заражения, но ведь главное начать?

## Why It's Good For The Game

ХВАТИТ ПРЕНЕБРЕГАТЬ ОБЕЗБОЛИВАЮЩИМИ АНЕСТЕТИКОМ, МОРФИНОМ, ШАХТЕРСКОЙ МАЗЬЮ, ОПРЕДЛЕННЫМИ НАРКОТИКАМИ И ВЫПИВКОЙ!

## Changelog

:cl:
balance: шанс провала операции изначально всегда равен 70 процентов и снижается при обезболе.
/:cl:

2024-07-28 18:12 UTC, Gaxeer requested changes

2024-07-28 18:12 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +	var/success_prob = implements[implement_type]
```suggestion
	var/success_prob = implements_type ? implements[implement_type] : 100
```

2024-07-28 18:12 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +	var/turf/user_turf = user.loc
```suggestion
	var/turf/user_turf = get_turf(user)
```

2024-07-28 18:12 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +		success_prob += (1/tool.toolspeed) * 10
```suggestion
```

Давай пока без этого

2024-07-28 18:12 UTC, Gaxeer commented on modular_bandastation/medical/_medicalPlus.dm
> +/datum/modpack/medicalPlus
```suggestion
/datum/modpack/medicine_extension
```

2024-07-28 18:12 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +		success_prob += clamp(light_amount, 0.6, 1) * 20
не стоит бафать от более хорошей освещенности, я считаю. Надо иметь порог в "достаточный" уровень освещения, и уже при его уменьшении ДЕбафать

2024-07-28 18:12 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +		success_prob += (1/tool.toolspeed) * 10
Так как у нас ниже всё равно идет `fail_prob *= modded_time / time`

2024-09-20 09:38 UTC, PhantornRU requested changes
То что Гахер сверху написал сделай.
+обнови ветку

2024-09-20 15:41 UTC, msw7007 commented
> То что Гахер сверху написал сделай. +обнови ветку

Обновлена, необходимость в переименовке отсутствует теперь

2024-09-21 15:20 UTC, PhantornRU approved these changes
В принципе гуд, но я бы значения в дефайны вынес.

2024-12-22 11:31 UTC, fineks commented
Этот PR **### ПОЛНЫЙ ПРОВАЛ**

2025-01-15 05:33 UTC, PhantornRU approved these changes
Okay

2025-01-15 05:35 UTC, PhantornRU requested changes

2025-01-15 05:35 UTC, PhantornRU commented on code/modules/surgery/surgery_step.dm
> +	fail_prob = get_failure_probability(user,target,tool,modded_time,)//if modded_time > time * modifier, then fail_prob = modded_time - time*modifier. starts at 0, caps at 99 // BANDASTATION EDIT
В последнем запятая, не хочешь туда ничего добавить? Да и комментарий имеет смысл тогда убрать, коль ты весь прок во внутрянку переписал
```suggestion
	fail_prob = get_failure_probability(user, target, tool, modded_time) // BANDASTATION EDIT
```

2025-01-15 05:36 UTC, PhantornRU commented
Доделай ревью, обнови бранч и можно пихать в ТМ на пару неделек.

2025-01-15 07:12 UTC, msw7007 commented on code/modules/surgery/surgery_step.dm
> +	fail_prob = get_failure_probability(user,target,tool,modded_time,)//if modded_time > time * modifier, then fail_prob = modded_time - time*modifier. starts at 0, caps at 99 // BANDASTATION EDIT
Оно закоменчено для истории

2025-01-27 02:14 UTC, PhantornRU commented
Апдейт бранча и можно в ТМ пробовать

2025-03-16 10:03 UTC, AyIong commented
Слишком долго висит без каких либо сподвижек. Снимаю Stale Exempt

2025-04-14 19:28 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +	owner.remove_traits(list(TRAIT_ANALGESIA), TRAIT_STATUS_EFFECT(id))
```suggestion
```

Стазис кровати и так оверпавер.

2025-04-15 09:58 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +#undef CRITICAL_SUCCESS_CHANCE
#define SURGERY_LIGHT_AMOUNT_REQUIRED 0.6
#define MIN_LIGHT_SURGFAIL_PROBABILITY_INCREASE 0
#define MAX_LIGHT_SURGFAIL_PROBABILITY_INCREASE 12
#define NO_PAINKILLER_SURGFAIL_PROBABILITY_INCREASE 70
#define BASIC_SURGERY_SUCCESS_CHANCE 100

/datum/surgery_step/proc/get_failure_probability(mob/living/user, mob/living/target, target_zone, obj/item/tool, var/modded_time)
	var/success_prob = implement_type ? implements[implement_type] : BASIC_SURGERY_SUCCESS_CHANCE
	if(!user.has_nightvision())
		var/turf/target_turf = get_turf(target)
		var/light_amount = target_turf.get_lumcount()
		if (light_amount < SURGERY_LIGHT_AMOUNT_REQUIRED)
			var/actual_to_required_light_ratio = clamp(light_amount, 0, SURGERY_LIGHT_AMOUNT_REQUIRED) / SURGERY_LIGHT_AMOUNT_REQUIRED
			success_prob -= LERP(MAX_LIGHT_SURGFAIL_PROBABILITY_INCREASE, MIN_LIGHT_SURGFAIL_PROBABILITY_INCREASE, actual_to_required_light_ratio)

	var/obj/item/bodypart/target_part = target.get_bodypart(target_zone)
	if(
		!(target_part.bodytype & BODYTYPE_ROBOTIC) &&\
		!(\
			target.stat == UNCONSCIOUS ||\
			target.IsSleeping() ||\
			target.stat == DEAD ||\
			HAS_TRAIT(target, TRAIT_ANALGESIA)\
		)\
	)
		success_prob -= NO_PAINKILLER_SURGFAIL_PROBABILITY_INCREASE

	var/fail_prob = clamp(BASIC_SURGERY_SUCCESS_CHANCE - success_prob, 0, 100)

	return fail_prob

#undef SURGERY_LIGHT_AMOUNT_REQUIRED
#undef MIN_LIGHT_SURGFAIL_PROBABILITY_INCREASE
#undef MAX_LIGHT_SURGFAIL_PROBABILITY_INCREASE
#undef NO_PAINKILLER_SURGFAIL_PROBABILITY_INCREASE
#undef BASIC_SURGERY_SUCCESS_CHANCE

2025-04-15 09:58 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/surgery_fail_chance.dm
> +#undef CRITICAL_SUCCESS_CHANCE
```suggestion
#define SURGERY_LIGHT_AMOUNT_REQUIRED 0.6
#define MIN_LIGHT_SURGFAIL_PROBABILITY_INCREASE 0
#define MAX_LIGHT_SURGFAIL_PROBABILITY_INCREASE 12
#define NO_PAINKILLER_SURGFAIL_PROBABILITY_INCREASE 70
#define BASIC_SURGERY_SUCCESS_CHANCE 100

/datum/surgery_step/proc/get_failure_probability(mob/living/user, mob/living/target, target_zone, obj/item/tool, var/modded_time)
	var/success_prob = implement_type ? implements[implement_type] : BASIC_SURGERY_SUCCESS_CHANCE
	if(!user.has_nightvision())
		var/turf/target_turf = get_turf(target)
		var/light_amount = target_turf.get_lumcount()
		if (light_amount < SURGERY_LIGHT_AMOUNT_REQUIRED)
			var/actual_to_required_light_ratio = clamp(light_amount, 0, SURGERY_LIGHT_AMOUNT_REQUIRED) / SURGERY_LIGHT_AMOUNT_REQUIRED
			success_prob -= LERP(MAX_LIGHT_SURGFAIL_PROBABILITY_INCREASE, MIN_LIGHT_SURGFAIL_PROBABILITY_INCREASE, actual_to_required_light_ratio)

	var/obj/item/bodypart/target_part = target.get_bodypart(target_zone)
	if(
		!(target_part.bodytype & BODYTYPE_ROBOTIC) &&\
		!(\
			target.stat == UNCONSCIOUS ||\
			target.IsSleeping() ||\
			target.stat == DEAD ||\
			HAS_TRAIT(target, TRAIT_ANALGESIA)\
		)\
	)
		success_prob -= NO_PAINKILLER_SURGFAIL_PROBABILITY_INCREASE

	var/fail_prob = clamp(BASIC_SURGERY_SUCCESS_CHANCE - success_prob, 0, 100)

	return fail_prob

#undef SURGERY_LIGHT_AMOUNT_REQUIRED
#undef MIN_LIGHT_SURGFAIL_PROBABILITY_INCREASE
#undef MAX_LIGHT_SURGFAIL_PROBABILITY_INCREASE
#undef NO_PAINKILLER_SURGFAIL_PROBABILITY_INCREASE
#undef BASIC_SURGERY_SUCCESS_CHANCE
```

2025-04-15 09:59 UTC, Gaxeer approved these changes

2025-04-15 10:16 UTC, merged