Напитки с парадиза
ss220club/Bandastation pull request #467
Opened 2024-07-30 11:34 UTC by Chorden523

## About The Pull Request
Портирует некоторые напитки с парадиза

## Why It's Good For The Game
Бухло это всегда вкусно и весело

## Изображения изменений
![image](https://github.com/user-attachments/assets/3c42486e-3dbe-4042-8804-37cde0d362e1)
![image](https://github.com/user-attachments/assets/db2a313f-36c4-4fcf-9e14-f661651e0919)

2024-07-30 14:35 UTC, larentoun requested changes
Вроде норм, в игре проверил?

2024-07-30 14:35 UTC, larentoun commented on modular_bandastation/food/_food.dm
> +/datum/modpack/drinks
Предлагаю перенести в модуль objects, папкой consumables

2024-07-30 14:35 UTC, larentoun commented on modular_bandastation/food/code/drinks/drinks.dm
> +	taste_description = "a pleasant tartness with a hint of sweetness and a bread-like aftertaste."
можно было и перевести

2024-07-30 14:38 UTC, Chorden523 commented
> Вроде норм, в игре проверил?

Почти всё проверил, только не проверял как это будет работать с ботами барными, которые напитки покупают.

2024-07-30 15:46 UTC, larentoun commented
> > Вроде норм, в игре проверил?
> 
> Почти всё проверил, только не проверял как это будет работать с ботами барными, которые напитки покупают.

Каждый бот имеет свой список, он не генерируется, насколько я понимаю

2024-07-30 15:46 UTC, larentoun approved these changes

2024-07-30 16:43 UTC, Gaxeer commented on modular_bandastation/objects/_objects.dme
> +#include "code/consumables/drinks.dm"
в алфавитном порядке всё поменяй

2024-08-22 11:03 UTC, Gaxeer approved these changes

2024-08-24 06:43 UTC, VentelR commented
Проверил на локалке с сильверхендом, ягермейстером, и олдфэшн, боты ушли довольные.

2024-08-24 06:49 UTC, Gaxeer approved these changes

2024-08-24 06:50 UTC, merged