Операция по смене TTS
ss220club/Bandastation pull request #470
Opened 2024-07-30 22:32 UTC by Boyarinov

## About The Pull Request

Новая операции на рот для изменения TTS голоса
Инструменты для проведения взял из кода трупа пары

## Why It's Good For The Game

Добавление в IC того, что делалось через админов
Дополнительные возможности для отыгрыша

## Changelog

:cl:
add: Операция по смене голоса

/:cl:

2024-07-30 22:36 UTC, Boyarinov commented
Есть вопросы:
Нужно ли сразу делать текст на русском?
Нужны ли какие-то ограничения в can_start для этой операции?

2024-07-31 07:09 UTC, Gaxeer commented
> Возможно стоит дать выбор голоса пациенту, а не хирургу, чтоб избежать выяснения нужного голоса через LOOC
> 
> И есть вопросы: Нужно ли сразу делать текст на русском? Нужны ли какие-то ограничения в can_start для этой операции?

Ну, хирург же вносит коррективы, значит он выбирает голос. Не вижу в этом проблем.

2024-07-31 07:17 UTC, Gaxeer requested changes

2024-07-31 07:17 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +	time = 64
```suggestion
	time = 6.4 SECONDS
```

2024-07-31 07:17 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +		/obj/item/wirecutters = 35)
```suggestion
	implements = list(
		TOOL_SCALPEL = 100,
		/obj/item/kitchen/knife = 50,
		/obj/item/wirecutters = 35
	)
```

2024-07-31 07:17 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +
```suggestion
```

2024-07-31 07:17 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +
```suggestion
```

2024-07-31 07:17 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +	return FALSE
Можешь всё сразу на русском писать

2024-08-01 08:45 UTC, Gaxeer requested changes

2024-08-01 08:45 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +// Surgery to change TTS voice
```suggestion
```

2024-08-01 08:45 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +// tune vocal cords
```suggestion

```

2024-08-01 08:45 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +
```suggestion
```

2024-08-01 20:43 UTC, Gaxeer commented on modular_bandastation/medical/code/surgery/vocal_cords.dm
> +/datum/surgery_step/tune_vocal_cords
```suggestion
	)
	
/datum/surgery_step/tune_vocal_cords
```

2024-08-02 07:24 UTC, Gaxeer approved these changes

2024-08-02 07:25 UTC, merged