Nanomaps in security consoles
ss220club/Bandastation pull request #474
Opened 2024-07-31 15:00 UTC by larentoun

## About The Pull Request

Добавляет наномапы в консоли CCTV
Если карты нет - рантаймов не будет, просто не будет картинки карты.

На будущее: надо бы в скрипт наномап убрать турфы лавы и айсмуна

## Why It's Good For The Game

<details><summary>Айс</summary>

![ice1](https://github.com/user-attachments/assets/6e5729de-59fa-47d4-95a3-4370e2d01eb6)
![ice2](https://github.com/user-attachments/assets/a7eff0f6-84a6-430b-beb5-f00d9ec47f56)
![ice3](https://github.com/user-attachments/assets/7796e9ac-07e6-43b6-a034-92affedd016f)

</details>
<details><summary>Мета</summary>

![meta](https://github.com/user-attachments/assets/c2e12ac6-fcce-4273-b8b7-0cff12faebd1)

</details>
<details><summary>Лава (общая для многих карт)</summary>

![meta2](https://github.com/user-attachments/assets/e4dceb5d-a467-487f-89f4-c1e3e686f159)

</details>
<details><summary>Берд</summary>

![bird](https://github.com/user-attachments/assets/6e7addd9-9f14-4728-8280-861ab37704cf)

</details>
<details><summary>Дельта</summary>

![delta](https://github.com/user-attachments/assets/d7198b5c-4233-4a04-97ef-ee7804174462)

</details>
<details><summary>Норстар</summary>

![Screenshot_1](https://github.com/user-attachments/assets/036e0a19-2f4e-4c14-85eb-601655e53d26)
![Screenshot_2](https://github.com/user-attachments/assets/4aa7b307-b846-4384-8264-ba85139e5cb0)
![Screenshot_3](https://github.com/user-attachments/assets/a4a9e265-926a-4ba7-a341-b91138953bd6)
![Screenshot_4](https://github.com/user-attachments/assets/c2006df0-fd83-4c48-bc66-605a124f519a)

</details>
<details><summary>Трам</summary>

![Screenshot_5](https://github.com/user-attachments/assets/4cf29631-4279-4da1-9e27-f82e3567aaaf)
![Screenshot_6](https://github.com/user-attachments/assets/cd540048-70d8-464d-ba23-1e565da0270f)

</details>
<details><summary>Вава</summary>

![Screenshot_7](https://github.com/user-attachments/assets/75025394-82a1-44dd-847c-16d05c0a8c3f)
![Screenshot_8](https://github.com/user-attachments/assets/60d4c477-1f19-4632-ab8e-4649eacbd9c4)

</details>

## Changelog

:cl:
add: Добавлена карта для CCTV
/:cl:

2024-07-31 15:04 UTC, larentoun commented
Легендарный топор, помоги починить зеленый айс мун и черный при-черный лаваленд

2024-07-31 15:13 UTC, Gaxeer requested changes

2024-07-31 15:13 UTC, Gaxeer commented on modular_bandastation/nanomap/code/nanomaps_asset.dm
> +		"Lavaland_nanomap_z1.png"		= 'icons/_nanomaps/Lavaland_nanomap_z1.png',
```suggestion
		"Birdshot Station_nanomap_z1.png" = 'icons/_nanomaps/Birdshot Station_nanomap_z1.png',
		"Delta Station_nanomap_z1.png" = 'icons/_nanomaps/Delta Station_nanomap_z1.png',
		"Ice Box Station_nanomap_z1.png" = 'icons/_nanomaps/Ice Box Station_nanomap_z1.png',
		"Ice Box Station_nanomap_z2.png" = 'icons/_nanomaps/Ice Box Station_nanomap_z2.png',
		"Ice Box Station_nanomap_z3.png" = 'icons/_nanomaps/Ice Box Station_nanomap_z3.png',
		"MetaStation_nanomap_z1.png" = 'icons/_nanomaps/MetaStation_nanomap_z1.png',
		"NorthStar_nanomap_z1.png" = 'icons/_nanomaps/NorthStar_nanomap_z1.png',
		"NorthStar_nanomap_z2.png" = 'icons/_nanomaps/NorthStar_nanomap_z2.png',
		"NorthStar_nanomap_z3.png" = 'icons/_nanomaps/NorthStar_nanomap_z3.png',
		"NorthStar_nanomap_z4.png" = 'icons/_nanomaps/NorthStar_nanomap_z4.png',
		"Tramstation_nanomap_z1.png" = 'icons/_nanomaps/Tramstation_nanomap_z1.png',
		"Tramstation_nanomap_z2.png" = 'icons/_nanomaps/Tramstation_nanomap_z2.png',
		"Wawastation_nanomap_z1.png" = 'icons/_nanomaps/Wawastation_nanomap_z1.png',
		"Wawastation_nanomap_z2.png" = 'icons/_nanomaps/Wawastation_nanomap_z2.png',
		"Lavaland_nanomap_z1.png" = 'icons/_nanomaps/Lavaland_nanomap_z1.png',
```

2024-08-01 09:20 UTC, Graybear98 commented
С обычных консолей камер ты не сможешь увидеть камеры у им, чтобы никто не мог спалить малфа, может и тут стоит отрубить?

2024-08-01 10:05 UTC, larentoun commented
> С обычных консолей камер ты не сможешь увидеть камеры у ИИ, чтобы никто не мог спалить малфа, может и тут стоит отрубить?

Что именно ты имеешь ввиду? Список доступных камер такой же, как и у обычного листа

2024-08-01 11:52 UTC, Graybear98 commented
> > С обычных консолей камер ты не сможешь увидеть камеры у ИИ, чтобы никто не мог спалить малфа, может и тут стоит отрубить?
> 
> Что именно ты имеешь ввиду? Список доступных камер такой же, как и у обычного листа

Ты не должен видеть камеры на саттелите у иишки, тем не менее на скриншотах отображаются квадратики, что они видны

2024-08-01 11:53 UTC, Graybear98 commented
![Uploading Screenshot_2024-08-01-14-53-22-40_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

2024-08-01 17:26 UTC, larentoun commented
> > > С обычных консолей камер ты не сможешь увидеть камеры у ИИ, чтобы никто не мог спалить малфа, может и тут стоит отрубить?
> > 
> > 
> > Что именно ты имеешь ввиду? Список доступных камер такой же, как и у обычного листа
> 
> Ты не должен видеть камеры на саттелите у иишки, тем не менее на скриншотах отображаются квадратики, что они видны

![image](https://github.com/user-attachments/assets/7a7ade53-e3dd-4683-aad6-6af505fd7201)

Я повторюсь. Список доступных камер не меняется. Это уже обращайся к мапперам, что забыли сделать камеры недоступными. На айсбоксе они недоступны, как видно

2024-10-04 10:33 UTC, Legendaxe approved these changes

2024-10-04 10:42 UTC, merged