Awaymission aeg port
ss220club/Bandastation pull request #475
Opened 2024-07-31 19:00 UTC by Chorden523

## About The Pull Request
Портирует гейтган с парадиза

## Why It's Good For The Game
Пушка для изучения гейтов

## Изображения изменений
![image](https://github.com/user-attachments/assets/336bd1d1-acd2-4b4f-aa11-d812e4441056)
![image](https://github.com/user-attachments/assets/8fccf3e6-2d04-44ec-9495-f3398810292f)

2024-08-01 10:32 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +/datum/techweb_node/awaymission_aeg
Мне не нравится, что две пушки, где вторая прямой апгрейд, находятся в одной ветке. Так как исследователи просто улетают вникуда и никогда не возвращаются в раунд, предлагаю сделать их снаряжение "подтипом" для шахтера

Базовая:
* Открывается вместе с TECHWEB_NODE_MINING
Улучшенная:
* Открывается вместе с TECHWEB_NODE_PLASMA_MINING

2024-08-01 10:33 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	name = "Gate Energy Gun MK2"
Дизайны и имя оружия не совпадают

2024-08-01 17:23 UTC, larentoun approved these changes
Я вообще имел ввиду разницу между EXploreverse и Gate Energy Gun, но да ладно

2024-08-02 11:25 UTC, larentoun requested changes

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	can_charge = 0
```suggestion
	can_charge = FALSE
```

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	force = 10
Просто интересно, почему повышен урон?

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	cell.give(1000)
```suggestion
	cell.give(STANDARD_CELL_CHARGE * 0.1)
```

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	user.visible_message(msg_recharge_all, msg_recharge_user)
Замени это всё на баллуны

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +		user.visible_message(msg_for_all, msg_for_user)
баллун

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +		user.visible_message(msg_for_all, msg_for_user)
баллун

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +		user.visible_message(
баллун

2024-08-02 11:25 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	departmental_flags = DEPARTMENT_BITFLAG_CARGO
Добавь еще в РНД на всякий оба

2024-08-02 11:27 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	cell.give(1000)
А вообще лучше в снарядах расчитывать, скорее всего

2024-08-02 11:27 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	cell.give(1000)
Пусть одна прокрутка даёт одну пульку?

2024-08-02 11:43 UTC, Chorden523 commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	force = 10
Ctrl + C и Ctrl + V

2024-08-05 11:39 UTC, larentoun requested changes

2024-08-05 11:39 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	cell.charge = 0
Используй прок, чтобы потратить всю энергию

2024-08-05 11:39 UTC, larentoun commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	departmental_flags = DEPARTMENT_BITFLAG_CARGO | DEPARTMENT_BITFLAG_SCIENCE
Пробела нет между строками?

2024-08-05 12:27 UTC, Chorden523 commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	departmental_flags = DEPARTMENT_BITFLAG_CARGO | DEPARTMENT_BITFLAG_SCIENCE
Пробелов нет тут

2024-08-07 07:48 UTC, Chorden523 commented on modular_bandastation/objects/code/weapons/ranged/awaymission_gun.dm
> +	cell.charge = 0
Может я что-то не понимаю, но я уже использую прок чтобы разрядить гейтган

2024-08-08 14:30 UTC, larentoun approved these changes

2024-08-08 14:31 UTC, merged