Лодаут - очки
ss220club/Bandastation pull request #483
Opened 2024-08-02 16:40 UTC by msw7007

## About The Pull Request

Добавляет очки в зависимости от уровня доната.
Вводит цены на предметы из лодаута.

## Why It's Good For The Game

Внедряет ограничение на вещи из лодаута.

## Changelog

:cl:
add: Добавление очков доната для ограничения вещей в лодауте
/:cl:

2024-08-03 11:58 UTC, Lime-7 commented
1984

2024-09-06 09:00 UTC, Furrior requested changes

2024-09-09 16:40 UTC, Furrior reviewed
Все еще остается вопрос по тому, что концепт "оставшихся" поинтов достаточно хрупкий

2024-09-09 16:40 UTC, Furrior commented on modular_bandastation/preferences/code/modules/client/preferences.dm
> +			parent.loadout_points = 20
Я имел ввиду хранить var/loadout_points в префах, а не клиенте

2024-09-09 16:41 UTC, Furrior commented
Остается = я изначально написал пасту, а гитхаб ее спиздил

2024-09-09 16:43 UTC, Furrior commented on modular_bandastation/loadout/code/loadout_preference.dm
> +	.=..()
Крч мне не нравится система с убавлением оставшихся поинтов. Она как бы и логичная, но, имхо, лучше будет считать оставшиеся поинты в интерфейсе, а на бэке перепроверять, что все сходится, когда юзер добавляет предмет лодаута, просто

2024-09-20 09:39 UTC, PhantornRU commented on code/modules/loadout/loadout_menu.dm
> +	data["loadout_leftpoints"] = preferences.loadout_points
// SS220 ADD - Lodout points

2024-09-20 09:40 UTC, PhantornRU commented on code/modules/loadout/loadout_menu.dm
> +	preferences.loadout_points = preferences.get_loadout_points()
Добавь комменты аля // SS220 ADD - Lodout points

2024-09-20 09:40 UTC, PhantornRU requested changes

2024-09-20 09:40 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/PreferencesMenu/loadout/index.tsx
> +  const loadout_leftpoints = data.loadout_leftpoints || '0';
// SS220 ADD - Lodout points
Сюда тоже бы комменты

2024-09-21 15:18 UTC, PhantornRU requested changes

2024-09-21 15:18 UTC, PhantornRU commented on modular_bandastation/preferences/code/modules/client/preferences.dm
> +			loadout_points = 20
Нужны дефайны ТИРов. Посмотри в нашем Парадайзе как было сделано. Хардкодом это лучше не делать.

2024-09-21 15:18 UTC, PhantornRU commented on modular_bandastation/preferences/code/modules/client/preferences.dm
> +	var/donation_level = savefile.get_entry("donator_level", 0)
тоже

2024-09-21 15:18 UTC, PhantornRU commented on modular_bandastation/loadout/code/loadout_items.dm
>  	var/donator_level = 0
дефайн ебани

2024-09-21 15:18 UTC, PhantornRU commented on modular_bandastation/loadout/code/client.dm
>  	var/donator_level = 0
дефайны нужны

2024-09-21 15:19 UTC, PhantornRU commented
И ветку обнови

2024-11-02 08:40 UTC, Furrior approved these changes
Под залог жопы кагелите

2024-11-02 08:40 UTC, merged