Криокапсулы
ss220club/Bandastation pull request #488
Opened 2024-08-19 23:47 UTC by RosSample

## About The Pull Request

Добавляет капсулы криосна, но их нужно будет расставить по картам :Fortune:

## Why It's Good For The Game

Освобождает слоты на командные роли и ИИ при их криосонировании (тело ССДшника можно отнести в крио через 30 минут после выхода) и дает муд бафф, если отвести спессменчика в спать в криокроватку.

## Changelog

:cl:
add: Добавлены криокапсулы
/:cl:

2024-08-20 06:08 UTC, dj-34 commented
> Добавляет капсулы криосна, но их нужно будет расставить по картам :Fortune:

Так просто перенеси модульные изменения карт и закинь в конфиг автомаппера?

2024-08-21 09:41 UTC, RosSample commented
> > Добавляет капсулы криосна, но их нужно будет расставить по картам :Fortune:
> 
> Так просто перенеси модульные изменения карт и закинь в конфиг автомаппера?

Сделал :Fortune:

2024-09-06 09:06 UTC, Furrior requested changes

2024-09-06 09:06 UTC, Furrior commented on code/game/gamemodes/objective.dm
>  	return ..()
Делай модульно

2024-09-06 09:06 UTC, Furrior commented on modular_bandastation/cryosleep/code/admin.dm
> +	sparks.start()
Вынеси в отдельный прок

2024-09-06 09:06 UTC, Furrior commented on modular_bandastation/cryosleep/code/admin.dm
> +		cryo_paper.update_appearance()
Это тоже

2024-09-06 09:06 UTC, Furrior commented on modular_bandastation/cryosleep/code/admin.dm
> +		if(!cryo.occupant && cryo.state_open && !cryo.panel_open) //free, opened, and panel closed?
Это тоже в прок уровня get_available_cryopod

2024-09-06 09:06 UTC, Furrior commented on modular_bandastation/cryosleep/code/cryo_console_return.dm
> +	for(var/obj/machinery/computer/cryopod/cryo_console in GLOB.cryopod_computers)
Аналогично

2024-09-06 09:06 UTC, Furrior commented on modular_bandastation/cryosleep/code/mind.dm
> +	var/list/datum/objective/objectives = list()
Зачем?

2024-09-20 09:42 UTC, PhantornRU requested changes
Изменения из: code/game/gamemodes/objective.dm - перенести в модульность.

2024-10-31 15:10 UTC, closed without merging