Продолжение перевода кухни
ss220club/Bandastation pull request #504
Opened 2024-10-04 15:54 UTC by msw7007

## About The Pull Request

Продолжение перевода кухни от каркарчеса

## Why It's Good For The Game

РУССКИЙ

## Changelog

Пока не русский

:cl:
/:cl:

https://github.com/ss220club/Bandastation/pull/292

2024-10-04 17:08 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("Это [source.name]. [capitalize(initial(bake_result.name))] могут быть [span_bold("приготовлены")] из нее.")
Пример использования declent_ru()
```suggestion
				examine_list += span_notice("[capitalize(initial(bake_result.name))] могут быть [span_bold("приготовлены")] из [parent.declent_ru(GENITIVE)].")
```

2024-10-06 12:44 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +	name = "фритюрница"
Не переводи `name`. В отдельном ПРе сделай типо такого
```suggestion
	name = "deep fryer"
	ru_names = RU_NAMES_LIST_INIT("deep fryer", "фритюрница", "фритюрницы", "фритюрнице", "фритюрницу", "фритюрницей", "фритюрнице")
```

2024-10-06 18:34 UTC, larentoun commented
В начале предложений не забудь добавлять capitalize()
src.declent_ru() -> declent_ru()
Добавь деклент ко всему, включая user, target и тд

2024-10-07 11:27 UTC, larentoun requested changes
1. Замени все `объект.name` на `объект.declent_ru(ПАДЕЖ)`
2. Если объект стоит в начале предложения, не забудь поставить `capitalize()`
3. `src.declent_ru()` -> `declent_ru()`

2024-10-07 13:17 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("Это [source.declent_ru(NOMINATIVE)]. [capitalize(span_bold("Можно"))] приготовить в [initial(bake_result.declent_ru(ACCUSATIVE))].")
У нас есть переменные, как `ru_name_nominative`, чтобы напрямую обращаться к переменой. Но следует сначала проверить, есть ли она.

`[initial(bake_result.ru_name_nominative) || [initial(bake_result.name)]`, думаю, сойдет?

2024-10-07 14:40 UTC, msw7007 commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("Это [source.declent_ru(NOMINATIVE)]. [capitalize(span_bold("Можно"))] приготовить в [initial(bake_result.declent_ru(ACCUSATIVE))].")
А зачем в макроса тогда именнительные?

2024-10-07 16:03 UTC, larentoun requested changes
Первичное ревью. У меня уже браузер тормозит от количества ревью. Учти то, что я указал, и пробегись по ВСЕМ файлам, а не только те, которые я осмотрел.

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +	to_chat(user, span_notice("Вы кладете [frying_item.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]."))
```suggestion
	to_chat(user, span_notice("Вы помещаете [frying_item.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]."))
```

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		visible_message(span_userdanger("[capitalize(declent_ru(NOMINATIVE))]  начинает пылать... О нет..."))
```suggestion
		visible_message(span_userdanger("[capitalize(declent_ru(NOMINATIVE))] начинает пылать... О нет..."))
```
Тут точно "пылать", а не "светиться"?

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +	visible_message(span_userdanger("[capitalize(name)] взрывается в результате энтропийной реакции!"))
деклент

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		to_chat(user, span_notice("Вы вытаскиваете [frying.name] из [declent_ru(GENITIVE)]]."))
деклент

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +			to_chat(user, span_warning("Тебе нужно получше схватить для этого!"))
```suggestion
			to_chat(user, span_warning("Для этого нужно усилить захват!"))
```

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		log_combat(user, dunking_target, "dunked", null, "into [name]")
как это произошло? Мы не переводим логи

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		user.visible_message(span_danger("[user] макает лицо [dunking_target.name] в [declent_ru(ACCUSATIVE)]]!"))
декленты

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +			dunking_target.visible_message(span_userdanger("[capitalize(dunking_target.name)] взрывается от энтропийной разницы! Блять!"))
декленты

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +			dunking_target.investigate_log("был развполощен в энтропиные пылинки (был обращен в [declent_ru(ACCUSATIVE)]]).", INVESTIGATE_DEATHS)
логи не переводим

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/food_cart.dm
> +	name = "тележка с едой"
нейм

2024-10-07 16:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/food_cart.dm
> +	name = "палатка тележки с едой"
нейм

2024-10-07 20:35 UTC, larentoun requested changes
Опять все те же ошибки.

Зайди по этой ссылке https://github.com/ss220club/Bandastation/pull/504/files и смотри на изменения, которые вносит ПР. Возможно, так будет легче смотреть?

Повторюсь. Я *НЕ* смотрел дальше тех файлов, что я отметил, потому что нет смысла проверять то, что все еще не исправлено.

2024-10-07 20:35 UTC, larentoun commented on code/datums/components/bakeable.dm
> +			examine_list += span_notice("Кажется, что блюдо '[parent.declent_ru(NOMINATIVE)]' почти готово!")
Блюдо "булочка" почти готово? Не "пирог"? Точно правильно тут?

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +	name = "coffee cartridge - Caffè Generico"
неймы.... везде пройдись снова.

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		user.visible_message(span_notice("[user.declent_ru(NOMINATIVE)] бросает [weapon.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]."), span_notice("Вы растворяете [weapon.declent_ru(ACCUSATIVE)] в
ну капиталайз, везде в начале предложения для фейлсейфа...

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		visible_message(span_userdanger("[capitalize(declent_ru(NOMINATIVE))]  начинает светиться... О нет..."))
```suggestion
		visible_message(span_userdanger("[capitalize(declent_ru(NOMINATIVE))] начинает светиться... О нет..."))
```

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		user.visible_message(span_danger("[user] макает лицо [dunking_target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]!"))
деклент...

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		user.visible_message(span_danger("[user] макает лицо [dunking_target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]!"))
капиталайз...

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/food_cart.dm
> +	name = "food cart stand"
неймы

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/gibber.dm
> +		name = "мясорубка"
как это случилось?

2024-10-07 20:35 UTC, larentoun commented on code/modules/food_and_drinks/machinery/gibber.dm
> +		. += span_notice("на дисплее состояния отображается: Вывод <b>[meat_produced]</b> мясных кусков через <b>[gibtime*0.1]</b> секунд работы.")
```suggestion
		. += span_notice("На дисплее состояния отображается: Вывод <b>[meat_produced]</b> мясных кусков через <b>[gibtime*0.1]</b> секунд работы.")
```

2024-10-10 17:09 UTC, larentoun requested changes
Дошел до мясоруки. Вижу, ты просишь ревью по тому, что еще не  готово к ревью. Всё те же ошибки. Я **НЕ** смотрю дальше.

2024-10-10 17:09 UTC, larentoun commented on code/datums/components/bakeable.dm
> +				examine_list += span_notice("Это [capitalize(parent.declent_ru(NOMINATIVE))]. [span_bold("запекается")] в [initial(bake_result.ru_name_accusative) || initial(bake_result.name)].")
тоже сделай лучше, как выше

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +		. += span_notice("Осталось [coffee_cups] [coffee_cups == 1 ? "кофейная чашка" : "кофейных чашек"].")
можно использовать declension_ru(), и использовать в других ситуациях, чтобы улучшить "речь"

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +		. += span_notice("Внутренняя кофемолка содержит [coffee.len] порций кофейных зерен")
declension_ru()

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +		balloon_alert(user, "добавил кофе")
```suggestion
		balloon_alert(user, "добавлено кофе")
```

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +						balloon_alert(user, "добавил кофе")
```suggestion
						balloon_alert(user, "добавлено кофе")
```

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		visible_message(span_userdanger("[capitalize(declent_ru(NOMINATIVE))]  начинает светиться... О нет..."))
```suggestion
		visible_message(span_userdanger("[capitalize(declent_ru(NOMINATIVE))] начинает светиться... О нет..."))
```

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		user.visible_message(span_danger("[capitalize(user.declent_ru(NOMINATIVE))] макает лицо [dunking_target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]!"))
```suggestion
		user.visible_message(span_danger("[capitalize(user.declent_ru(NOMINATIVE))] макает лицо [dunking_target.declent_ru(GENITIVE)] в [declent_ru(ACCUSATIVE)]!"))
```

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/food_cart.dm
> +	desc = "Что-нибудь для борьбы с солнцем, ведь перерывов в работе у работников бургерной нет."
```suggestion
	desc = "Что-то для борьбы с солнцем, ведь перерывов у работников бургерной нет."
```

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/gibber.dm
> +		to_chat(user, span_danger("он заблокирован и работает."))
```suggestion
		to_chat(user, span_danger("Машина работает, потому доступ заблокирован."))
```

2024-10-10 17:09 UTC, larentoun commented on code/modules/food_and_drinks/machinery/gibber.dm
> +		to_chat(user, span_warning("нельзя использовать мясорубку, пока она не прикручена к полу!"))
```suggestion
		to_chat(user, span_warning("Нельзя использовать [delcent_ru(ACCUSATIVE)], пока [ru_p_they()] не прикручена к полу!"))
```

2024-10-10 19:00 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +		span_hear("Вы слышите кухонный комбайн."))
время

2024-10-10 19:00 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +	playsound(loc, 'sound/machines/blender.ogg', 50, TRUE)
лишнее

2024-10-10 21:00 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +	desc = "Деревянное устройство, используемое для сушки растительных продуктов, пищи и шкур."
почему описания различаются в конце между этими двумя?

2024-10-10 21:00 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +	desc = "Холодильник для хранения вкусного алкоголя."
```suggestion
	desc = "Холодильник для хранения вкусного-вкусного алкоголя."
```

2024-10-10 21:02 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +		to_chat(user, span_notice("Вы добавляете [loaded] в [declent_ru(ACCUSATIVE)]."))
предметов в, даже перемещаете?

2024-10-10 21:02 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +		balloon_alert(user, "не могу добавить это!")
```suggestion
		balloon_alert(user, "нельзя это добавить!")
```

2024-10-10 21:02 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +	balloon_loc.balloon_alert(user, "добавлен ингредиент")
```suggestion
	balloon_loc.balloon_alert(user, "ингредиент добавлен")
```

2024-10-10 21:02 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove_component.dm
> +		real_parent.balloon_alert_to_viewers("нет энергии!")
```suggestion
		real_parent.balloon_alert_to_viewers("нет питания!")
```

2024-10-10 21:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove_component.dm
> +		to_chat(user, span_notice("Вы положили [attacking_item.declent_ru(NOMINATIVE)] на [parent.declent_ru(ACCUSATIVE)]."))
```suggestion
		to_chat(user, span_notice("Вы перемещаете [attacking_item.declent_ru(ACCUSATIVE)] на [parent.declent_ru(ACCUSATIVE)]."))
```

2024-10-10 21:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove_component.dm
> +		context[SCREENTIP_CONTEXT_LMB] = "Положить содержимое"
```suggestion
		context[SCREENTIP_CONTEXT_LMB] = "Положить контейнер"
```

2024-10-10 21:03 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove_component.dm
> +	examine_list += span_notice("Вы можете  [on ? "выключить" : "включить"] прожиг <i>правой кнопкой</i>.")
```suggestion
	examine_list += span_notice("Вы можете  [on ? "выключить" : "включить"] прожиг с помощью <i>ПКМ</i>.")
```

2024-10-10 21:04 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	name = "ХимМастер 3000"
имя

2024-10-10 21:04 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/chem_master.dm
> +	name = "ПриправМастер 3000"
имя

2024-10-10 21:04 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	name = "\improper Гриндер Все-в-одном"
имя

2024-10-10 21:04 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	desc = "От БлендТех. Перемолит ли? Проверим!"
перевод плохой, потеряна игра слов

2024-10-10 21:05 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_notice("Наполенен на <b>[round((total_weight / maximum_weight) * 100)]%</b> вместимости.")
```suggestion
		. += span_notice("Наполнен на <b>[round((total_weight / maximum_weight) * 100)]%</b> вместимости.")
```

2024-10-10 21:05 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_notice("Контейнер, наполененый <b>[beaker.reagents.maximum_volume]u</b> вставлен. Содержимое:")
```suggestion
		. += span_notice("Мензурка размером в <b>[beaker.reagents.maximum_volume]u</b> юнитов вставлена. Содержимое:")
```

2024-10-10 21:05 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
>  				. += span_notice("[round(reg.volume, CHEMICAL_VOLUME_ROUNDING)]u of [reg.name]")
```suggestion
				. += span_notice("[round(reg.volume, CHEMICAL_VOLUME_ROUNDING)] юнитов [reg.name]")
```

2024-10-10 21:05 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +			. += span_notice("Нет.")
```suggestion
			. += span_notice("Ничего.")
```

2024-10-10 21:06 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_notice("[EXAMINE_HINT("Right click")] пустой рукой, чтобы убрать контейнер.")
```suggestion
		. += span_notice("[EXAMINE_HINT("ПКМ")] пустой рукой для снятия мензурки.")
```

2024-10-10 21:07 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_warning("Нет контейнера.")
```suggestion
		. += span_warning("Нет мензурки.")
```

2024-10-10 21:08 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	. += span_notice("Вы можете перетащить предмет-хранилище на гриндер, чтобы поместить в него содержимое.")
```suggestion
	. += span_notice("Вы можете перетащить хранилище на [delcent_ru(ACCUSATIVE)], чтобы перемести всё содержимое.")
```

2024-10-10 21:08 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_notice("Он может быть [EXAMINE_HINT("отвинчен")].")
```suggestion
		. += span_notice("Машина может быть [EXAMINE_HINT("откручена")].")
```

2024-10-10 21:08 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_warning("Нужно что бы он был [EXAMINE_HINT("привинчен")] к полу для работы.")
```suggestion
		. += span_warning("Машина должна быть [EXAMINE_HINT("прикручена")] к полу для работы.")
```

2024-10-10 21:11 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +	. += span_notice("Его панель может быть [EXAMINE_HINT("овтерткой")] [panel_open ? "закрыта" : "открыта"].")
```suggestion
	. += span_notice("Панель обслуживания может быть [EXAMINE_HINT(panel_open ? "привинчина" : "отвинчина")].")
```

2024-10-10 21:11 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_notice("Можно [EXAMINE_HINT("вырвать")] сожержимое.")
```suggestion
		. += span_notice("Машина может быть [EXAMINE_HINT("вскрыта")].")
```

2024-10-10 21:12 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	name = "бутылка специй"
имя

2024-10-10 21:12 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	user.visible_message(span_suicide("[user] пытается проглоить содержимое [src.name]! Еда работает не так!"))
капиталайз и декленты

2024-10-10 21:49 UTC, larentoun commented on code/modules/food_and_drinks/machinery/gibber.dm
> +				. += span_notice("[capitalize(declent_ru(NOMINATIVE))] была модернизирована для обработки неорганических материалов.")
```suggestion
				. += span_notice("Машина была модернизирована для обработки неорганических материалов.")
```

2024-10-10 22:06 UTC, larentoun requested changes
В холодильнике комменты были зарезолвены и неизменены, или мне кажется?

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/gibber.dm
> +			to_chat(user, span_warning("[capitalize(C.declent_ru(NOMINATIVE))] уже к чему-то прикреплен!"))
```suggestion
			to_chat(user, span_warning("Тело [C.declent_ru(GENITIVE)] к чему-то пристегнуто!"))
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/monkeyrecycler.dm
> +		to_chat(user, span_warning("Обезьяна пристегнута к чему-то."))
```suggestion
		to_chat(user, span_warning("Тело обезьяны к чему-то пристегнуто."))
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/monkeyrecycler.dm
> +	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(to_chat), user, span_notice("Теперь машина имеет [stored_matter] хранящихся материалов стоимостью с обезьяну.")))
```suggestion
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(to_chat), user, span_notice("Теперь машина имеет материалов на обезьян: [stored_matter].")))
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/oven.dm
> +		to_chat(user, span_notice("Вы открыли [declent_ru(ACCUSATIVE)]."))
```suggestion
		to_chat(user, span_notice("Вы открываете [declent_ru(ACCUSATIVE)]."))
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/oven.dm
> +		to_chat(user, span_notice("Вы закрыли [declent_ru(ACCUSATIVE)]."))
```suggestion
		to_chat(user, span_notice("Вы открываете [declent_ru(ACCUSATIVE)]."))
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +	user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] включил [declent_ru(ACCUSATIVE)]."), \
```suggestion
	user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] включает [declent_ru(ACCUSATIVE)]."), \
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +		span_notice("Вы включили [declent_ru(NOMINATIVE)]."), \
```suggestion
		span_notice("Вы включаете [declent_ru(NOMINATIVE)]."), \
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +		span_hear("Вы услышали кухонный комбайн."))
```suggestion
		span_hear("Вы слышите кухонный комбайн."))
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +	visible_message(span_notice(" [declent_ru(NOMINATIVE)] заканчивает обработку."))
```suggestion
	visible_message(span_notice("[capitalize(declent_ru(NOMINATIVE))] заканчивает обработку."))
```

2024-10-10 22:06 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +		processed_slime.balloon_alert_to_viewers("ползет")
```suggestion
		processed_slime.balloon_alert_to_viewers("выползает")
```

2024-10-11 04:24 UTC, msw7007 commented
> В холодильнике комменты были зарезолвены и неизменены, или мне кажется?

Да нет, я по всем замечаниям прохожусь

2024-10-11 07:39 UTC, larentoun requested changes
Кондименты не трогал

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +		balloon_alert_to_viewers("[capitalize(coffeepot.declent_ru(NOMINATIVE))] уже полон!")
наоборот, убрать капиталайз - это же баллун

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/griddle.dm
> +	to_chat(user, span_notice("Вы кладёте содержимое из [storage.parent.declent_ru(ACCUSATIVE)] на [declent_ru(ACCUSATIVE)]."))
```suggestion
	to_chat(user, span_notice("Вы перемещаете содержимое из [storage.parent.declent_ru(ACCUSATIVE)] на [declent_ru(ACCUSATIVE)]."))
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/griddle.dm
> +			visible_message(span_danger("Жарить на [griddled_item.declent_ru(ACCUSATIVE)] - не лучшая идея!"))
```suggestion
			visible_message(span_danger("Жарить на [griddled_item.declent_ru(PREPOSITIONAL)] - не лучшая идея!"))
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		context[SCREENTIP_CONTEXT_LMB] = "[anchored ? "От : "При"]крутить"
```suggestion
		context[SCREENTIP_CONTEXT_LMB] = "[anchored ? "От" : "При"]крутить"
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		context[SCREENTIP_CONTEXT_RMB] = "Начало [vampire_charging_enabled ? "готовки" : "зарядки"]"
```suggestion
		context[SCREENTIP_CONTEXT_RMB] = "Начать [vampire_charging_enabled ? "зарядку" : "готовку"]"
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] заканчивает ремонт, [declent_ru(NOMINATIVE)] снова работает."),
```suggestion
		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] заканчивает ремонтировать, [declent_ru(NOMINATIVE)] снова работает."),
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		span_notice("ВВы начинаете ремонтировать [declent_ru(ACCUSATIVE)]."),
```suggestion
		span_notice("Вы начинаете ремонтировать [declent_ru(ACCUSATIVE)]."),
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/oven.dm
> +		to_chat(user, span_notice("Вы помещаете содержимое [item.declent_ru(ACCUSATIVE)] на [declent_ru(ACCUSATIVE)]..."))
```suggestion
		to_chat(user, span_notice("Вы помещаете содержимое из [item.declent_ru(ACCUSATIVE)] на [declent_ru(ACCUSATIVE)]..."))
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +		visible_message(span_warning("[capitalize(user.declent_ru(NOMINATIVE))] помещает [pushed_mob.name] в [declent_ru(ACCUSATIVE)]!"))
деклент

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +	user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] выбирается из кухонного комбайна!"))
вместо кухонного комбайна деклент объекта лучше

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] начинает ремонтировать  [declent_ru(ACCUSATIVE)]."),
```suggestion
		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] начинает ремонтировать [declent_ru(ACCUSATIVE)]."),
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +		. += span_info("Можно [EXAMINE_HINT("открутить")] от пола.")
```suggestion
		. += span_info("Можно [EXAMINE_HINT("прикрутить")] к полу.")
```

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +						span_notice("Вы перемещаете содержимое [weapon.declent_ru(GENITIVE)] в [declent_ru(ACCUSATIVE)]."))
содержимое из, и падежи поправить

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +				return
лишнее тронуто

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
>  	light_power = 0.5
лишнее тронуто

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +	desc = "Механизм, используемый для сушки растительных продуктов, еды и шкур."
описание перепутал между двумя вещами?

2024-10-11 07:39 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +				examine_list += "&bull; [round(current_reagent.volume, 0.01)] [declension_ru(unknown_volume,"юнит","юнита","юнитов")] [current_reagent.declent_ru(GENITIVE)]"
у реагента нет отдельной поддержки деклентов, он вернет датум - а не имя датума, верни

2024-10-11 07:39 UTC, larentoun commented on code/modules/reagents/chemistry/machinery/reagentgrinder.dm
> +		. += span_notice("Машина может быть [EXAMINE_HINT("вскрыта")].")
разобрана ломом мб лучше?

2024-10-11 14:04 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +		balloon_alert_to_viewers("Нет [coffeepot.declent_ru(NOMINATIVE)] внутри!")
```suggestion
		balloon_alert_to_viewers("нет кофейных зерен!")
		return FALSE
	if(!coffeepot)
		balloon_alert_to_viewers("нет [coffeepot.declent_ru(NOMINATIVE)] внутри!")
```

2024-10-11 14:12 UTC, larentoun requested changes
Почти заканчиваем, остались кондименты

2024-10-11 14:12 UTC, larentoun commented on code/modules/food_and_drinks/machinery/griddle.dm
> +	visible_message(span_notice("[capitalize(exposing_reagent.declent_ru(NOMINATIVE))] начинает жарится на [declent_ru(PREPOSITIONAL)]."))
```suggestion
	visible_message(span_notice("[capitalize(exposing_reagent.declent_ru(NOMINATIVE))] начинает жариться на [declent_ru(PREPOSITIONAL)]."))
```

2024-10-11 14:12 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] заканчивает ремонтировать, [declent_ru(NOMINATIVE)] снова работает."),
```suggestion
		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] заканчивает ремонтировать [declent_ru(ACCUSATIVE)]."),
```

2024-10-11 14:12 UTC, larentoun commented on code/modules/food_and_drinks/machinery/oven.dm
> +		to_chat(user, span_notice("Вы открываете [declent_ru(ACCUSATIVE)]."))
```suggestion
		to_chat(user, span_notice("Вы закрываете [declent_ru(ACCUSATIVE)]."))
```

2024-10-11 14:12 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +			to_chat(user, span_notice("Вы помещаете [loaded] [declension_ru(loaded,"предмет","предмета","предметов")] вставлен в [declent_ru(ACCUSATIVE)].."))
```suggestion
			to_chat(user, span_notice("Вы помещаете [loaded] [declension_ru(loaded,"предмет","предмета","предметов")] в [declent_ru(ACCUSATIVE)]."))
```

2024-10-11 14:12 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +		или <b>[reagents.maximum_volume - reagents.total_volume]</b> юнитов ингредиентов.")
```suggestion
		или <b>[reagents.maximum_volume - reagents.total_volume]</b> юнитов реагентов.")
```

2024-10-11 14:12 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +			examine_list += "&bull; [round(unknown_volume, 0.01)] [declension_ru(unknown_volume,"юнит","юнита","юнитов")] неизвестного ингредиента"
```suggestion
			examine_list += "&bull; [round(unknown_volume, 0.01)] [declension_ru(unknown_volume,"юнит","юнита","юнитов")] неизвестного реагента"
```

2024-10-11 14:38 UTC, larentoun requested changes

2024-10-11 14:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +		. += span_notice("Внутренняя кофемолка содержит [coffee.len] [declension_ru(coffee.len,"порция","порции","порций")] кофейных зерен")
```suggestion
		. += span_notice("Внутренняя кофемолка содержит [coffee.len] [declension_ru(coffee.len,"порцию","порции","порций")] кофейных зерен")
```

2024-10-11 14:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		to_chat(user, span_notice("Вы начиаете перемещать содержимое [tool.declent_ru(GENITIVE)] в [declent_ru(ACCUSATIVE)]..."))
```suggestion
		to_chat(user, span_notice("Вы начинаете перемещать содержимое [tool.declent_ru(GENITIVE)] в [declent_ru(ACCUSATIVE)]..."))
```

2024-10-11 14:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +		span_notice("Вы включаете [declent_ru(NOMINATIVE)]."), \
```suggestion
		span_notice("Вы включаете [declent_ru(ACCUSATIVE)]."), \
```

2024-10-11 14:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +	visible_message(span_notice(" [capitalize(declent_ru(NOMINATIVE))] заканчивает обработку."))
```suggestion
	visible_message(span_notice("[capitalize(declent_ru(NOMINATIVE))] заканчивает обработку."))
```

2024-10-11 14:38 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +			examine_list += "&bull; [round(unknown_volume, 0.01)] [declension_ru(round(unknown_volume, 0.01),"юнит","юнита","юнитов")] неизвестного ингредиента"
```suggestion
			examine_list += "&bull; [round(unknown_volume, 0.01)] [declension_ru(round(unknown_volume, 0.01),"юнит","юнита","юнитов")] неизвестного реагента"
```

2024-10-11 15:22 UTC, larentoun requested changes

2024-10-11 15:22 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +	examine_list += "Внутри вы можете увидеть:"
снизу надо бы перевести `examine_list += "&bull; [ingredient_amounts[ingredient_type]] [initial(ingredient_type.name)]\s"`, используя ru_name_nominitive || name для атома

2024-10-11 20:49 UTC, larentoun requested changes

2024-10-11 20:49 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +			examine_list += "&bull; [ingredient_amounts[ingredient_type]] [initial(ingredient_type.ru_name_nominative) || initial(ingredient_type.name)]\s"
```suggestion
			examine_list += "&bull; [ingredient_amounts[ingredient_type]] единиц[declension_ru(ingredient_amounts[ingredient_type], "у", "ы", "")] [initial(ingredient_type.ru_name_nominative) || initial(ingredient_type.name)]"
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	user.visible_message(span_suicide("[capitalize(user.declent_ru(NOMINATIVE))] пытается проглотить  [declent_ru(GENITIVE)] целиком! Похоже, [ru_p_they()] пытается совершить суицид!"))
```suggestion
	user.visible_message(span_suicide("[capitalize(user.declent_ru(NOMINATIVE))] пытается проглотить [declent_ru(ACCUSATIVE)] целиком! Кажется, [ru_p_they()] забывает, как работает еда!"))
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		M.visible_message(span_warning("[capitalize(user.declent_ru(NOMINATIVE))] кормит [M.declent_ru(ACCUSATIVE)] с помощью[declent_ru(GENITIVE)]."), \
```suggestion
		M.visible_message(span_warning("[capitalize(user.declent_ru(NOMINATIVE))] кормит [M.declent_ru(ACCUSATIVE)] с помощью [declent_ru(GENITIVE)]."), \
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		to_chat(user, span_notice("[capitalize(declent_ru(NOMINATIVE))] наполняет [trans] [declension_ru(trans,"юнитом","юнитами","юнитами")] содержимое [target.declent_ru(GENITIVE)]."))
```suggestion
		to_chat(user, span_notice("[capitalize(declent_ru(NOMINATIVE))] наполняет [declent_ru(ACCUSATIVE)] [trans] [declension_ru(trans,"юнитом","юнитами","юнитами")] из [target.declent_ru(GENITIVE)]."))
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +			to_chat(user, span_warning("В [target.declent_ru(GENITIVE)] пусто!"))
```suggestion
			to_chat(user, span_warning("Внутри [declent_ru(GENITIVE)] пусто!"))
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +			to_chat(user, span_warning("В [declent_ru(DATIVE)] нет места!"))
```suggestion
			to_chat(user, span_warning("Внутри [targent.declent_ru(GENITIVE)] недостаточно места!"))
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	user.visible_message(span_suicide("[capitalize(user.declent_ru(NOMINATIVE))] пытается проглотить  [declent_ru(GENITIVE)] целиком! Похоже, [ru_p_they()] пытается совершить суицид!"))
```suggestion
	user.visible_message(span_suicide("[capitalize(user.declent_ru(NOMINATIVE))] пытается проглотить [declent_ru(GENITIVE)] целиком! Кажется, [ru_p_they()] забывает, как работает еда!"))
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +			examine_list += "&bull; [ingredient_amounts[ingredient_type]] [initial(ingredient_type.ru_name_nominative) || initial(ingredient_type.name)]\s"
```suggestion
			examine_list += "&bull; [ingredient_amounts[ingredient_type]] единиц(declension_ru(ingredient_amounts[ingredient_type], "а", "ы", "")) [initial(ingredient_type.ru_name_nominative) || initial(ingredient_type.name)]"
```

2024-10-11 20:49 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		M.visible_message(span_warning("[capitalize(user.declent_ru(NOMINATIVE))] кормит [M.declent_ru(ACCUSATIVE)] с помощью[declent_ru(GENITIVE)]."), \
```suggestion
		M.visible_message(span_warning("[capitalize(user.declent_ru(NOMINATIVE))] кормит [M.declent_ru(ACCUSATIVE)] с помощью [declent_ru(GENITIVE)]."), \
```

2024-10-12 08:56 UTC, larentoun requested changes

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		to_chat(user, span_notice("Вы наполняете [declent_ru(NOMINATIVE)] на [trans] [declension_ru(trans,"юнит","юнита","юнитов")] из [target.declent_ru(GENITIVE)]."))
```suggestion
		to_chat(user, span_notice("Вы наполняете [declent_ru(ACCUSATIVE)] на [trans] [declension_ru(trans,"юнит","юнита","юнитов")] из [target.declent_ru(GENITIVE)]."))
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	. += span_notice("Требуется [milk_required] [declension_ru(milk_required,"юнит","юнита","юнитов")] молока, [enzyme_required] [declension_ru(enzyme_required,"юнит","юнита","юнитов")] энзима и вы полу
```suggestion
	. += span_notice("[milk_required] [declension_ru(milk_required,"юнит","юнита","юнитов")] молока, [enzyme_required] [declension_ru(enzyme_required,"юнит","юнита","юнитов")] энзима, и вы получите сыр.")
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	. += span_notice("[flour_required] [declension_ru(flour_required,"юнит","юнита","юнитов")] муки, [eggyolk_required] [declension_ru(eggyolk_required,"яйцо","яйца","яиц")] или соевого молока, [sugar_r
желток яичный, не яйцо?

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	. += span_notice("[flour_required] [declension_ru(flour_required,"юнит","юнита","юнитов")] муки, [eggyolk_required] [declension_ru(eggyolk_required,"яйцо","яйца","яиц")] или соевого молока, [sugar_r
не пирог, а тесто для пирога

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	name = "[user.declent_ru(NOMINATIVE)]"
имя меняется в мастер ветке с помощью ru_name_rename()

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	user.visible_message(span_suicide("[capitalize(user.declent_ru(NOMINATIVE))] начинает поглощать содержимое солонки! Кажется, [user.ru_p_they()] пытается совершить самоубийство!"))
не поглощать, а меняться формами

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] посыпает солью [target.declent_ru(ACCUSATIVE)]."), span_notice("Вы посыпаете солью[target.declent_ru(ACCUSATIVE)]."))
```suggestion
		user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] посыпает солью [target.declent_ru(ACCUSATIVE)]."), span_notice("Вы посыпаете солью [target.declent_ru(ACCUSATIVE)]."))
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	. += span_notice("Требуется [milk_required] [declension_ru(milk_required,"юнит","юнита","юнитов")] молока, [enzyme_required] [declension_ru(enzyme_required,"юнит","юнита","юнитов")] энзима и вы полу
```suggestion
	. += span_notice("[milk_required] [declension_ru(milk_required,"юнит","юнита","юнитов")] молока, [enzyme_required] [declension_ru(enzyme_required,"юнит","юнита","юнитов")] энзима, и вы получите сыр.")
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	. += span_warning("Помните, что энзим лишь катализатор, поэтому верните его потом на место!")
```suggestion
	. += span_warning("Помни, что энзим лишь катализатор, поэтому верни его обратно в бутылку после использования, глупыш!")
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	. += span_notice("Требуется [dough_flour_required] [declension_ru(dough_flour_required,"юнит","юнита","юнитов")] муки, [dough_water_required] [declension_ru(dough_water_required,"юнит","юнита","юнит
```suggestion
	. += span_notice("[dough_flour_required] [declension_ru(dough_flour_required,"юнит","юнита","юнитов")] муки, [dough_water_required] [declension_ru(dough_water_required,"юнит","юнита","юнитов")] воды подойдет для обычного кусочка теста. Его можно потом раскатать в плоскую лепешку.")
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	. += span_notice("Нужно [cakebatter_flour_required] [declension_ru(cakebatter_flour_required,"юнит","юнита","юнитов")] муки, [cakebatter_eggyolk_required] [declension_ru(cakebatter_eggyolk_required,
```suggestion
	. += span_notice("[cakebatter_flour_required] [declension_ru(cakebatter_flour_required,"юнит","юнита","юнитов")] муки, [cakebatter_eggyolk_required] [declension_ru(cakebatter_eggyolk_required,"юнит","юнита","юнитов")] яичного желтка (или соевого молока), [cakebatter_sugar_required] [declension_ru(cakebatter_sugar_required,"юнит","юнита","юнитов")] сахара, чтобы сделать слоенное тесто. Из него выйдет отличный пирог!")
```
а вот тут ты правильно написал желток
не пирог, а тесто для пирога

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "соя, божество прозрачное, но все еще питательное!"
```suggestion
	desc = "Соевое молоко. Божество прозрачное, но все еще питательное!"
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "Крупная коробка с кукрзной мукой. Отличный выбор для приготовления южных блюд."
```suggestion
	desc = "Крупная коробка с кукурузной мукой. Отличный выбор для приготовления южных блюд."
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "Салфетки не включены."
```suggestion
	desc = "Салфетки в набор не входят."
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "Вкусное, тянущееся масло в банке."
```suggestion
	desc = "Вкусное, тянущееся арахисовое масло в банке."
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "Фермнтированный легендарный соус с Земли."
```suggestion
	desc = "Ферментированный легендарный соус со Старой Англии. Делает почти всё вкуснее."
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "Выжатые томаты, что скрываются в пластиковой бутылке."
```suggestion
	desc = "Выжатые томаты, что скрываются в пластиковой бутылке. Смутно напоминают Америку."
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "Превосходно подходит для чипсов. Если у вас специфичный вкус."
```suggestion
	desc = "Превосходно подходит для чипсов, если вы сегодня хотите побыть космическим англичанином."
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
>  /obj/item/reagent_containers/condiment/hotsauce
верни строку

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc= "Вы можете чувствовать язву!"
```suggestion
	desc= "Вы можете уже ЧУВСТВОВАТЬ вкус язвы желудка!"
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		/datum/reagent/consumable/ketchup = list("condi_ketchup", "Кетчуп", "Вы уже чувствуете себя более космическим."),
```suggestion
		/datum/reagent/consumable/ketchup = list("condi_ketchup", "Кетчуп", "Вы уже чувствуете себя более по-американски."),
```

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		/datum/reagent/consumable/mayonnaise = list("condi_mayo", "Майонез", "Не является инструментом."),
Скопируй описания с оригиналов

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	//Пакет можно разорвать над едой, чтобы добавить приправы.
коммент не трогай

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		to_chat(user, span_notice("[src.name] открыли, и [target.name] наполняется."))
декленты?

2024-10-12 08:56 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +	desc = "Небольшой пакетик с приправами и он пуст."
```suggestion
	desc = "Небольшой пакетик с приправами, и он пуст."
```

2024-10-12 14:00 UTC, larentoun requested changes

2024-10-12 15:24 UTC, larentoun requested changes
Я точно часть из этого уже ревьювил - и они остались без изменений

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/coffeemaker.dm
> +		balloon_alert_to_viewers("нет [coffeepot.declent_ru(NOMINATIVE)] внутри!")
```suggestion
		balloon_alert_to_viewers("нет [coffeepot.declent_ru(GENITIVE)] внутри!")
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/deep_fryer.dm
> +		playsound(loc, 'sound/machines/ding.ogg', 50, TRUE)
лишнее

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/food_cart.dm
> +		to_chat(user, span_warning("Ваша [unpacked ? "распаковка" :"разборка"] [declent_ru(ACCUSATIVE)] была прервана!"))
```suggestion
		to_chat(user, span_warning("Ваша [unpacked ? "распаковка" :"разборка"] [declent_ru(GENITIVE)] была прервана!"))
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/griddle.dm
> +			visible_message(span_danger("Жарить на [griddled_item.declent_ru(PREPOSITIONAL)] - не лучшая идея!"))
```suggestion
			visible_message(span_danger("Кажется, [griddled_item.declent_ru(NOMINATIVE)] не очень удачно готовится на [declent_ru(PREPOSITIONAL)]!"))
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/icecream_vat.dm
> +	balloon_alert(user, "[reagent_to_remove.declent_ru(NOMINATIVE)] разливается")
```suggestion
	balloon_alert(user, "[reagent_to_remove.name] разливается")
```
это реагент - поддержка отсутствует

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] добавляет [item.declent_ru(ACCUSATIVE)] в [declent_ru(DATIVE)]."), span_notice("Вы добавляете [item.declent_ru(ACCUSATIVE
```suggestion
		user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] добавляет [item.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]."), span_notice("Вы добавляете [item.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]..."))
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/oven.dm
> +		to_chat(user, span_notice("Вы помещаете [item.declent_ru(NOMINATIVE)] в [declent_ru(ACCUSATIVE)]."))
```suggestion
		to_chat(user, span_notice("Вы помещаете [item.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]."))
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +		to_chat(user, span_warning("Внутри [capitalize(declent_ru(NOMINATIVE))] пусто!"))
```suggestion
		to_chat(user, span_warning("Внутри [declent_ru(GENITIVE)] пусто!"))
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +	set name = "Извлечь содержимое"
Все вербы отдельно переведем, убери

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/processor.dm
> +	user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] выбирается из [declent_ru(NOMINATIVE)]!"))
```suggestion
	user.visible_message(span_notice("[capitalize(user.declent_ru(NOMINATIVE))] выбирается из [declent_ru(GENITIVE)]!"))
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +			span_notice("[capitalize(declent_ru(NOMINATIVE))] начинает отваривать [declent_ru(ACCUSATIVE)] от пола."),
```suggestion
			span_notice("[capitalize(user.declent_ru(NOMINATIVE))] начинает отваривать [declent_ru(ACCUSATIVE)] от пола."),
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +
лишняя строка

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +		. += span_info("Машина [EXAMINE_HINT("открутить")] от пола.")
```suggestion
		. += span_info("Машина [EXAMINE_HINT("прикручена")] к полу.")
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +			examine_list += "&bull; [ingredient_amounts[ingredient_type]] единиц[declension_ru(ingredient_amounts[ingredient_type], "у", "ы", "")] [initial(ingredient_type.ru_name_nominative) || initial(ingre
```suggestion
			examine_list += "&bull; [ingredient_amounts[ingredient_type]] единиц[declension_ru(ingredient_amounts[ingredient_type], "у", "ы", "")] [initial(ingredient_type.ru_name_genitive) || initial(ingredient_type.name)]"
```

2024-10-12 15:24 UTC, larentoun commented on code/modules/food_and_drinks/machinery/stove.dm
> +				examine_list += "&bull; [round(current_reagent.volume, 0.01)] [declension_ru(round(unknown_volume, 0.01),"юнит","юнита","юнитов")] [initial(current_reagent.name)]"
```suggestion
				examine_list += "&bull; [round(current_reagent.volume, 0.01)] [declension_ru(round(unknown_volume, 0.01),"юнит","юнита","юнитов")] [current_reagent.name]"
```

2024-10-12 16:02 UTC, larentoun commented on code/modules/food_and_drinks/machinery/microwave.dm
> +		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] начинает ремонтировать [declent_ru(GENITIVE)]."),
```suggestion
		span_notice("[capitalize(user.declent_ru(NOMINATIVE))] начинает ремонтировать [declent_ru(ACCUSATIVE)]."),
```

2024-10-12 16:05 UTC, larentoun commented on code/modules/food_and_drinks/machinery/smartfridge.dm
> +		. += span_info("Машина [EXAMINE_HINT("прикручена")] от пола.")
```suggestion
		. += span_info("Машина [EXAMINE_HINT("прикручена")] к полу.")
```

2024-10-12 16:08 UTC, larentoun commented on code/modules/reagents/reagent_containers/condiment.dm
> +		to_chat(user, span_notice("Вы разорвали [declent_ru(ACCUSATIVE)] над [target.declent_ru(ACCUSATIVE)] и добавляете содержимое в блюдо."))
замени на "вскрываете"

ПАДЕЖИ

2024-10-12 18:15 UTC, merged