NewTranslate
ss220club/Bandastation pull request #57
Opened 2024-04-12 22:50 UTC by AloeNeverDie

## Что этот PR делает

Перевод квирков на русский язык.

## Почему это хорошо для игры

Тем кто не знает английский будут понимать, что за древний эльфиский скрывается в описании черты.

## Тестирование

Выдавал/снимал черты на локалке, вроде все ок было.

## Changelog

:cl:
qol: Переведены черты
/:cl:

2024-04-12 22:54 UTC, Furrior requested changes
Посмотрел первый и последний файл. Остальнеое - лень

2024-04-12 22:54 UTC, Furrior commented on _maps/_basemap.dm
> -//#define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
Увы

2024-04-12 22:54 UTC, Furrior commented on code/datums/quirks/positive_quirks/voracious.dm
> +	lose_text = span_danger("Вы больше не чувствуете себя ЗДОРОВЫМ.")
Не праивльный перевод

2024-04-13 00:08 UTC, AloeNeverDie commented on code/datums/quirks/positive_quirks/voracious.dm
> +	lose_text = span_danger("Вы больше не чувствуете себя ЗДОРОВЫМ.")
Хотел оставить шутку без потери перевода, ну ладно, счастливый меня тоже, поменяем на "ХОЧУ ЖРАААТЬ" Clueless

2024-04-13 15:25 UTC, dj-34 requested changes

2024-04-13 15:25 UTC, dj-34 commented on code/datums/quirks/negative_quirks/addict.dm
> +	medical_record_text = "У пациента есть зависимость к чему-то, но он отказывается говорить к чему конкретно.."
```suggestion
	medical_record_text = "У пациента есть зависимость к чему-то, но он отказывается говорить к чему конкретно."
```

2024-04-13 19:05 UTC, larentoun requested changes

2024-04-13 19:05 UTC, larentoun commented on code/datums/quirks/positive_quirks/spacer.dm
> +			Вы получаете 25% надбавку за работу в опасных условиях в связи с тем, что [on_a_planet ?  "station" : "occupational"] assignment."))
```suggestion
			Вы получаете 25% надбавку за работу в опасных условиях в связи с [on_a_planet ?  "станционной" : "профессиональной"] деятельностью."))
```

2024-04-13 19:05 UTC, larentoun commented on code/datums/quirks/positive_quirks/spacer.dm
> +		to_chat(quirk_holder, span_info("Благодаря [isnull(spacer_account) ? " " : " also "] были выданы противорвотные пластыри, чтобы помочь адаптироваться к планетарной гравитации."))
```suggestion
		to_chat(quirk_holder, span_info("Вам [isnull(spacer_account) ? " " : " также "] были выданы противорвотные пластыри, чтобы помочь адаптироваться к планетарной гравитации."))
```

2024-04-13 19:05 UTC, larentoun commented on code/datums/quirks/positive_quirks/throwing_arm.dm
> +	desc = "У вас очень сильные руки! Предметы, которые вы бросаете, всегда летят дальше, чем все остальные, и вы никогда не промахиваетесь при броске."
```suggestion
	desc = "У вас очень сильные руки! Предметы, которые вы бросаете, всегда летят дальше остальных, и вы никогда не промахиваетесь при броске."
```

2024-04-13 19:45 UTC, larentoun requested changes

2024-04-13 19:45 UTC, larentoun commented on code/datums/quirks/negative_quirks/big_hands.dm
> +	desc = "У вас большие руки, это, конечно, затрудняет использование многих вещей.."
```suggestion
	desc = "У вас большие руки, и это затрудняет использование многих вещей."
```

2024-04-13 19:45 UTC, larentoun commented on code/datums/quirks/negative_quirks/hypersensitive.dm
> +	desc = "К лучшему или худшему, вам кажется, что все влияет на ваше настроение больше, чем должно."
```suggestion
	desc = "К лучшему или худшему, вам кажется, что всё влияет на ваше настроение сильнее обычного."
```

2024-04-13 19:45 UTC, larentoun commented on code/datums/quirks/neutral_quirks/transhumanist.dm
> +	desc = "Вы считаете синтетическую форму жизни идеальной и презираете органическую плоть. Вы расстраиваетесь, когда рядом с вами органические формы жизни и нет никого хоть как-то смахивающего на кибо
```suggestion
	desc = "Вы считаете синтетическую форму жизни идеальной и презираете органическую плоть. Вы расстраиваетесь, когда рядом с вами органические формы жизни и нет никого хоть как-то смахивающего на киборга. Вы стремитесь заменить свои мясистые конечности на их хромированные аналоги. Вы начинаете с роботизированной конечностью."
```

2024-04-13 21:54 UTC, Fullonibus requested changes
тяжело...

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/negative_quirks/unusual.dm
> +	desc = "Вы очень чувствительны и должны прикоснуться к чему-то, чтобы изучить это."
"... тактильно чувствительны и..." ?

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/neutral_quirks/bald.dm
> +	desc = "У вас нет волос, и вы не чувствуете себя уверенно из-за этого! Не снимайте парик или хотя бы прикрывайте голову."
"не чувствуете себя уверенно" на "чувствуете себя  неуверенно"

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/neutral_quirks/monochromatic.dm
> +	medical_record_text = "Пациент страдает почти полной дальтонизмом."
полным

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/neutral_quirks/no_taste.dm
> +	desc = "Вы не сможете ничего попробовать! Токсичная пища все равно настигнет вас."
"...попробовать на вкус". Настигнет слегка туманно, лучше "Токсичная пища всё еще может отравить вас"

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/neutral_quirks/snob.dm
> +	desc = "Вы заботитесь о тонкостях, и если комната выглядит некрасиво, она того не стоит, не так ли?"
кажется, дословно не перевести, предлагаю так: "У вас утончённый вкус, и если..."

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/neutral_quirks/snob.dm
> +	gain_text = span_notice("Вы ощущаете, что прекрасно понимаете, как должны выглядеть окружение вокруг вас.")
должно выглядеть.

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/neutral_quirks/transhumanist.dm
> +	desc = "Вы считаете синтетическую форму жизни идеальной и презираете органическую плоть. Вы расстраиваетесь, когда рядом с вами органические формы жизни и нет никого хоть как-то смахивающего на кибо
Вы начинаете с роботизированной конечностью.

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/positive_quirks/apathetic.dm
> +	desc = "В целом вам все-равно на все, в отличии от других людей. В таком месте, как это, довольно спокойно."
"В целом вам все-равно на все, в отличии от других людей. Тут прикольно... наверное..."

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/positive_quirks/skittish.dm
> +	medical_record_text = "Пациент демонстрирует сильное отторжение к опасности и рассказывает, что прятался в контейнерах от страха."
"Пациент демонстрирует крайне сильное стремление избежать опасности и рассказывает как прятался в контейнерах от страха."

2024-04-13 21:54 UTC, Fullonibus commented on code/datums/quirks/positive_quirks/tagger.dm
> +	medical_record_text = "Пациент недавно был замечен в связи с возможным инцидентом, связанным с использованием краски."
Пациент недавно был замечен в связи с возможным инцидентом ненадлежащего использования краски/распыления краски

2024-04-13 22:09 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/addict.dm
> +	medical_record_text = "Пациент употребляет тяжелые наркотики."
В целом не вижу тут особой проблемы, но "У пациента есть период употребления тяжёлых наркотиков" звучит ещё хуже, как по мне, если есть идея лучше - можно поменять.

2024-04-13 22:17 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/brain_problems.dm
> +	lose_text = span_notice("Вы снова чувствуете себя изнеможденно.")
Тут в целом сложно придумать т.к. нормально это не перевести на русский.
Текст получения - в целом можно взять
Текст потери - не уверен, но если чего-то лучше не найдется можно поменять на твой вариант.

2024-04-13 22:19 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/glass_jaw.dm
> +	gain_text = span_danger("Ваша челюсть кажется ослабленной.")
по сути синоним, можно заменить, но хотелось бы ещё подумать, может что лучше придумается

2024-04-13 22:24 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/light_drinker.dm
> +	desc = "Вы просто не умеете обращаться с напитками и очень быстро пьянеете."
Как идея можно поменять на "Вы не можете осилить много алкоголя и быстро пьянеете."

2024-04-13 22:25 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/photophobia.dm
> +	desc = "Кажется, что яркий свет беспокоит вас больше всего. Возможно, это следствие какой-либо болезни."
Возьмем второй вариант

2024-04-13 22:29 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/nearsighted.dm
> +	desc = "У вас близорукость, но зато с парой очков выписанных по рецепту."
как по мне "вы" лишние будет

2024-04-13 22:32 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/pushover.dm
> +	desc = "Ваше мышление заключается в том, чтобы всегда позволять людям манипулировать вами и делать из вас ведомого. Сопротивление из захвата потребует особых усилий."
Как вариант: "Вы довольно податливы, что позволяет людям легче манипулировать и командовать вами...

2024-04-14 00:20 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/family_heirloom.dm
> +		to_chat(quirk_holder, span_boldnotice("Волна экзистенциального ужаса накатывает на вас, когда вы осознаете, что пропала ваша драгоценная семейная реликвия. Может быть, боги смилостивятся над вашей
Думаю можно переделать как "... окутывает ...", если никто не против.

2024-04-14 00:22 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/addict.dm
> +	gain_text = span_danger("Вам бы сейчас не помешало покурить.")
Не уверен, что так будет лучше, могу предложить: "Вы бы сейчас не отказались от сигареты"

2024-04-14 00:23 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/bad_back.dm
> +	desc = "Из-за плохой осанки рюкзаки и другие сумки никогда не сидят на спине правильно. Более равномерно взвешенные предметы вполне подойдут, скорее всего."
Как будто старый вариант лучше, нужно мнение ещё кого-нибудь

2024-04-14 11:44 UTC, larentoun commented on code/datums/quirks/negative_quirks/addict.dm
> +	gain_text = span_danger("Вам бы сейчас не помешало покурить.")
Можно более свободно, "Эх, вот бы сейчас закурить" попробовать

2024-04-14 11:45 UTC, larentoun commented on code/datums/quirks/negative_quirks/bad_back.dm
> +	desc = "Из-за плохой осанки рюкзаки и другие сумки никогда не сидят на спине правильно. Более равномерно взвешенные предметы вполне подойдут, скорее всего."
Нравится саггестион

2024-04-14 11:51 UTC, larentoun requested changes

2024-04-14 11:51 UTC, larentoun commented on code/datums/quirks/negative_quirks/blood_deficiency.dm
> +	gain_text = span_danger("Вы чувствуете как силы покидают вас.")
```suggestion
	gain_text = span_danger("Вы чувствуете, как силы покидают вас.")
```

2024-04-14 11:51 UTC, larentoun commented on code/datums/quirks/negative_quirks/claustrophobia.dm
> +			to_chat(quirk_holder, span_warning("Санта Клаус здесь! Я должен выбираться отсюда!"))
Можно попробовать с Дед Морозом, для более отечественного пользователя? Хызы, просто как идея

2024-04-14 11:51 UTC, larentoun commented on code/datums/quirks/negative_quirks/hemiplegic.dm
> +	desc = "Половина вашего тела не работает. Ничто и никогда это не исправит."
Нравится саггестион

2024-04-14 11:51 UTC, larentoun commented on code/datums/quirks/negative_quirks/photophobia.dm
> +	desc = "Кажется, что яркий свет беспокоит вас больше чем любой другой. Возможно, это следствие какой-либо болезни."
```suggestion
	desc = "Кажется, что яркий свет беспокоит вас больше остальных. Возможно, это следствие какой-либо болезни."
```

2024-04-14 11:51 UTC, larentoun commented on code/modules/reagents/withdrawal/_addiction.dm
> +	victim_mind.current.log_message("стал зависимым к [name].", LOG_GAME)
логи не стоит переводить

2024-04-14 22:04 UTC, larentoun approved these changes
И так сойдет

2024-04-14 22:04 UTC, larentoun commented on _maps/_basemap.dm
> +// #define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
Погоди, верни как было емае
```suggestion
//#define LOWMEMORYMODE //uncomment this to load centcom and runtime station and thats it.
```

2024-04-15 14:26 UTC, AloeNeverDie commented on code/datums/quirks/positive_quirks/tagger.dm
> +	medical_record_text = "Пациент недавно был замечен в связи с возможным инцидентом ненадлежащего распыления краски."
не нравится данный вариант

2024-04-15 14:32 UTC, AloeNeverDie commented on code/datums/quirks/negative_quirks/insanity.dm
> +		Токсин Mindbreaker может подавить воздействие этого вещества, и у вас появится иммунитет к галлюциногенным свойствам Mindbreaker. \
данный вариант не сильно нравится, но переделаю как "Токсин Mindbreaker может подавлять воздействие этого вещества, и у вас появится иммунитет к галлюциногенным свойствам Mindbreaker"

2024-04-15 15:15 UTC, AloeNeverDie commented on code/datums/quirks/positive_quirks/light_step.dm
> +	desc = "Вы ходите мягким шагом; шаги и наступание на острые предметы будут тише и менее болезненными. Кроме того, вы не испачкаете руки и одежду, если наступите в кровь."
нет

2024-04-15 15:19 UTC, AloeNeverDie commented on code/datums/quirks/positive_quirks/light_step.dm
> +	medical_record_text = "Ловкость пациента скрывает сильную способность к скрытности."
не нравится, переделаю на "отражает"

2024-04-15 17:32 UTC, larentoun commented on code/datums/quirks/negative_quirks/insanity.dm
> +		Токсин Mindbreaker может подавлять воздействие этого вещества, и у вас появится иммунитет к галлюциногенным свойствам Mindbreake. \
```suggestion
		Токсин Mindbreaker может подавлять воздействие этого вещества, и у вас появится иммунитет к галлюциногенным свойствам Mindbreaker. \
```

2024-04-15 17:36 UTC, Furrior approved these changes
Мне лень смотреть

2024-04-15 17:36 UTC, merged