Капсулы криосна
ss220club/BandaStation pull request #635
Opened 2024-11-01 22:13 UTC by RosSample

## About The Pull Request

Порт капсул криосна с Nova Sector. <s>:catDespair:</s>

## Why It's Good For The Game

Освобождает слоты на командные роли и ИИ при их криосонировании (тело ССДшника можно отнести в крио через 30 минут после выхода) и дает муд бафф, если отвести спессменчика в спать в криокроватку.

## Changelog

:cl:
add: капсулы криосна
map: комнаты для капсул через автомаппер
/:cl:

2024-11-02 08:56 UTC, dj-34 commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			radio.talk_into(src, "[user][rank ? ", [rank]" : ""] был перемещён в криогенное хранилище.", announcement_channel)
Нужны декленты, шоб был(-а/-о) перемещен(-а/-о). Как там это правильно делать лучше уточнить у Ларентауна.

2024-11-02 08:56 UTC, dj-34 commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			radio.talk_into(src, "[user][rank ? ", [rank]" : ""] has woken up from cryo storage.", announcement_channel)
Не переведено

2024-11-02 08:56 UTC, dj-34 commented on modular_bandastation/cryosleep/code/cryopod.dm
> +				to_chat(objective.owner.current, "<BR>[span_userdanger("You get the feeling your target is no longer within reach. Time for Plan [pick("A","B","C","D","X","Y","Z")]. Objectives updated!")]")
ту чат бы перевести

2024-11-02 08:56 UTC, dj-34 commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		if(tgui_alert(user, "Would you like to place [target] into [src]?", "Place into Cryopod?", list("Yes", "No")) != "No")
перевод

2024-11-02 08:56 UTC, dj-34 commented on modular_bandastation/cryosleep/code/mood.dm
> +	description = "I feel better having tucked someone in for a good night's rest!"
перевод

2024-11-02 08:56 UTC, dj-34 commented on modular_bandastation/cryosleep/code/admin.dm
> +		cryo_paper.add_raw_text("Приносим искренние извинения, персону \"[name][job ? ", [job]," : ""]\" пришлось отправить в криогенное хранилище по причинам, которые на данный момент не могут быть уточне
```suggestion
		cryo_paper.add_raw_text("Приносим искренние извинения, персону \"[name][job ? ", [job]," : ""]\" пришлось отправить в криогенное хранилище по причинам, которые на данный момент не могут быть уточнены.<br><br>С уважением,<br><i>Агентство Нанотрейзен по борьбе с SSD.</i>")
```

2024-11-11 09:57 UTC, larentoun requested changes
Пока поверхностно пробежался, еще вернусь к основному файлу.
Вопрос - удаляет ли из манифеста, когда уходят в крио? Нужно.

2024-11-11 09:57 UTC, larentoun commented on modular_bandastation/cryosleep/code/admin.dm
> +			break
```suggestion
	for(var/obj/machinery/cryopod/cryo in GLOB.valid_cryopods)
		if(cryo.occupant || !cryo.state_open || cryo.panel_open) //free, opened, and panel closed?
			return
		if(buckled)
			buckled.unbuckle_mob(src, TRUE)
		if(buckled_mobs)
			for(var/mob/buckled_mob in buckled_mobs)
				unbuckle_mob(buckled_mob)
		cryo.close_machine(src) //put player
		break
```

2024-11-11 09:57 UTC, larentoun commented on modular_bandastation/cryosleep/code/ai.dm
> +		return
```suggestion
```

2024-11-11 09:57 UTC, larentoun commented on modular_bandastation/cryosleep/code/mood.dm
> +	description = "Я чувствую себя лучше, уложив [tuckee.name] отдохнуть на ночь!"
деклент

2024-11-11 11:24 UTC, larentoun requested changes

2024-11-11 11:24 UTC, larentoun commented on _maps/bandastation/automapper/automapper_config.toml
> +# Metastation Cryo
Добавь еще на норстар, кажется, когда-нибудь на ней поиграем

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			radio.talk_into(src, "[user][rank ? ", [rank]" : ""] [genderize_ru(occupant_gender, "пробудился", "пробудилась", "пробудилось", "пробудились")] из криогенного хранилища.", announcement_channel)
```suggestion
			radio.talk_into(src, "[user][rank ? ", [rank]" : ""] пробудил[genderize_ru(occupant_gender, "ся", "ась", "ось", "ись")] из криогенного хранилища.", announcement_channel)
```

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +						radio.talk_into(src, "[user][rank ? ", [rank]" : ""] [genderize_ru(occupant_gender, "был", "была", "было", "были")] [genderize_ru(occupant_gender, "перемещён", "перемещена", "перемещено", "пере
```suggestion
						radio.talk_into(src, "[user][rank ? ", [rank]" : ""] был[genderize_ru(occupant_gender, "", "а", "о", "и")] перемещ[genderize_ru(occupant_gender, "ён", "ена", "ено", "ены")] в криогенное хранилище.", RADIO_CHANNEL_COMMAND)
```

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			radio.talk_into(src, "[user][rank ? ", [rank]" : ""] [genderize_ru(occupant_gender, "был", "была", "было", "были")] [genderize_ru(occupant_gender, "перемещён", "перемещена", "перемещено", "перемещ
тут тоже так же сделай, как выше

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		if(mob_occupant && mob_occupant.stat != DEAD)
```suggestion
		if(mob_occupant?.stat != DEAD)
```

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		..(target)
```suggestion
		. = ..(target)
```

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		if(mob_occupant && mob_occupant.stat != DEAD)
А проверка не нужна, что это точно ливинг? isliving()

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	..()
```suggestion
	. = ..()
```

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		span_notice("Вы вылезаете из [src]!"))
декленты

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	var/mob/living/mob_occupant = occupant
нет проверки, что это ливинг

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	var/mob/living/mob_occupant = occupant
нет проверки на ливинга

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +				mind.announce_objectives()
Вместо елс-иф можно использовать ранний ретурн, поправь тут в этом проке это

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	var/mob/living/mob_occupant = occupant
проверка на ливинга

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +				break
В раунде не обновился плексагон (крю манифест), перепроверь прок.

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	visible_message(span_notice("[src] гудит и шипит, перемещая [mob_occupant.real_name] в хранилище."))
декленты

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		to_chat(user, span_notice("[src] уже занята!"))
деклент

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			to_chat(user, span_danger("Вы помещаете [target] в [src]."))
деклент

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +					to_chat(user, span_notice("Вы не можете поместить [target] в [src] ещё [round(((ssd_time - (world.time - target.lastclienttime)) / (1 MINUTES)), 1)] минут."))
Ладно, много текста, понимаешь - везде вставляй декленты там, где игрок получает информацию. НЕ ЛОГИ.

2024-11-11 11:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	density = FALSE
А в перму везде добавил?

2024-11-11 14:05 UTC, RosSample commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		if(mob_occupant && mob_occupant.stat != DEAD)
![image](https://github.com/user-attachments/assets/37d4ce77-ed0b-473b-a1be-d4c490acd523)

2024-11-13 00:20 UTC, dj-34 approved these changes
Апрув карт

2024-11-27 12:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/admin.dm
> +	playsound(loc, 'sound/effects/magic/Repulse.ogg', 100, 1)
```suggestion
	playsound(loc, 'sound/effects/magic/Repulse.ogg', 50, TRUE)
```

2024-11-27 12:24 UTC, larentoun commented on modular_bandastation/cryosleep/code/admin.dm
> +/mob/proc/send_to_cryo(with_paper = FALSE)
Почему тут не только ливинги? Призраков и глаза тоже допускаем?

2024-11-27 12:25 UTC, larentoun commented on modular_bandastation/cryosleep/code/admin.dm
> +/mob/proc/send_to_cryo(with_paper = FALSE)
```suggestion
/mob/living/proc/send_to_cryo(with_paper = FALSE)
```

2024-11-27 12:25 UTC, larentoun commented on modular_bandastation/cryosleep/code/admin.dm
> +	sparks.set_up(10, 1, loc)
```suggestion
	sparks.set_up(10, TRUE, loc)
```

2024-11-27 12:26 UTC, larentoun commented on modular_bandastation/cryosleep/code/admin.dm
> +	sparks.attach(loc)
```suggestion
```

2024-11-27 12:27 UTC, larentoun commented on modular_bandastation/cryosleep/code/admin.dm
> +	for(var/obj/machinery/cryopod/cryo in GLOB.valid_cryopods)
А если нету криопода? Или такого быть не может? Не следует ли сделать проверку до анимки телепорта и писмьма?

2024-11-27 12:28 UTC, larentoun commented on modular_bandastation/cryosleep/code/ai.dm
> +		src.ghostize(FALSE)
убери тут везде уточнение `src.`

2024-11-27 12:29 UTC, larentoun commented on modular_bandastation/cryosleep/code/mood.dm
> +/datum/mood_event/tucked_in/add_effects(mob/tuckee)
```suggestion
/datum/mood_event/tucked_in/add_effects(mob/living/tuckee)
```

2024-11-27 12:31 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	visible_message(span_notice("[occupant] вылезает из [declent_ru(GENITIVE)]!"),
для оккупанта деклент

2024-11-27 12:33 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	if(!occupant)
```suggestion
	if(!isliving(occupant))
```

2024-11-27 12:34 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	if(!occupant)
Для кого ревью делаю... Для себя? Я ведь попросил проверки на ливинга поставить.
```suggestion
	if(!isliving(occupant))
```

2024-11-27 12:34 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +				return
В чём тут логика? Мы уже обращаемся к `objective`, значит он не может быть нуллом?

2024-11-27 12:35 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +				var/list/objectivestoupdate
```suggestion
				var/list/objectives_to_update
```

2024-11-27 12:35 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	if(!occupant)
```suggestion
	if(!isliving(occupant))
```

2024-11-27 12:36 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		if (issilicon(mob_occupant) && istype(item_content, /obj/item/mmi))
```suggestion
		if(issilicon(mob_occupant) && istype(item_content, /obj/item/mmi))
```

2024-11-27 12:37 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		if(tgui_alert(user, "Хотите помесить [target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]?", "Поместить в [declent_ru(ACCUSATIVE)]?", list("Да", "Нет")) != "Нет")
```suggestion
		if(tgui_alert(user, "Хотите помесить [target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]?", "Поместить в [declent_ru(ACCUSATIVE)]?", list("Да", "Нет")) == "Да")
```

2024-11-27 12:38 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			name = "[name] ([target.name])"
```suggestion
			ru_names_rename(ru_names_toml(src::name, suffix = " ([target.declent_ru(NOMINATIVE)])", override = "[name] ([target.name])"))
			name = "[name] ([target.name])"
```

2024-11-27 12:39 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		else
можно ли тут ранними ретурнами избавиться от елс иф бесконечных?

2024-11-27 12:39 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +					name = "[name] ([target.name])"
ru_name_rename

2024-11-27 12:40 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			to_chat(user, span_danger("Вы не можете поместить [target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]. [target.ru_p_they(TRUE, target.gender)] в сознании."))
```suggestion
			to_chat(user, span_danger("Вы не можете поместить [target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]. [target.ru_p_they(TRUE)] в сознании."))
```

2024-11-27 12:40 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	if(target == user && (tgui_alert(target, "Войти в криохранилище?", "Войти в криокапсулу?", list("Да", "Нет")) != "Да"))
```suggestion
	if(target == user && (tgui_alert(target, "Войти в криохранилище?", "Войти в криокапсулу?", list("Да", "Нет")) == "Нет"))
```

2024-11-27 12:41 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +			tgui_alert(target, "Вы [antag.declent_ru(NOMINATIVE)]! Уверены что хотите покинуть раунд?")
У датума антагониста нет поддержки деклентов
```suggestion
			tgui_alert(target, "Вы [antag.name]! Уверены что хотите покинуть раунд?")
```

2024-11-27 12:42 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		visible_message(span_infoplain("[user.declent_ru(NOMINATIVE)] помещает [target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)]."))
капитазайлы в начале предложения

2024-12-07 16:53 UTC, larentoun commented on modular_bandastation/extra_vv/code/extra_vv.dm
> +/mob/vv_get_dropdown()
Почему это не у ливингов, опять же?
Кто-то возьмет да и призрака отправит в крио, что делать будем?

2024-12-07 18:26 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +				visible_message("[capitalize(declent_ru(NOMINATIVE))] выдаёт [item].")
айтем декленти

2024-12-07 18:27 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		if("CRYO_LEAVE")
CRYO_JOIN и CRYO_LEAVE в дефайны (можно в этом же файле и потом андефайнуть в нём же)

2024-12-07 18:27 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +						radio.talk_into(src, "[user][rank ? ", [rank]," : ""] был[genderize_ru(occupant_gender, "", "а", "о", "и")] перемещ[genderize_ru(occupant_gender, "ён", "ена", "ено", "ены")] в криогенное хранил
```suggestion
			if(occupant_job_radio)
				if(occupant_departments_bitflags & DEPARTMENT_BITFLAG_COMMAND)
					if(occupant_job_radio != RADIO_CHANNEL_COMMAND)
						radio.talk_into(src, "[user][rank ? ", [rank]," : ""] был[genderize_ru(occupant_gender, "", "а", "о", "и")] перемещ[genderize_ru(occupant_gender, "ён", "ена", "ено", "ены")] в криогенное хранилище.", RADIO_CHANNEL_COMMAND)
```

2024-12-07 18:27 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	name = "cryogenic freezer"
ru_names.toml перевод просит

2024-12-07 18:27 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	desc = "Suited for Cyborgs and Humanoids, the pod is a safe place for personnel affected by the Space Sleep Disorder to get some rest."
перевод

2024-12-07 18:28 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +/obj/machinery/cryopod
в идеале раздели на несколько файлов - криопод в одной, консоль в другой

2024-12-07 18:31 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +	name = "[name] ([target.name])"
и где же рунеймс ренейм?

2024-12-07 18:32 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +		to_chat(user, span_notice("[capitalize(declent_ru(NOMINATIVE))] занята!"))
женский род?

2024-12-07 18:32 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +/obj/machinery/cryopod/attackby(obj/item/weapon, mob/living/carbon/human/user, params)
используй новомодное `item_interaction()`

2024-12-07 18:33 UTC, larentoun commented on modular_bandastation/cryosleep/code/cryopod.dm
> +/mob/living
это тожде в отдельный файл

2025-01-13 16:34 UTC, merged