Перевод всяких штук у тритора
ss220club/Bandastation pull request #68
Opened 2024-04-14 13:09 UTC by Ingakem

## About The Pull Request
Перевод 

## Why It's Good For The Game
Да

## Changelog
Перевел чето там

2024-04-14 13:10 UTC, Furrior commented on code/modules/antagonists/traitor/contractor/contract_teammate.dm
> +	generic_objective.name = "Следуйте приказам контрактора"
Так контрактор или контрактник?

2024-04-14 13:13 UTC, Ingakem commented on code/modules/antagonists/traitor/contractor/contract_teammate.dm
> +	generic_objective.name = "Следуйте приказам контрактора"
Вобля...

2024-04-14 13:13 UTC, Ingakem commented on code/modules/antagonists/traitor/contractor/contract_teammate.dm
> +	generic_objective.name = "Следуйте приказам контрактора"
Подрядчик

2024-04-14 14:23 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contract_teammate.dm
> +	generic_objective.name = "Следуйте приказам Контрактника"
```suggestion
	generic_objective.name = "Следуйте приказам контрактника"
```
Контрактник это не имя собственное. Предатель, ведь, не пишем с заглавной?

2024-04-14 14:24 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contractor_items.dm
> +		от обычного Скафандра Синдиката доступного в вашем аплинке. Мы также предоставляем вам костюм и маску хамелеон, которые оба могут быть изменены\
```suggestion
		от обычного скафандра Синдиката доступного в вашем аплинке. Мы также предоставляем вам костюм и маску хамелеон, которые оба могут быть изменены\
```

2024-04-14 14:24 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contractor_items.dm
> +		<p>Выданная вам дубинка бьет сильнее чем та, к который вы привыкли и скорее всего будет вашим лучшим оружием для похищения ваших \
```suggestion
		<p>Выданная вам дубинка бьет сильнее чем та, к который вы привыкли, и, скорее всего, будет вашим лучшим оружием для похищения ваших \
```

2024-04-14 14:25 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contractor_items.dm
> +		целей. Три дополнительных предмета которые имелись у нас в наличии были случайно выбраны и выданы вам. Мы надеемся они будут полезны для вашей работы.</p>\
```suggestion
		целей. Три дополнительных предмета, которые имелись у нас в наличии, были случайно выбраны и выданы вам. Мы надеемся, что они будут полезны для вашей работы.</p>\
```

2024-04-14 14:25 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contractor_items.dm
> +		<p>Магазин контрактора, находится в правом верхнем угле аплинка, он предоставит вам уникальные предметы и возможности. Они могут быть куплены за контракторскую репутацию,\
```suggestion
		<p>Магазин контрактника, находящийся в правом верхнем угле аплинка, предоставит вам уникальные предметы и возможности. Они могут быть куплены за репутацию контрактника,\
```

2024-04-14 14:27 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contractor_items.dm
> +			<li>чтобы выполнять контракт вам нужно принести цель до назначенного места высадки, вызвать под отправки и положить\
```suggestion
			<li>Чтобы выполнить контракт, вам нужно принести цель до назначенного места высадки, вызвать под отправки и положить\
```

2024-04-14 14:27 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contractor_items.dm
> +		<p>Будьте осторожны принимая контракт. Хотя вы сможете видеть местоположение точки высадки, отмена контракта сделает\
```suggestion
		<p>Будьте осторожны принимая контракт. Хоть вы и сможете видеть местоположение точки высадки, отмена контракта сделает\
```

2024-04-14 14:28 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/contractor_items.dm
> +			<li>схватите свою цель и поместите ее в под.</li>\
```suggestion
			<li>Схватите свою цель и поместите ее в под.</li>\
```

2024-04-14 14:29 UTC, larentoun commented on code/modules/antagonists/traitor/contractor/syndicate_contract.dm
> +			to_chat(victim, span_warning("это капсула, что-то сделала с вами..."))
```suggestion
			to_chat(victim, span_warning("Эта капсула что-то сделала с вами..."))
```

2024-04-14 14:30 UTC, larentoun commented on code/modules/antagonists/traitor/objectives/final_objective/infect_ai.dm
> +				to_chat(user, span_warning("Вы должны быть в [initial(board_area_pickup.name)] чтобы получить зараженную плату загрузки законов."))
```suggestion
				to_chat(user, span_warning("Вы должны быть в [initial(board_area_pickup.name)], чтобы получить зараженную плату загрузки законов."))
```

2024-04-14 14:31 UTC, larentoun commented on code/modules/antagonists/traitor/objectives/locate_weakpoint.dm
> +	user.visible_message(span_danger("[user] нажимает несколько кнопок на [src] и он начинает зловеще пищать!"), span_notice("Вы активируете [src] и начинаете сканировать местность. Не выходите [get_are
```suggestion
	user.visible_message(span_danger("[user] нажимает несколько кнопок на [src], и предмет начинает зловеще пищать!"), span_notice("Вы активируете [src] и начинаете сканировать местность. Не выходите [get_area_name(user, TRUE)], пока сканирование не завершится!"))
```

2024-04-14 14:32 UTC, larentoun commented on code/modules/antagonists/traitor/objectives/locate_weakpoint.dm
> +	var/alertstr = span_userdanger("Сетевое оповещение: обнаружена попытка анализирование сети станции. [user_area?" in [get_area_name(user, TRUE)]":". Невозможно определить местоположение"].")
```suggestion
	var/alertstr = span_userdanger("Сетевое оповещение: обнаружена попытка анализирование сети станции[user_area?" в [get_area_name(user, TRUE)]":". Невозможно определить местоположение"].")
```

2024-04-14 14:34 UTC, larentoun commented on code/modules/antagonists/traitor/objectives/sleeper_protocol.dm
> +		"Они положили что-то в твою еду чтобы ты забыл.",
```suggestion
		"Они подложили что-то в твою еду, чтобы ты забыл.",
```

2024-04-14 14:34 UTC, larentoun commented on code/modules/antagonists/traitor/objectives/sleeper_protocol.dm
> +		"Ваша сумка кажется легче? Могу поспорить, что те ребята из службы безопасности что-то оттуда украли. Иди и верни это!.",
```suggestion
		"Ваша сумка кажется легче? Могу поспорить, что те ребята из службы безопасности что-то оттуда украли. Иди и верни это!",
```

2024-04-14 14:40 UTC, larentoun commented
Ыа-ыа, если ты еще в процессе, сделай драфт, чтобы всё одним скопом проверить :madge:

2024-04-14 14:41 UTC, Ingakem commented
Вот би тебя послать..

2024-04-16 16:14 UTC, larentoun requested changes

2024-04-16 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/SyndicateContractor.tsx
>            Contractor Status
А это чего не переведено?

2024-04-16 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/SyndicateContractor.tsx
> +            <LabeledList.Item label="Текущий статус">ACTIVE</LabeledList.Item>
Тут тоже не переведено?

2024-04-16 16:14 UTC, larentoun commented on tgui/packages/tgui/interfaces/SyndicateContractor.tsx
> +                  : 'Неверная Цель'
```suggestion
                  : 'Неверная цель'
```

2024-04-16 16:15 UTC, larentoun commented
Определись там, как переводится `pod` у контрактника. Где-то под, там челнок, там капсула. Попытался под "под" всё подогнать

2024-04-16 19:25 UTC, larentoun requested changes

2024-04-16 19:25 UTC, larentoun commented on code/game/gamemodes/objective.dm
> +	team_explanation_text = "Угоните аварийный шаттл, взломав его навигационные протоколы через консоль управления (Alt-Клик по консоли аварийного шаттла). Все члены вашей команды должны выжить."
```suggestion
	team_explanation_text = "Угоните эвакуационный шаттл, взломав его навигационные протоколы через консоль управления (Alt-Клик по консоли эвакуационного шаттла). Все члены вашей команды должны выжить."
```

2024-04-16 19:25 UTC, larentoun commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Угоните эвакуационный шаттл, взломав его навигационные протоколы через консоль управления (Alt-Клик по консоли аварийного шаттла)."
```suggestion
	explanation_text = "Угоните эвакуационный шаттл, взломав его навигационные протоколы через консоль управления (Alt-Клик по консоли эвакуационного шаттла)."
```

2024-04-16 19:25 UTC, larentoun commented on tgui/packages/tgui/interfaces/SyndicateContractor.tsx
> +    'как их знания будут извлечены,  и вам будет предоставлена',
```suggestion
    'как их знания будут извлечены, и вам будет предоставлена',
```

2024-04-16 19:25 UTC, larentoun commented on code/modules/uplink/uplink_items/contractor.dm
> +		оплату и места для транспортировкидля ваших текущих доступных контрактов."
```suggestion
		оплату и места для транспортировки для ваших текущих доступных контрактов."
```

2024-04-16 19:25 UTC, larentoun commented on code/modules/antagonists/traitor/objectives/final_objective/objective_dark_matteor.dm
> +		в установке их в космосе рядом со станцией и перекалибровки их с помощью предоставленного Емага.  Будьте осторожны: вам нужно 30 секунд
```suggestion
		в установке их в космосе рядом со станцией и перекалибровки их с помощью предоставленного Емага. Будьте осторожны: вам нужно 30 секунд
```

2024-04-16 19:25 UTC, larentoun commented on strings/antagonist_flavor/traitor_flavor.json
> +        "allies": "Вы можете сотрудничать с другими оперативниками синдиката, если они поддержат наше дело. Может быть, ты сможешь нанять рекрута из АRC, чтобы хоть раз оказаться полезным?",
```suggestion
        "allies": "Вы можете сотрудничать с другими оперативниками синдиката, если они поддержат наше дело. Может быть, ты сможешь нанять рекрута из АRC, чтобы они хоть раз оказались полезными?",
```

2024-04-16 19:25 UTC, larentoun commented on strings/antagonist_flavor/traitor_flavor.json
> +        "allies": "Любой, кто видит то, что вы видите, чувствует то же, что вы чувствуете, может присоединиться к Чемпионам Зла! Это означает, что Синдикат, корыстный или даже безумный, пока у него е
```suggestion
        "allies": "Любой, кто видит то, что вы видите, чувствует то же, что вы чувствуете, может присоединиться к Чемпионам Зла! Это означает, что Синдикат, корыстный или даже безумный, и пока у него есть сердце тьмы - он дружит с Чемпионами!",
```

2024-04-16 19:25 UTC, larentoun commented on strings/antagonist_flavor/traitor_flavor.json
> +        "allies": "Вы можете сотрудничать с любыми друзьями коалиции Синдиката, но следите за теми мудилами из Тигров, если они все же появятся",
```suggestion
        "allies": "Вы можете сотрудничать с любыми друзьями коалиции Синдиката, но следите за теми мудилами из Тигров, если они все же появятся.",
```

2024-04-16 19:25 UTC, larentoun commented on strings/antagonist_flavor/traitor_flavor.json
> +        "allies": "НЕ раскрывайте свой статус агента никому. Работайте чтобы искоренить коррупцию на станции из тени.",
```suggestion
        "allies": "НЕ раскрывайте свой статус агента никому. Работайте, чтобы искоренить коррупцию на станции из тени.",
```

2024-04-16 19:25 UTC, larentoun commented on strings/antagonist_flavor/traitor_flavor.json
> +        "allies": "Сотрудникам Cybersun следует доверять. Членам организации МИ-13 можно доверять. Всем остальным оперативникам синдиката доверять нельзя.",
```suggestion
        "allies": "Сотрудникам Cybersun следует доверять. Членам организации MI13 можно доверять. Всем остальным оперативникам синдиката доверять нельзя.",
```
Определись, MI13 или МИ-13

2024-04-16 19:25 UTC, larentoun commented on strings/antagonist_flavor/traitor_flavor.json
> +        "goal": "Помните учения Хай-лургиксона: убей первым, задавай вопросы позже!",
```suggestion
        "goal": "Помните учения Хай-лургиксона: сначала убийство, а потом вопросы!",
```

2024-04-16 19:58 UTC, larentoun requested changes

2024-04-16 19:58 UTC, larentoun commented on code/modules/uplink/uplink_items/contractor.dm
> +		оплату и места для транспортировки для ваших текущих доступных контрактов."
```suggestion
		оплату и места для транспортировки ваших текущих доступных контрактов."
```
Вот ты и попался

2024-04-16 20:03 UTC, larentoun approved these changes

2024-04-17 17:23 UTC, merged