Locker & Pipe sounds, Transform tweaks, Remove TTS from scanner gate, Stickers amt. restriction
ss220club/Bandastation pull request #692
Opened 2024-11-11 19:36 UTC by dj-34

## About The Pull Request
Причины введения описаны в ишуях прикрепленных ниже.

- Заменил уебищный, доебывающий звук падающей трубы с мема, который уже сдох.
Closes https://github.com/ss220club/Bandastation/issues/683

- Добавил звук открытия/закрытия замков шкафчиков.
Closes https://github.com/ss220club/Bandastation/issues/691

- Уменьшил порог максимального значения у growthserum. Больше не должно быть абсурдно огромных персонажей, даже с геном гигантизма.
Closes https://github.com/ss220club/Bandastation/issues/684

- Убрал ТТС у сканнера, больше нет "ОТМЕНА СКАНИРОВАНИЯ НА ОРУЖИЕ".
Closes https://github.com/ss220club/Bandastation/issues/682

- Ограничил наклеивание стикеров на персонажа до 1 штуки.
Closes https://github.com/ss220club/Bandastation/issues/685

- Ограничил элемент squish до максимально 3 возможных.
Closes https://github.com/ss220club/Bandastation/issues/686

## Why It's Good For The Game
Уменьшено количество SHIZO.

2024-11-11 19:40 UTC, AyIong commented
Огромных кукол оставь, душнила

2024-11-11 19:42 UTC, dj-34 commented
> Огромных кукол оставь, душнила

Мне найти скрин?

2024-11-11 19:45 UTC, dj-34 commented
Там был перс еще больше, это было 10 дней назад.

> > Огромных кукол оставь, душнила
> 
> Мне найти скрин?

![image](https://github.com/user-attachments/assets/9af78036-4c75-40f3-aedf-b504049ebe8c)

2024-11-12 11:39 UTC, Graybear98 commented
О, это мне весело было и я совершил жёсткий абуз игровых механик

2024-11-12 23:01 UTC, dj-34 commented
Я пересилил свое недовольство и вернул ПР. Отмена сканирования на оружие и отсутствия звука лок/анлок шкафчика выебала мне мозги при просмотре стрима 🥺

2024-11-12 23:03 UTC, dj-34 commented
Что будет то будет.
Я готов вести диалог и устраивать голосование в разрабской, если что-то не нравится. Процент проигрыша звука падающей трубы делать не буду.

2024-11-12 23:21 UTC, AyIong commented on modular_bandastation/aesthetics_sounds/code/closet.dm
> +	)
Зачем каждый вызов прока, делать список? Вынесешь мб прямо в сущность?

2024-11-12 23:44 UTC, dj-34 commented
Звук падающей трубы откачу, по локу/анлоку ща посмотрю че можно сделать.

2024-11-13 00:26 UTC, larentoun requested changes

2024-11-13 00:26 UTC, larentoun commented on modular_bandastation/aesthetics_sounds/_aesthetics_sounds.dm
> +/datum/modpack/aesthetics
У модпака такой же путь, как и у модуля "Эстетика". Можно просто туда же кинуть все изменения звуков и визуала вместе?

2024-11-13 00:26 UTC, larentoun commented on modular_bandastation/aesthetics_sounds/code/closet.dm
> +	var/list/togglelock_sound = list(
```suggestion
	var/static/list/togglelock_sound = list(
```

2024-11-13 00:26 UTC, larentoun commented on modular_bandastation/aesthetics_sounds/code/closet.dm
> +	. = ..()
Вообще, можно запомнить `var/is_locked = locked`, вызвать `. = ..()`, если `is_locked != locked`, то проиграть звук

2024-11-13 00:26 UTC, larentoun commented on modular_bandastation/overrides/code/stickers.dm
> +	if(isliving(target) && COUNT_TRAIT_SOURCES(target, TRAIT_STICKERED) >= 1)
```suggestion
	if(isliving(target) && COUNT_TRAIT_SOURCES(target, TRAIT_STICKERED))
```

2024-11-13 00:26 UTC, larentoun commented on modular_bandastation/overrides/code/squish.dm
> +	if(C && C.squish_counter >= 0)
```suggestion
	if(C && C.squish_counter)
```

2024-11-13 00:26 UTC, larentoun commented on modular_bandastation/overrides/code/squish.dm
> +	if(C && C.squish_counter >= 0)
а нужно ли проверять на 0?

2024-11-13 00:26 UTC, larentoun commented on modular_bandastation/overrides/code/squish.dm
> +		return ELEMENT_INCOMPATIBLE
Попробуй использовать argument_hash_start_idx с ELEMENT_BESPOKE, кажется они ограничивают количество одиноковых элементов. Если оно - класс, если нет, то жаль, будут рантаймы.

2024-11-13 14:08 UTC, larentoun commented on modular_bandastation/overrides/code/squish.dm
> +		return ELEMENT_INCOMPATIBLE
Можно тогда в коркод убрать, чтобы там проверяло и останавливало до добавления элемента?

2024-11-13 14:10 UTC, dj-34 commented on modular_bandastation/overrides/code/squish.dm
> +		return ELEMENT_INCOMPATIBLE
> Можно тогда в коркод убрать, чтобы там проверяло и останавливало до добавления элемента?

Как?

2024-11-13 14:14 UTC, larentoun requested changes

2024-11-13 14:19 UTC, dj-34 commented on modular_bandastation/aesthetics_sounds/code/closet.dm
> +	)
Но тогда у не secure клозета будет лишний лист, это ок?

2024-11-13 15:00 UTC, larentoun commented on modular_bandastation/overrides/code/squish.dm
> +		return ELEMENT_INCOMPATIBLE
В коркоде перед `AddElement(/datum/element/squish, N SECONDS)` делать проверку, окружив комментом BANDASTATION EDIT. Рантаймы не хочется видеть от того, что ELEMENT_INCOMPATIBLE.

2024-11-13 15:10 UTC, dj-34 commented on modular_bandastation/overrides/code/squish.dm
> +/mob/living
> 

А если НПС?

2024-11-13 18:12 UTC, dj-34 commented on modular_bandastation/overrides/code/squish.dm
> +		return ELEMENT_INCOMPATIBLE
> В коркоде перед `AddElement(/datum/element/squish, N SECONDS)` делать проверку, окружив комментом BANDASTATION EDIT. Рантаймы не хочется видеть от того, что ELEMENT_INCOMPATIBLE.

А откуда там рантайм будет? У меня не было вроде с этим рантаймов

2024-11-13 18:54 UTC, larentoun approved these changes

2024-11-13 19:13 UTC, merged