Papershredder shredding fix & translated papershredder
ss220club/Bandastation pull request #722
Opened 2024-11-15 11:09 UTC by Chorden523

## About The Pull Request
Фиксит ту проблему, что измельчитель бумаги не мог измельчать подтипы бумаги, книг и т.д. Переводит всё что с ним связано на русский язык.

## Why It's Good For The Game
Измельчитель теперь может измельчать больше предметов и он на русском.

## Changelog
:cl:
fix: Измельчитель бумаги теперь измельчает все типы бумаги, книг, фото и папок для документов.
/:cl:

2024-11-15 12:23 UTC, Furrior commented on modular_bandastation/objects/code/papershredder.dm
> +	var/shredded_paper_amount
Клуелесс

2024-11-15 12:23 UTC, Furrior commented on modular_bandastation/objects/code/papershredder.dm
> +	shredded_paper_amount = 5
Почему это не сделать списком в самом шредере?

2024-11-15 12:23 UTC, Furrior requested changes
Хуйня, переделывай

2024-11-16 05:56 UTC, Chorden523 commented on modular_bandastation/objects/code/papershredder.dm
> +	shredded_paper_amount = 5
Можно, просто список выйдет большим, ведь у бумаги огромная куча подтипов

2024-11-18 10:50 UTC, Furrior commented on modular_bandastation/objects/code/papershredder.dm
> +	shredded_paper_amount = 5
> Можно, просто список выйдет большим, ведь у бумаги огромная куча подтипов

Такой же по размеру, как это

2024-12-04 00:49 UTC, closed without merging