Better dragon/carp translation
ss220club/Bandastation pull request #75
Opened 2024-04-14 18:16 UTC by larentoun

## About The Pull Request

Теперь не переводим имена

2024-04-15 15:11 UTC, Furrior reviewed
Рандомные замечания

2024-04-15 15:11 UTC, Furrior commented on code/_onclick/hud/alert.dm
> +			context[SCREENTIP_CONTEXT_ALT_LMB] = "[selected_never ? "Начать " : "Не "]приглашать в этом раунде"
Косяк?

2024-04-15 15:11 UTC, Furrior commented on code/datums/actions/mobs/fire_breath.dm
> +	to_chat(barbecued, span_userdanger("Вас подожгло огненное дыхание от - [source]!"))
```suggestion
	to_chat(barbecued, span_userdanger("Вас подожгло огненное дыхание [source]!"))
```
наверн все же лучше будет

2024-04-15 15:11 UTC, Furrior commented on code/datums/components/mind_linker.dm
> +		to_chat(owner, span_boldwarning("Ваша связь, [network_name], сломалась!"))
```suggestion
		to_chat(owner, span_boldwarning("Ваша [network_name] сломалась!"))
```
Далее ты не пишешь связь

2024-04-15 15:11 UTC, Furrior commented on code/datums/components/mind_linker.dm
> +	desc = "Отправьте мысленное сообщение всем, кто соединен вашей связью."
```suggestion
	desc = "Отправьте мысленное сообщение всем, кто соединен вашей Связью."
```

2024-04-15 15:11 UTC, Furrior commented on code/datums/components/mind_linker.dm
> +	desc = "Отправьте мысленное сообщение всем, кто соединен с помощью [linker.network_name]."
```suggestion
	desc = "Отправьте мысленное сообщение всем, кто соединен с вашей [linker.network_name]."
```

2024-04-15 15:11 UTC, Furrior commented on code/modules/mob/living/basic/festivus_pole.dm
> +	gender = MALE
Перевод, который мы залужили

2024-04-15 15:11 UTC, Furrior commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Свирепое, клыкастое существо, внешне схожее на рыбу."
```suggestion
	desc = "Свирепое, клыкастое существо, внешне схожее с рыбой."
```

2024-04-15 15:11 UTC, Furrior commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	AddComponent(/datum/component/aggro_emote, emote_list = string_list(list("оскаливается")))
```suggestion
	AddComponent(/datum/component/aggro_emote, emote_list = string_list(list("скалится")))
```

2024-04-15 15:11 UTC, Furrior commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Она вышла из кого-то."
```suggestion
	desc = "Она вышло из кого-то."
```

2024-04-15 15:11 UTC, Furrior commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Покорное и с присоской вместо рта существо, внешне схожее на рыбу. "
Звучит ужасно

2024-04-15 15:18 UTC, larentoun commented on code/_onclick/hud/alert.dm
> +			context[SCREENTIP_CONTEXT_ALT_LMB] = "[selected_never ? "Начать " : "Не "]приглашать в этом раунде"
Если нажали "не приглашать", то мы "Начнем приглашать", а если не нажимали, то предложим "Не приглашать"

2024-04-15 15:19 UTC, larentoun commented on code/modules/mob/living/basic/festivus_pole.dm
> +	gender = MALE
Заделки на будущее

2024-04-15 15:19 UTC, larentoun commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Покорное и с присоской вместо рта существо, внешне схожее на рыбу. "
Я не смог нормально перевести

2024-04-15 15:20 UTC, larentoun commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Она вышла из кого-то."
Она вышло? Просто с "it" - питомцы, им не дают гендеры. А в русском у животных есть гендеры?

2024-04-15 15:21 UTC, larentoun commented on code/datums/components/mind_linker.dm
> +	desc = "Отправьте мысленное сообщение всем, кто соединен вашей связью."
Не знаю, считать ли это именем собственным?

2024-04-15 15:22 UTC, Furrior commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Она вышла из кого-то."
У меня шиза, забей. Я прочитал "оно"

2024-04-17 17:24 UTC, Furrior commented on code/datums/components/mind_linker.dm
> +	desc = "Отправьте мысленное сообщение всем, кто соединен вашей связью."
Ну в оригинале считается же

2024-04-17 19:14 UTC, Artemchik542 commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Покорное и с присоской вместо рта существо, внешне схожее на рыбу. "
Ну могу предложить такой перевод: "На первый взгляд робкая и не опасная рыбина, однако не дайте ей поставить вам засос в неожиданном месте."

2024-04-19 09:38 UTC, Gaxeer requested changes

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/mob/living/basic/tree.dm
> +	desc = "Разозленное древоподобное существо. Кажется, оно не любит праздники..."
```suggestion
	desc = "Обозленное древоподобное существо. Кажется, оно не любит праздники..."
```

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/mob/living/basic/space_fauna/space_dragon/dragon_gust.dm
> +	desc = "Вздымитесь в воздух, чтобы вызвать сильный порыв воздуха со своих крыльев, отталкивающий врагов. Значительно утомляет, если делать его без перерыва."
```suggestion
	desc = "Вздымитесь в воздух, вызвав своимы крыльями мощный порыв воздуха, отталкивающий врагов. Значительно утомляет, если делать его без перерыва."
```

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Покорное и с присоской вместо рта существо, внешне схожее на рыбу. "
```suggestion
	desc = "На первый взгляд робкая и не опасная рыбина, однако не дайте ей поставить вам засос в неожиданном месте. "
```

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Она вышла из кого-то."
```suggestion
	desc = "Карп-паразит, который живет в своём носителе до созревания и кажется он уже \"вылупился\"."
```

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Провальный эксперимент Синдиката по созданию военных технологий на основе карпов, ныне милый талисман."
```suggestion
	desc = "Провальный эксперимент Синдиката по созданию оружия из обычного космокарпа, ныне милый талисман."
```

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/mob/living/basic/space_fauna/carp/carp.dm
> +	desc = "Провальный эксперимент Nanotrasen по созданию военных технологий на основе карпов. Этот менее устрашающий карп теперь служит питомцем для главы службы безопасности."
```suggestion
	desc = "Провальный эксперимент Nanotrasen по созданию оружия из космокарпа. Этот менее устрашающий карп теперь служит питомцем для главы службы безопасности."
```

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/antagonists/space_dragon/space_dragon.dm
> +	priority_announce("Огромное количество форм жизни надвигается в сторону [station_name()] с огромной скоростью. \
```suggestion
	priority_announce("Огромное количество форм жизни надвигается в сторону [station_name()] с невероятной скоростью. \
```

2024-04-19 09:38 UTC, Gaxeer commented on code/modules/antagonists/space_dragon/space_dragon.dm
> +		Живому экипажу необходимо эвакуироваться как можно скорее.", "[command_name()]: Отдел Изучения Дикой Природы", has_important_message = TRUE)
```suggestion
		Оставшемуся экипажу необходимо эвакуироваться как можно скорее.", "[command_name()]: Отдел Изучения Дикой Природы", has_important_message = TRUE)
```

2024-04-19 09:38 UTC, Gaxeer commented on code/datums/components/mind_linker.dm
> +		to_chat(owner, span_warning("Связь, видимо, была уничтожена."))
```suggestion
		to_chat(owner, span_warning("Связь, видимо, была разорвана."))
```

2024-04-19 09:38 UTC, Gaxeer commented on code/datums/components/mind_linker.dm
> +	desc = "Отправьте мысленное сообщение всем, кто соединен вашей Связью."
```suggestion
	desc = "Отправьте мысленное сообщение всем, кто с вами связан."
```

2024-04-19 09:38 UTC, Gaxeer commented on code/datums/actions/mobs/fire_breath.dm
> +	desc = "Выдохните линию пламени в сторону цели."
```suggestion
	desc = "Изрыгните линию огня в сторону цели."
```

2024-04-19 09:59 UTC, Artemchik542 commented on code/datums/actions/mobs/fire_breath.dm
> +	desc = "Выдохните линию пламени в сторону цели."
"Линия огня" звучит двусмысленно, а вот "Извергните" - очень даже к месту. Предлагаю вообще убрать слово "линия" чтобы получилось:
```
desc = "Извергните огонь в сторону цели."
```

2024-04-19 10:27 UTC, larentoun commented on code/modules/mob/living/basic/space_fauna/space_dragon/dragon_gust.dm
> +	desc = "Вздымитесь в воздух, чтобы вызвать сильный порыв воздуха со своих крыльев, отталкивающий врагов. Значительно утомляет, если делать его без перерыва."
Дракон сначала поднимается, а потом через секунду как падает

2024-04-19 13:50 UTC, Gaxeer approved these changes

2024-04-19 14:20 UTC, merged