Add: Syndicate Central Command
ss220club/Bandastation pull request #815
Opened 2024-11-27 01:09 UTC by dj-34

Добавляет Синди-ЦК с Пары, объекты под него и скрипт замены.

2024-11-28 09:26 UTC, adskipups commented
Надо бы заменить траву на снег(и воду на плазму), ибо база синдиката находиться на айс муне.

2024-12-01 05:23 UTC, dj-34 commented
> Надо бы заменить траву на снег(и воду на плазму), ибо база синдиката находиться на айс муне.

Это не та база Синдиката и лор у нас другой

2024-12-03 15:32 UTC, dj-34 commented on code/__DEFINES/access.dm
> +	ACCESS_SYNDICATE_COMMAND, \
Сразу скажу что у меня не получается это комментировать - выдает ошибку

2024-12-05 01:40 UTC, dj-34 commented
Вроде все. С телепортом не смог справиться, в остальном вроде все рабочее.

2024-12-07 15:45 UTC, Gaxeer requested changes

2024-12-07 15:45 UTC, Gaxeer commented on modular_bandastation/mobs/_mobs.dm
> +/datum/modpack/overrides
```suggestion
/datum/modpack/mobs
```

2024-12-07 15:45 UTC, Gaxeer commented on modular_bandastation/mobs/_mobs.dm
> +	desc = "Кастомные симпл-мобы."
```suggestion
	desc = "Кастомные мобы."
```

2024-12-07 15:45 UTC, Gaxeer commented on modular_bandastation/objects/code/shuttles.dm
> +	return TRUE
```suggestion
/obj/machinery/computer/shuttle/syndicate/sit/launch_check(mob/user)
	return allowed(user)

/obj/machinery/computer/shuttle/syndicate/sst/launch_check(mob/user)
	return allowed(user)
```

2024-12-08 11:46 UTC, Gaxeer approved these changes

2024-12-08 11:46 UTC, merged