[Feat] Новые работки ролеплейной направленности
ss220club/Bandastation pull request #833
Opened 2024-12-02 17:20 UTC by Gaxeer

## About The Pull Request

Добавляет новые работки, пока что включены:
- [ ] Магистрат
   - [ ] Карточка
   - [ ] ПДА и программы на него по умолчанию
   - [ ] Стандартное снаряжение
   - [ ] Одежда (В том числе для плазмамена)
   - [ ] Кабинет и его наполнение
   - [ ] Бюрократические формы
   - [ ] Придумать зарплату
   - [ ] Предметы в почту
   - [ ] Список возможных семейных реликвий (список family_heirlooms)
   - [ ] Обдумать требуемый возраст куклы
- [ ] Представитель NanoTrasen
   - [ ] Карточка
   - [ ] ПДА и программы на него по умолчанию
   - [ ] Стандартное снаряжение
   - [ ] Одежда (В том числе для плазмамена)
   - [ ] Кабинет и его наполнение
   - [ ] Бюрократические формы
   - [ ] Придумать зарплату
   - [ ] Предметы в почту
   - [ ] Список возможных семейных реликвий (список family_heirlooms)
   - [ ] Обдумать требуемый возраст куклы
- [ ] Офицер "Синий щит" 
   - [ ] Карточка
   - [ ] ПДА и программы на него по умолчанию
   - [ ] Стандартное снаряжение
   - [ ] Стан посох
   - [ ] Одежда (В том числе для плазмамена)
   - [ ] Кабинет и его наполнение
   - [ ] Придумать зарплату
   - [ ] Предметы в почту
   - [ ] Список возможных семейных реликвий (список family_heirlooms)
   - [ ] Обдумать требуемый возраст куклы

## Why It's Good For The Game

Некоторые люди без них жить не могут. В целом больше работок - больше вариантов ролеплея :clueless:

## Changelog

:cl:
add: Добавлены новые професии: Магистрат, Представитель NanoTrasen, Офицер "Синий щит"
/:cl:

2024-12-03 03:16 UTC, dj-34 commented
### Blueshield
https://github.com/Monkestation/Monkestation2.0/tree/master/monkestation/code/modules/blueshield
https://github.com/NovaSector/NovaSector/tree/master/modular_nova/modules/blueshield
https://github.com/Bubberstation/Bubberstation/tree/master/modular_skyrat/modules/blueshield

### NTRep

https://github.com/Monkestation/Monkestation2.0/tree/master/monkestation/code/modules/NTrep
https://github.com/Bubberstation/Bubberstation/tree/master/modular_skyrat/modules/nanotrasen_rep
https://github.com/NovaSector/NovaSector/tree/master/modular_nova/modules/nanotrasen_rep

### Magistrate
https://github.com/Dripstation-Dev/Dripstation/pull/55 (Yogstation)

### Explorer
https://github.com/Monkestation/Monkestation2.0/pull/4217
https://github.com/Dripstation-Dev/Dripstation/pull/55 (Yogstation)

2024-12-03 09:25 UTC, Graybear98 commented
Синий щит нах не нужен, юзелесс профа, которая ворует работу у сб

2024-12-14 10:24 UTC, Graybear98 commented
https://github.com/tgstation/tgstation/pull/74423

2024-12-14 10:25 UTC, Graybear98 commented
Работки уже были кстати!

2024-12-20 13:41 UTC, dj-34 commented on code/__DEFINES/jobs.dm
> +#define DEPARTMENT_BITFLAG_JUSTICE (1<<11) // Bandastation add - Jobs Module
а почему не через
// BANDASTATION ADD - START
** код **
// BANDASTATION ADD - END

2024-12-20 13:41 UTC, dj-34 commented on code/__DEFINES/jobs.dm
> +	"JUSTICE" = DEPARTMENT_BITFLAG_JUSTICE, // Bandastation add - Jobs Module
Здесь тоже

2024-12-20 13:41 UTC, dj-34 commented on code/datums/station_traits/positive_traits.dm
> +		/datum/job/magistrate = /obj/item/organ/cyberimp/arm/paperwork, // BANDASTATION ADD - Jobs Module
и здесь

2024-12-20 13:41 UTC, dj-34 commented on code/modules/asset_cache/assets/paper.dm
> +
Походу лишний
```suggestion
```

2024-12-20 13:41 UTC, dj-34 commented on code/modules/mob/mob.dm
> +			var/image/I = image('modular_bandastation/hud_icon/icons/hud.dmi', src, "") // Bandastation edit - original: 'icons/mob/huds/hud.dmi'
Так ты насрунькал в icons/mob/huds/hud.dmi
Какой смысл менять на модульный тогда?

2024-12-20 13:41 UTC, dj-34 commented on code/modules/mob/living/living_say.dm
> +	"ч" = RADIO_CHANNEL_JUSTICE,  // BANDASTATION ADD - Jobs Module
ч? было же l (д)

2024-12-20 13:41 UTC, dj-34 commented on modular_bandastation/hud_icon/_hud_icon.dm
> +	author = "gaxeer"
шо то не совсем понял зачем оно

2024-12-20 13:41 UTC, dj-34 commented on modular_bandastation/hud_icon/README.md
> +PR: https://github.com/ss220club/Bandastation/pull/
```suggestion
PR: https://github.com/ss220club/Bandastation/pull/833
```

2024-12-20 13:41 UTC, dj-34 commented on modular_bandastation/jobs/_jobs.dme
> +// END_INCLUDE
```suggestion
```

2024-12-23 11:47 UTC, Gaxeer commented
Надо мергировать. Изменения карты ебут

2024-12-23 11:54 UTC, AyIong requested changes

2024-12-23 11:54 UTC, AyIong commented on code/_globalvars/admin.dm
> +	"Justice Radio" = "justiceradio", // BANDASTATION ADD
Добавить бы у всех комментов, какого модуля это касается, для быстрого поиска

2024-12-23 11:54 UTC, AyIong commented on interface/stylesheet.dm
> +.justiceradio			{color: #df3e71;}
Таба не хватает, и коммента

2024-12-23 11:54 UTC, AyIong commented on modular_bandastation/jobs/readme.md
Пустота 💀

2024-12-24 13:59 UTC, AyIong approved these changes

2024-12-24 14:00 UTC, merged