RnD experiments translation (FARGUS)
ss220club/Bandastation pull request #85
Opened 2024-04-15 14:30 UTC by BR54FF

## About The Pull Request

перевод эксперментов

## Why It's Good For The Game

перепвод эксперминетов

## Changelog

:cl:
add: перевод экспериментов
/:cl:

2024-04-15 14:58 UTC, BR54FF commented on code/modules/experisci/experiment/physical_experiments.dm
> +	. += EXPERIMENT_PROG_BOOL("Выстрелите эмиттером в отслеживаемую мясную стену", is_complete())
Не уверен насчёт этого перевода

2024-04-15 14:58 UTC, BR54FF commented on code/modules/experisci/experiment/physical_experiments.dm
> +	. += EXPERIMENT_PROG_BOOL("Выиграйте аркадную игру в отслеживаемом игровом зале.", is_complete())
Этого тоже немного.

2024-04-18 15:19 UTC, BR54FF commented
есть куча проёбов, но я пьяный, так что плюйтесь

2024-04-18 17:13 UTC, larentoun requested changes
Не забудь проверить то, что билд компилируется.

Так же, разберись, как ты переводишь tank - баллон, резервуар, или бак. Лучше зайди в игру и посмотри, что нужно пихать. Скорее всего вообще канистру.

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	description = "Гиперноблиум образуется очень энергично, и его можно использовать для изготовления взрывчатых веществ. Зафиксируйте любой взрыв бака с помощью доплеровской решетки и опубликуйте данны
```suggestion
	description = "Гиперноблиум образуется очень энергично, и его можно использовать для изготовления взрывчатых веществ. Зафиксируйте любой взрыв любого резервуара с помощью доплеровской решетки и опубликуйте данные в отчёте. Разрешена только конденсация гиперноблия."
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "BZ-газовые гильзы"
```suggestion
	name = "BZ-снаряды"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Гиперноблиевые гильзы"
```suggestion
	name = "Гиперноблиевые снаряды"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	description = "Доставка Гиперноблиума в район проведения операции может оказаться полезной. Упакуйте указанный газ в баллон и взорвите его с помощью компрессора для баллонов. Опубликуйте данные в от
```suggestion
	description = "Доставка гиперноблиума в район проведения операции может оказаться полезной. Упакуйте указанный газ в баллон и взорвите его с помощью компрессора для баллонов. Опубликуйте данные в отчёте."
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Эксперимент по скану материалов среднего класса(1)"
```suggestion
	name = "Эксперимент по скану материалов среднего класса (1)"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Эксперимент по скану материалов среднего класса(2)"
```suggestion
	name = "Эксперимент по скану материалов среднего класса (2)"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Эксперимент по скану материалов среднего класса(3)"
```suggestion
	name = "Эксперимент по скану материалов среднего класса (3)"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Эксперимент по скану высококлассных материалов(1)"
```suggestion
	name = "Эксперимент по скану высококлассных материалов (1)"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Эксперимент по скану высококлассных материалов(2)"
```suggestion
	name = "Эксперимент по скану высококлассных материалов (2)"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Эксперимент по скану высококлассных материалов(3)"
```suggestion
	name = "Эксперимент по скану высококлассных материалов (3)"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Материалы для Мехов 1: Стресс-тест"
```suggestion
	name = "Материалы для экзокостюмов 1: стресс-тест"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Материалы для Мехов 2: Испытание на нагрузку"
```suggestion
	name = "Материалы для экзокостюмов 2: испытание на нагрузку"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	description = "Экзокостюмы создают уникальную нагрузку на конструкцию транспортного средства. Сканируйте экзокостюмы, собранные на вашем предприятии по мехосборке и полностью оснащенные, чтобы ускор
```suggestion
	description = "Экзокостюмы создают уникальную нагрузку на конструкцию транспортного средства. Сканируйте экзокостюмы, собранные на ваших фабрикаторах экзосьютов и полностью оснащенные, чтобы ускорить моделирование структурных нагрузок."
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	name = "Исследование людского поля: Дивергентная биология"
```suggestion
	name = "Исследование людского поля: дивергентная биология"
```

2024-04-18 17:13 UTC, larentoun commented on code/modules/experisci/experiment/experiments.dm
> +	performance_hint = "Необычные органы могут быть введены вручную путем пересадки, генетической инфузии или очень быстро с помощью эффекта аномалии Биоскрамлер."
```suggestion
	performance_hint = "Необычные органы могут быть введены вручную путем пересадки, генетической инфузии или очень быстро с помощью эффекта аномалии Биоскрэмблэр."
```

2024-04-18 23:34 UTC, BR54FF commented on code/modules/experisci/experiment/experiments.dm
> +	performance_hint = "Необычные органы могут быть введены вручную путем пересадки, генетической инфузии или очень быстро с помощью эффекта аномалии Биоскрамлер."
скрэээээмблерс

2024-04-18 23:53 UTC, BR54FF commented on code/modules/experisci/experiment/types/scanning_points.dm
> +	. = EXPERIMENT_PROG_INT("Сканируйте образцы следующих объектов для набора достаточного кол-ва очков и завершения эксперимента.", points, required_points)
Я везде сокращать пытаюсь, чтоб влезало.

2024-04-19 08:40 UTC, BR54FF commented on code/modules/experisci/experiment/experiments.dm
> +	description = "Маломощные взрывчатые вещества могут оказаться полезными для наших групп по защите активов. Зафиксируйте небольшой взрыв с помощью доплеровской решетки и опубликуйте данные в отчёте."
Нашёл, чё это за хрень. Лучше перевести как массив или матрица. Измеряет взрывы крч.

2024-04-19 08:58 UTC, BR54FF commented
локалка запускается, где надо сократил ещё немного и тд и тп и пуппупипэ чикиряу

2024-04-19 10:47 UTC, larentoun approved these changes
Тесты прошли, суть передана, а с литературным языком справимся после запуска

2024-04-19 14:17 UTC, Gaxeer approved these changes

2024-04-19 14:18 UTC, merged