Add: Closet & Crate lockpicking
ss220club/Bandastation pull request #869
Opened 2024-12-13 01:16 UTC by dj-34

Добавляет взлом шкафчиков с Пары

2024-12-13 01:22 UTC, larentoun requested changes
Надо бы добавить ремонт шкафчика тоже. Просто проводом и ПКМ отверткой.

2024-12-13 01:22 UTC, larentoun commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +			. += span_notice("Замок отключён.")
Предлагаю всё в одно предложение запихнуть, а не плодить 3 строки.

2024-12-13 01:22 UTC, larentoun commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +		to_chat(user, span_notice("Вы начинаете выламывать панель доступа [src]..."))
```suggestion
		to_chat(user, span_notice("Вы начинаете выламывать панель доступа [declent_ru(GENITIVE)]..."))
```

2024-12-13 01:22 UTC, larentoun commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +				to_chat(user, span_notice("Вы успешно выломали панель с [src]!"))
```suggestion
				to_chat(user, span_notice("Вы успешно выломали панель с [declent_ru(GENITIVE)]!"))
```

2024-12-13 01:22 UTC, larentoun commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +				to_chat(user, span_warning("Проклятье! [I] сорвалась и повредила [affecting.name]!"))
```suggestion
				to_chat(user, span_warning("Проклятье! [capitalize(I.declent_ru(NOMINATIVE))] срывается и повреждает [affecting.declent_ru(ACCUSATIVE)]!"))
```

2024-12-13 01:22 UTC, larentoun commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +		to_chat(user, span_notice("Вы начинаете подготавливать провода панели [src]..."))
```suggestion
		to_chat(user, span_notice("Вы начинаете подготавливать провода панели [declent_ru(GENITIVE)]..."))
```

2024-12-13 01:22 UTC, larentoun commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +				to_chat(user, span_notice("Вы успешно подготовили провода панели [src]!"))
```suggestion
				to_chat(user, span_notice("Вы успешно подготовили провода панели [declent_ru(GENITIVE)]!"))
```

2024-12-13 01:27 UTC, dj-34 commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +			. += span_notice("Замок отключён.")
Я не хочу так делать, тут все определения с новой строки
![image](https://github.com/user-attachments/assets/abdf8df1-ea48-483e-bbf8-6348776808f1)

2024-12-13 02:16 UTC, dj-34 commented
> Надо бы добавить ремонт шкафчика тоже. Просто проводом и ПКМ отверткой.

Касаемо ремонта, это надо на оффы, ибо используются стейты шкафчика, на которые ремонта нет.

2024-12-13 17:12 UTC, Lime-7 commented
а нужно ли?

2024-12-13 17:58 UTC, dj-34 commented
> а нужно ли?

Для тебя ничего не нужно

2024-12-13 20:04 UTC, Lime-7 commented
хотя в принципе, ничего плохо в новых методах открытия шкафов и криейтов нет, так что ладно...

2024-12-14 16:30 UTC, Gaxeer commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +				update_icon()
Не вижу чтобы ты где-то добавил обновление иконки

2024-12-14 16:30 UTC, Gaxeer requested changes
Опять надо кое-что обсудить в дискордике

2024-12-14 21:17 UTC, dj-34 commented on modular_bandastation/lockpicking/code/lockpicking.dm
> +				update_icon()
забыл вырезать рудимент, подчищу

2024-12-29 00:50 UTC, closed without merging