HTML Title Screen
ss220club/Bandastation pull request #874
Opened 2024-12-16 02:26 UTC by AyIong

## About The Pull Request
Наконец доделал (вроде) браузерный тайтл скрин
ТМ крайне желателен

## Why It's Good For The Game
Все думаю и так знают, но вот видос

https://github.com/user-attachments/assets/660a50a6-5109-4dde-83df-95eb78563939

## Changelog

:cl:
add: Дефолтное лобби заменено на браузерное
/:cl:

2024-12-16 11:26 UTC, Gaxeer requested changes

2024-12-16 12:31 UTC, Gaxeer commented on modular_bandastation/title_screen/code/title_screen_controls.dm
> +	for(var/mob/new_player in GLOB.player_list)
```suggestion
	for(var/mob/dead/new_player/new_player as anything in GLOB.new_player_list)
```

2024-12-16 12:32 UTC, Gaxeer commented on modular_bandastation/title_screen/code/title_screen_subsystem.dm
> +		show_title_screen_to(viewer.client)
```suggestion
	for(var/mob/dead/new_player/viewer as anything in GLOB.new_player_list)
		show_title_screen_to(viewer.client)
```

2024-12-16 12:33 UTC, Gaxeer commented on modular_bandastation/title_screen/code/title_screen_subsystem.dm
> +		viewer.client << output(params, "title_browser:[function]")
```suggestion
	for(var/mob/dead/new_player/viewer as anything in GLOB.new_player_list)
		viewer.client << output(params, "title_browser:[function]")
```

2024-12-16 13:42 UTC, Gaxeer commented on modular_bandastation/title_screen/code/title_screen_controls.dm
> +	set category = "OOC"
```suggestion
	set category = "Special"
```

2024-12-19 07:38 UTC, Sadboysuss commented on modular_bandastation/title_screen/code/station_traits.dm
> +	return // No SCUB and Pet Day
почему?

2024-12-19 10:05 UTC, AyIong commented on modular_bandastation/title_screen/code/station_traits.dm
> +	return // No SCUB and Pet Day
У нас никто не шарит за скаб, и я лично (вместе со всей разрабской), считаем его бредом.
А Pet Day в целом похуй, я не понял его прикола

2024-12-25 14:56 UTC, Gaxeer commented on modular_bandastation/title_screen/code/title_screen_controls.dm
> +	if(isnewplayer(src.mob))
```suggestion
	if(isnewplayer(mob))
```

2024-12-25 15:15 UTC, Gaxeer approved these changes

2024-12-25 15:19 UTC, merged