Новые причёски и рога
ss220club/Bandastation pull request #888
Opened 2024-12-20 18:13 UTC by Podvaldeda

## Что этот PR делает

Добавляет 9 новых причёсок и 14 новых рогов для ящеров, портированных с крысы

## Почему это хорошо для игры

Добавляет разнообразие для создания куклы и создание более подходящего образа для РП

## Изображения изменений

https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/oasis/Desktop/LIzpr.jpg?version%3D1734718232504

## Changelog

:cl:
add: Что-то добавил
/:cl:

2024-12-20 18:20 UTC, Podvaldeda commented
![LIzpr1](https://github.com/user-attachments/assets/77146d6a-fef8-4230-a7a1-16bc2856d834)
по какой-то причине не смог добавить картинку как надо

2024-12-22 22:23 UTC, dj-34 requested changes
1. Мне не нравится что ты создаешь отдельный модпак для кастомайза. Следует создать общий модпак "species" где ты разместишь code/lizardperson/sprite_accesories/hair.dm и туда вставишь свой код. По примеру с тем как делает Nlaysi https://github.com/ss220club/Bandastation/pull/267/files#diff-54e890efa4aa23116f97c8ab6832887ed8119a2feb4d34cdde3758d4cc1d5631

2. Насёр в .dme нужно почистить (оно иногда автоматически срёт лишним). Оставить только #include.

3. Комментарии в коде на английском, соответствующе с примерами из других модпаков, например:

```
// MARK: Frills
/datum/sprite_accessory/frills/divinity

// MARK: Horns
/datum/sprite_accessory/horns/angler
```

MARK позволяет видеть в VSCode "разделы" в правом окне.

2024-12-24 02:37 UTC, dj-34 requested changes

2024-12-24 02:37 UTC, dj-34 commented on modular_bandastation/species/_species.dm
> +	desc = "Добавляет модпак кастомайза для всех рас"
Чтоб было меньше конфликтов между твоим пром и пром Nlaysi
```suggestion
	name = "Species"
	desc = "Добавление архитектуры для новых видов и конфигурирования существующих."
```

2024-12-24 02:37 UTC, dj-34 commented on modular_bandastation/species/code/lizardperson/sprite_accesories/hair.dm
Я надеюсь здесь нет дубликата name, так как если name занят - оно будет конфликтовать.

2024-12-25 03:53 UTC, dj-34 approved these changes

2024-12-25 03:55 UTC, dj-34 commented on modular_bandastation/species/_species.dme
> +#include "code\lizardperson\sprite_accesories\hair.dm"
```suggestion
#include "_species.dm"

#include "code/lizardperson/sprite_accesories/hair.dm"
```

2024-12-25 08:00 UTC, merged