Translate: Explanation text of antag objectives
ss220club/BandaStation pull request #900
Opened 2024-12-21 20:25 UTC by dj-34

Доперевод целек

2024-12-21 20:27 UTC, dj-34 commented
какой нах тгуи

2024-12-28 03:46 UTC, larentoun requested changes

2024-12-28 03:46 UTC, larentoun commented on code/modules/antagonists/brother/brother.dm
> +	explanation_text = "Конвертируйте лицо, поддающееся промывке мозгов, используя вашу флешку на него. Любая портативная флешка подойдет, если вы потеряете или сломаете свою."
Вспышка, не флешка. Перепроверь в ru_names.toml

2024-12-28 03:46 UTC, larentoun commented on code/modules/antagonists/cult/cult_objectives.dm
> +		explanation_text = "Принесите в жертву [target], [job_title_ru(target.assigned_role.title)], с помощью использования руны Offer с [target.ru_p_theirs()] на ней и трёх послушниках вокруг руны."
"с ней на ней", перефразировать бы

2024-12-28 03:46 UTC, larentoun commented on code/modules/antagonists/fugitive/hunters/hunter.dm
> +	capture.explanation_text = "Отловите беглецов на станции и поместите их в bluespace capture machine на вашем корабле."
параллельно бы ПР, который бы добавлял перевод хотя бы для названий

2024-12-28 03:46 UTC, larentoun commented on code/modules/antagonists/pirate/pirate.dm
> +	explanation_text = "Соберите ценную добычу и храните ее в специально отведенном месте."
```suggestion
	explanation_text = "Соберите ценную добычу и храните её в специально отведенном месте."
```

2024-12-28 03:46 UTC, larentoun commented on code/modules/antagonists/separatist/objectives.dm
>  		explanation_text = "Make sure no member of [target_team] ([target_team.department.department_name]) nation escapes alive!"
Пропустили перевод?

2024-12-28 03:46 UTC, larentoun commented on code/modules/antagonists/spiders/spiders.dm
> +	explanation_text = "Распространяйте инфекцию."
Разве не заражение? Инфекция, скорее, к болезням относится, а не к "куче тараканов"?

2024-12-28 03:46 UTC, larentoun commented on code/modules/antagonists/venus_human_trap/venus_human_trap.dm
> +	explanation_text = "Распространяйте инфекцию."
Тоже самое, заражение

2024-12-30 16:33 UTC, AyIong requested changes

2024-12-30 16:33 UTC, AyIong commented on code/modules/antagonists/abductor/abductee/abductee_objectives.dm
> +		explanation_text += " кого-либо."
```suggestion
		explanation_text += " кого угодно."
```

2024-12-30 16:33 UTC, AyIong commented on code/modules/antagonists/pyro_slime/pyro_slime.dm
> +	explanation_text = "Все, что я знаю, - это огонь. Я говорю на языках пламени. Почему все такие холодные?"
```suggestion
	explanation_text = "Всё что я знаю, - это огонь. Я говорю на языках пламени. Почему все такие холодные?"
```

2024-12-30 16:33 UTC, AyIong commented on code/modules/antagonists/spiders/spiders.dm
> +	explanation_text = "Распространяйте инфекцию."
Мне кажется тут вообще не про что-то медицинское

2024-12-30 16:33 UTC, AyIong commented on code/modules/antagonists/venus_human_trap/venus_human_trap.dm
> +	explanation_text = "Распространяйте инфекцию."
Да откуда вы взяли что это как-то связано с медициной?

2024-12-30 16:33 UTC, AyIong commented on code/modules/antagonists/wizard/slaughter_antag.dm
> +	objective_verb = "Обнимите и защекотайте"
```suggestion
	objective_verb = "Обнимайте и щекочите"
```

2025-01-09 11:02 UTC, larentoun commented on code/modules/antagonists/spiders/spiders.dm
> +	explanation_text = "Распространяйте инфекцию."
Ну в том то и суть, что "инфекция" - это чисто медицинское, а заражение может быть и как для болезни ("я заразился простудой"), так и для заражений паразитами ("дом заражен тараканами"). Если есть другое слово для этих "тараканов", то я не смог вспомнить

2025-01-12 02:44 UTC, dj-34 commented on code/modules/antagonists/brother/brother.dm
> +	explanation_text = "Конвертируйте лицо, поддающееся промывке мозгов, используя вашу флешку на него. Любая портативная флешка подойдет, если вы потеряете или сломаете свою."
ПОЧЕМУ ВСПЫШКА..... ОБОЖЕ...

2025-01-12 02:47 UTC, dj-34 commented on code/modules/antagonists/brother/brother.dm
> +	explanation_text = "Конвертируйте лицо, поддающееся промывке мозгов, используя вашу флешку на него. Любая портативная флешка подойдет, если вы потеряете или сломаете свою."
Ладно

2025-01-12 02:57 UTC, dj-34 commented on code/modules/antagonists/fugitive/hunters/hunter.dm
> +	capture.explanation_text = "Отловите беглецов на станции и поместите их в bluespace capture machine на вашем корабле."
ну тут увы

2025-01-12 02:57 UTC, dj-34 commented on code/modules/antagonists/separatist/objectives.dm
>  		explanation_text = "Make sure no member of [target_team] ([target_team.department.department_name]) nation escapes alive!"
Нации вырезали же?

2025-01-12 03:09 UTC, AyIong approved these changes
Галка сику нужна ещё

2025-01-13 17:12 UTC, merged

2025-01-15 09:54 UTC, larentoun commented on code/modules/antagonists/separatist/objectives.dm
>  		explanation_text = "Make sure no member of [target_team] ([target_team.department.department_name]) nation escapes alive!"
Их в эвент панели нет, что ли?

2025-01-15 09:55 UTC, larentoun commented on code/modules/antagonists/brother/brother.dm
> +	explanation_text = "Конвертируйте лицо, поддающееся промывке мозгов, используя вашу флешку на него. Любая портативная флешка подойдет, если вы потеряете или сломаете свою."
Перевод с вики :)