Translation: Antags information
ss220club/BandaStation pull request #915
Opened 2024-12-25 16:53 UTC by Ingakem

## Что этот PR делает
Перевод большинства информационных табличек антагов

## Почему это хорошо для игры
Перевод для тех кто не понимает инглиш

## Изображения изменений
![image](https://github.com/user-attachments/assets/eff7647c-488e-48c9-9aa6-db8bd298acc4)
![image](https://github.com/user-attachments/assets/00ea6c3e-aafc-4030-b516-6e71c3835c3b)

## Тестирование
Проверил на локалке

## Changelog

:cl:
tweak: Перевод буков
/:cl:

2024-12-26 08:45 UTC, dj-34 commented
Линтер

2024-12-28 03:53 UTC, larentoun requested changes
Я чуть позже вернусь к этому ПРу, но пока попробуй убрать разницу в строках перефразированиями или чем-то

2024-12-28 03:53 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +        В роли управляющего ядра вы можете управлять блобом.
```suggestion
        В роли сверхразума вы можете управлять блобом.
```
Можно взять пример перевода с Starcraft. Сверхмозги сила

2024-12-28 03:53 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          Вы сможете вручную разместить ядро блоба, нажав кнопку Place Blob Core
А давай сразу кнопки тоже переведи?

2024-12-28 03:53 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          в правом нижнем углу экрана. <br />
а где {' ' } и желательно убери разницу в строках

2024-12-28 03:53 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Эй, не смейте! Хватит транслировать это!
А это, разве, пишет в чат на кириллице? Там же просто символы, если это виндингс?

2024-12-28 03:53 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Ты испортил мой классный эффект шрифта.
тоже самое?

2024-12-29 16:08 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Эй, не смейте! Хватит транслировать это!
> А это, разве, пишет в чат на кириллице? Там же просто символы, если это виндингс?

Я и не заметил что это символы, но оно вроде и не особо ломается, но если нужно могу вернуть как было
![image](https://github.com/user-attachments/assets/8a3e2dc4-bde0-4822-9386-58d7d47d0039)

2024-12-29 16:09 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +        В роли управляющего ядра вы можете управлять блобом.
> Можно взять пример перевода с Starcraft. Сверхмозги сила

А это точно будет звучать хорошо? Я и так мог, просто мне как то странно звучит

2024-12-29 16:09 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          в правом нижнем углу экрана. <br />
> а где {' ' } и желательно убери разницу в строках

Я не особо понимаю о чем ты, уточни пожалуйста

2024-12-29 16:10 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          Вы сможете вручную разместить ядро блоба, нажав кнопку Place Blob Core
> А давай сразу кнопки тоже переведи?

Все кнопочки у блоба?

2024-12-30 01:57 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          в правом нижнем углу экрана. <br />
Все я увидел, мог написать что удалил случайно

2025-01-09 10:59 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Эй, не смейте! Хватит транслировать это!
Возвращай, не трогай, что не надо трогать

2025-01-09 11:00 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          Вы сможете вручную разместить ядро блоба, нажав кнопку Place Blob Core
Да, почему бы и нет. А то кнопка называется по-английски, а в гайде на русском

2025-01-09 11:00 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +        В роли управляющего ядра вы можете управлять блобом.
Этакая отсылка будет к старику

2025-01-15 04:28 UTC, PhantornRU requested changes
По блобу:

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          ядрам, что позволит вам координировать свои действия с ними.
```suggestion
          Попытка коммуникации отправит сообщение всем сверхразумам, 
          для совместной координации.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          короткое время потеряет способность производить споры.
```suggestion
          Боевая единица производимая на фабриках за определенную стоимость. 
          Мощные и крепкие, и даже в меру умные.
          Фабрика, использованная для производства - станет хрупкой,
          временно теряя способность производить споры.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          рядом с фабрики и пытаются зомбировать трупы.
```suggestion
          Автоматически производятся на фабриках, слабы, но их все
           можно послать на врагов. Они также будут атаковать врагов
          рядом с фабриками и зомбифицировать трупы.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +        в виду, что расширение в космос с вероятностью 80% не удастся!
```suggestion
        Блобы для вашего распространения. Могут быть улучшены до
        специализированных блобов. Имейте ввиду,
        расширение в космос с вероятностью 80% не удастся!
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +      <Box>Вы можете превратить обычные клетки блоба в следующие типы:</Box>
```suggestion
      <Box>Вы можете превратить обычных блобов в следующие типы:</Box>
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          чтобы защититься от пожаров на станции.
```suggestion
        <LabeledList.Item label="Сильный блоб">
          Сильные блобы стоят дороже, но наносят больше урона. Кроме
          того, они огнеупорные и могут блокировать воздух, используйте их,
          чтобы защититься от пожаров на станции.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          здоровья сильной клетки блоба.
Лишние строки не надо добавлять
```suggestion
        <LabeledList.Item label="Отражающий блоб">
          Улучшение сильного блоба создает блоба, отражающего
          большинство снарядов, ценой увеличенного здоровья.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          размещен рядом с узловыми клетками блоба или ядра, чтобы они работали.
```suggestion
        <LabeledList.Item label="Ресурсные блобы">
          Блобы, производящие для вас ресурсы, стройте их как 
          можно больше для поглощения станции. 
          Размещается рядом с узлами или ядром.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          клетками блоба или ядром, чтобы они работали.
```suggestion
        <LabeledList.Item label="Фабричные блобы">
          Блобы, порождающие споры, атакующие ближайших врагов. 
          Размещаются рядом с узлами или ядром.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          активировать ресурсные клетки и клетки-фабрики блоба.
```suggestion
        <LabeledList.Item label="Узлы блоба">
          Блоб, распространяющийся как ядро. Как и ядро, могут
          активировать ресурсных и фабричных блобов.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Ваши мысли разбегаются...
```suggestion
              Голова идет кругом...
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Сосредоточен на одной цели...
```suggestion
              Сосредоточен на единственной цели...
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +                    Необходимо следовать этой директиве.
```suggestion
                    Обязан следовать директиве.
```

2025-01-15 04:28 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Выполняйте директивы любой ценой!
```suggestion
              Следуй директивам любой ценой!
```

2025-01-15 05:16 UTC, PhantornRU requested changes
Следующая пачка ревью (сам тоже пройдись лучше)

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoSentient.jsx
> +                  ' Вы также удручающе осознаете, что являетесь не реальным существом, а голоформой. Ваше существование ограничено параметрами голодека.'}
```suggestion
                  ' Вас удручает от осознания, что вы не реальное существо, а голоформа. Ваше существование ограничено параметрами голодека.'}
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoSentient.jsx
> +                  ' Вы также удручающе осознаете, что являетесь не реальным существом, а голоформой. Ваше существование ограничено параметрами голодека.'}
```suggestion
                  ' Вас удручает от осознания, что вы не реальное существо, а голоформа. Ваше существование ограничено параметрами голодека.'}
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoSentient.jsx
> +                  ' Вы также удручающе осознаете, что являетесь не реальным существом, а голоформой. Ваше существование ограничено параметрами голодека.'}
```suggestion
                  ' Вас удручает от осознания, что вы не реальное существо, а голоформа. Ваше существование ограничено параметрами голодека.'}
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoSeparatist.tsx
> +          Вы - Сепаратист за свободу {nation}!
```suggestion
          Вы - Борец за свободу {nation}!
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoSentient.jsx
> +                  ' Вы также удручающе осознаете, что являетесь не реальным существом, а голоформой. Ваше существование ограничено параметрами голодека.'}
```suggestion
                  ' Вас удручает от осознания, что вы не реальное существо, а голоформа. Ваше существование ограничено параметрами голодека.'}
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoShade.jsx
> +              Ваша душа была захвачена в камень души!
```suggestion
              Ваша душа была поймана!
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoShade.jsx
> +              Вы обязаны выполнять волю {master_name}!
```suggestion
              Вы обязаны беспрекословно следовать воли {master_name}!
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoShade.jsx
> +              Помогите им добиться успеха в достижении своих целей любой ценой.
```suggestion
              Помогите добиться успеха в достижении их целей любой ценой.
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoVoidwalker.tsx
> +                    радиосигналы, передаваемые этой станцией.
```suggestion
                    Вы - существо из пустоты между звездами. 
                    Вас привлекли радиосигналы, передаваемые 
                    этой станцией.
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoVoidwalker.tsx
> +                  путь к спасению.
```suggestion
                  <span style={tipstyle}>Выживайте:&ensp;</span>
                  Вы безудержно свободны. Оставаясь в космосе - никто не сможет 
                  вас остановить. Перемещайтесь через окна, придерживайтесь их, 
                  чтобы чтобы всегда иметь путь к отступлению.
```

2025-01-15 05:16 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoVoidwalker.tsx
> +                  руку, чтобы похитить их.
```suggestion
                  <span style={tipstyle}>Похищайте:&ensp;</span>
                  Ваша способность Unsettle оглушает и истощает цели. Прикончите
                  их с помощью своего острия пустоты, открывая окна и вытаскивая 
                  в космос, используйте пустую руку, чтобы похитить их.
```

2025-01-15 05:16 UTC, PhantornRU commented
Как закончишь разбираться с ревью - обязательно пингани меня в дискорде.

2025-01-15 09:56 UTC, larentoun commented
Я тогда подключюсь после того, как ревью @PhantornRU будет принято к сведению.

2025-01-15 12:25 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoShade.jsx
> +              Ваша душа была захвачена в камень души!
Можно вообще написать что душа была заточена в камень души.

2025-01-15 12:51 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoVoidwalker.tsx
> +                  руку, чтобы похитить их.
Я бы оставил так, потому что тут больше обьяснятся игроку, что следует и как делать

2025-01-15 13:00 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Ваши мысли разбегаются...
Я бы оставил мысли, про голову как то странно звучит

2025-01-16 09:05 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoVoidwalker.tsx
> +                  руку, чтобы похитить их.
в любом случае нужно в 3 строчки уместить, а не 4.

2025-01-16 09:21 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Ваши мысли разбегаются...
не, голова здесь как раз-таки стойкое выражение. "Мысли разбегаются" никто у нас не использует. А вот когда голова кружится, это как раз голова идет кругом

2025-01-16 11:02 UTC, Ingakem commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Ваши мысли разбегаются...
Мы промываем человеку мозги, мы меняем ему мысли, мы затуманиваем ему разум, про голову тут нет никаких слов нету, а выдумывать перевод который мало связан с оригиналом, я не особо хочу.

2025-01-18 06:06 UTC, PhantornRU commented
@larentoun глянешь?

2025-01-18 06:15 UTC, PhantornRU requested changes

2025-01-18 06:15 UTC, PhantornRU commented on code/_onclick/hud/blob_overmind.dm
> +			desc = "Попытатся разместить ядро блоба в этом месте."
```suggestion
			desc = "Попытка разместить ядро блоба в этом месте."
```

2025-01-18 06:15 UTC, PhantornRU commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит сильного, умного блоббернаута из фабричного блоб за (ОШИБКА) ресурсов.<br>Используемый фабричный блоб станет хрупким и не сможет производить споры."
```suggestion
	desc = "Производит сильного, умного блоббернаута из фабричного блоба за (ОШИБКА) ресурсов.<br>Используемый фабричный блоб станет хрупким и не сможет производить споры."
```

2025-01-18 06:15 UTC, PhantornRU commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит сильного, умного блоббернаута из фабричного блоб за [BLOBMOB_BLOBBERNAUT_RESOURCE_COST] ресурсов.<br>Используемый фабричный блоб станет хрупким и не сможет производить споры."
```suggestion
	desc = "Производит сильного, умного блоббернаута из фабричного блоб за [BLOBMOB_BLOBBERNAUT_RESOURCE_COST] ресурсов.<br>Используемый фабричный блоба станет хрупким и не сможет производить споры."
```

2025-01-18 06:15 UTC, PhantornRU commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит ресурсный блоб за ОШИБКА ресурсов.<br>Ресурсный блоб будет давать вам ресурсы каждые несколько секунд."
```suggestion
	desc = "Производит ресурсного блоба за ОШИБКА ресурсов.<br>Ресурсный блоб будет давать вам ресурсы каждые несколько секунд."
```

2025-01-18 06:15 UTC, PhantornRU commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит ресурсный блоб за [BLOB_STRUCTURE_RESOURCE_COST] ресурсов.<br>Ресурсный блоб будет давать вам ресурсы каждые несколько секунд."
```suggestion
	desc = "Производит ресурсного блоба за [BLOB_STRUCTURE_RESOURCE_COST] ресурсов.<br>Ресурсный блоб будет давать вам ресурсы каждые несколько секунд."
```

2025-01-18 06:15 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          Вы еще не показали свою истинную форму!
```suggestion
          Ваша натура еще не явлена!
```

2025-01-18 06:15 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +          Вы можете распространятся, что приведет к атаке существ, повреждению
```suggestion
          Вы можете распространяться, что приведет к атаке существ, повреждению
```

2025-01-18 06:15 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoBrainwashed.tsx
> +              Ваши мысли разбегаются...
Это не выдумывание перевода. Не нужно переводить слово в слово, иначе выходит плохо. Локализуй, используй меньше "это". У нас многие вещи в английском языке не используются в повседневной и литературной речи. Наша задача дать хорошую локализацию, а не дословный перевод, в этом ничего зазорного.

2025-01-18 06:21 UTC, PhantornRU commented
@Ingakem говорил же. Сначало вносишь правки от ревью, а уже потом лично. 10 раз одно и то же повторял и показал как делать. По итогу все изменения с ревью потерялись и даже непонятно за что цепляться.

Больше повторяться в этом плане не буду и буду сам правки принимать, если ты их пропускаешь. Куча ревью по грамматическим ошибкам была и не лаконичному тексту - и куча было пропущено.

Я не буду одно и то же ревьювить, если ты не будешь хотя бы прислушиваться. Я в дискорде тебя зачем пинговал по твоему? Несколько раз спрашивал, ты сказал что всё понял. По итогу вижу что вижу.

2025-01-18 06:22 UTC, PhantornRU commented
ПР большой, не усложняй ревьюверам жизнь. Сначала ревью, а уже потом свои изменения. 11й раз повторяю. Как это делать - зайди в дискорд по своим пингам, я тебе кучу раз объяснял.

2025-01-18 06:29 UTC, PhantornRU requested changes

2025-01-18 06:29 UTC, PhantornRU commented on tgui/packages/tgui/interfaces/AntagInfoMorph.tsx
> +              всего, что увидели{' '}
```suggestion
              ...мерзость, способная съесть почти все. 
              Вы можете принимать форму всего, что увидели{' '}
```

2025-01-18 13:06 UTC, larentoun requested changes
Вижу, что можно перефразировать вещи, чтобы убрать разницу в строках. Займись этим, перепроверь падежи.

Названия антагонистов - не имена собственные, пишутся с маленькой буквы. 
`Вы - блоб, блоббернаут, пират, предатель` и т.д. Надо исправить.

2025-01-18 13:06 UTC, larentoun commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит сильного, умного блоббернаута из фабричного блоб за [BLOBMOB_BLOBBERNAUT_RESOURCE_COST] ресурсов.<br>Используемый фабричный блоба станет хрупким и не сможет производить споры."
```suggestion
	desc = "Производит сильного, умного блоббернаута из фабричного блоб за [BLOBMOB_BLOBBERNAUT_RESOURCE_COST] ресурсов.<br>Используемый фабричный блоб станет хрупким и не сможет производить споры."
```

2025-01-18 13:06 UTC, larentoun commented on code/_onclick/hud/blob_overmind.dm
> +	name = "Произвести Блоббернаута ([BLOBMOB_BLOBBERNAUT_RESOURCE_COST])"
```suggestion
	name = "Произвести блоббернаута ([BLOBMOB_BLOBBERNAUT_RESOURCE_COST])"
```

2025-01-18 13:06 UTC, larentoun commented on code/_onclick/hud/blob_overmind.dm
> +	name = "Произвести Блоббернаута (ОШИБКА)"
```suggestion
	name = "Произвести блоббернаута (ОШИБКА)"
```

2025-01-18 13:06 UTC, larentoun commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит ресурсного блоба за ОШИБКА ресурсов.<br>Ресурсный блоб будет давать вам ресурсы каждые несколько секунд."
Производит (что? булочку. винительный падеж).

2025-01-18 13:06 UTC, larentoun commented on tgui/packages/tgui/interfaces/AntagInfoBlob.tsx
> +        Вы - Блоб!
```suggestion
        Вы - блоб!
```

2025-01-18 13:07 UTC, larentoun commented
Напишу отдельным комментом. Смотри, что я написал в топике ревью, а не только то, что прошу изменить в каждой отдельной строке.

2025-01-18 13:08 UTC, larentoun commented
Напишу отдельным комментом еще то, что если хочешь более быстрое ревью - атомизируй ПР на много маленьких.

2025-01-18 14:16 UTC, Ingakem commented
Меня заебали ваши предложения(обязаловки) и непонятные дополнения. Один хочет одно, другой третье, хотите переводить, переводите сами, как раз уже все сами решаете и закидываете со своими же ошибками в переводе и со своим же переводом.

2025-01-18 14:17 UTC, Ingakem commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Производит ресурсного блоба за ОШИБКА ресурсов.<br>Ресурсный блоб будет давать вам ресурсы каждые несколько секунд."
Все вопросы к Пупсу.

2025-01-18 15:10 UTC, larentoun commented
> Меня заебали ваши предложения(обязаловки) и непонятные дополнения. Один хочет одно, другой третье, хотите переводить, переводите сами, как раз уже все сами решаете и закидываете со своими же ошибками в переводе и со своим же переводом.

Никто не обязывает тебя переводить, как и нас проводить ревью, но всё-таки хочется видить хороший перевод, а не машинный с логическими ошибками.

2025-01-18 15:12 UTC, larentoun commented
Думаю, лучшим решением будет, чтобы кто-то другой взялся за это дело и разделил на несколько ПРов.

2025-01-18 15:12 UTC, closed without merging

2025-01-18 15:43 UTC, Ingakem commented
> > Меня заебали ваши предложения(обязаловки) и непонятные дополнения. Один хочет одно, другой третье, хотите переводить, переводите сами, как раз уже все сами решаете и закидываете со своими же ошибками в переводе и со своим же переводом.
> 
> Никто не обязывает тебя переводить, как и нас проводить ревью, но всё-таки хочется видеть хороший перевод, а не машинный с логическими ошибками.

Хочется видеть хорошие исправления или дополнения, а не исправление одной ошибки на другую с форсом своего перевода и непонятных доебов к строчкам, которые меняет Prettier, о котором вы вроде должны знать.