Small balance changes
ss220club/BandaStation pull request #931
Opened 2024-12-29 02:14 UTC by AloeNeverDie

## Что этот PR делает
Цены на патроны в карго теперь выше;
Цены на большинство видов оружия стали фиксированными и заказов оружия должно стать меньше (в теории);
Пони стал дороже;
Святые арбузы теперь могут защитить максимум 3 раза вместо 5.

## Почему это хорошо для игры

Оружия должно стать меньше, что должно сделать угрозы на станции более серьёзными;
5 зарядов у арбузов было слишком много, меньшее кол-во зарядов должно их ослабить;
Пони сейчас слишком дешевый (1984).

## Тестирование

Локалка

## Changelog

:cl:
balance:  Цены в карго изменены
balance:  Святы арбузы стали слабее
/:cl:

2024-12-29 08:29 UTC, Gaxeer commented on modular_bandastation/balance/code/unique_plant_genes.dm
> +	shield_uses = round(our_seed.potency / 30)
В коркоде меняй. Потому что вот эти изменения ничего не дают, так как там дальше по коду добавляется компонент

2024-12-29 11:30 UTC, dj-34 requested changes

2024-12-29 11:30 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +
```suggestion
// MARK: AMMO
```

2024-12-29 11:30 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +
```suggestion
// MARK: WEAPONS
```

2024-12-29 11:30 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = 9999
выглядит как рофлоцена
```suggestion
	cost = 10000
```

2024-12-29 11:30 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
Добавь в коментах сколько примерно выходит у каждой по кредитам, если не сложно.

2024-12-29 11:32 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = CARGO_CRATE_VALUE * 14
Вверх закинь к остальным /security/

2024-12-29 12:46 UTC, AloeNeverDie commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = CARGO_CRATE_VALUE * 14
Цена в 9999 сделана, чтобы не было выделения жёлтым в карго + сказали, что выделение не нравится - поэтому поставил цену в 9999

2024-12-29 13:44 UTC, AloeNeverDie commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = 9999
Цена в 9999 сделана, чтобы не было выделения в списке заказов желтым цветом + попросили убрать

2024-12-29 13:54 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = 9999
ну сделай хотя бы 9000

2024-12-29 14:11 UTC, AloeNeverDie commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = 9999
Сделал

2024-12-30 11:44 UTC, AyIong commented on modular_bandastation/balance/code/cargo_packs.dm
> +
Мне кажется, резина должна быть дешевле летала

2024-12-30 16:34 UTC, AyIong approved these changes

2025-01-14 07:47 UTC, dj-34 commented on modular_bandastation/balance/_balance.dme
> +#include "code/laser.dm"
Ты куда засунул не в алфавитном порядке

2025-01-14 07:47 UTC, dj-34 commented on code/controllers/subsystem/stock_market.dm
> +	var/price_minimum = round(mat.value_per_unit * SHEET_MATERIAL_AMOUNT * 0.8) // BANDASTATION EDIT - Original: round(mat.value_per_unit * SHEET_MATERIAL_AMOUNT * 0.5)
Ты меняешь только 1 цифру, смысл в коментариях указывать фул строку, если можно указать что изменилась цифра.

2025-01-14 07:47 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = CARGO_CRATE_VALUE * 6 // Original price: 600  Approximate new price: 1200
```suggestion
	cost = CARGO_CRATE_VALUE * 6 // Original price: 600 Approximate new price: 1200
```

2025-01-14 07:47 UTC, dj-34 commented on modular_bandastation/balance/code/laser.dm
Возможно тоже самое стоит проделать и с нелетальным СМГ. Не уверен.

2025-01-14 07:47 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = CARGO_CRATE_VALUE * 150 // Original price: 20000  Approximate new price: 30000
```suggestion
	cost = CARGO_CRATE_VALUE * 150 // Original price: 20000 Approximate new price: 30000
```

2025-01-14 07:47 UTC, dj-34 commented on modular_bandastation/balance/code/cargo_packs.dm
> +	cost = PAYCHECK_COMMAND * 24 // Original price: 1200  Approximate new price: 2400
```suggestion
	cost = PAYCHECK_COMMAND * 24 // Original price: 1200 Approximate new price: 2400
```

2025-01-14 07:51 UTC, dj-34 commented
Попрошу в следующий раз указывать корректное название ПРа, иначе никогда в жизни не найден ПР если потребуется.

2025-01-15 05:39 UTC, PhantornRU commented
This branch is out-of-date with the base branch

Бранч надо обновить

2025-01-15 06:03 UTC, AyIong commented
This branch is out-of-date with the base branch

Бранч надо обновить

2025-01-15 06:07 UTC, AyIong commented
This branch is out-of-date with the base branch

Бранч надо обновить

2025-01-19 17:30 UTC, larentoun commented
Пушка горизонта - манч и невероятная игра на победку. Скорее вопрос по рулзам, почему за это не стреляют.

2025-01-19 17:32 UTC, larentoun commented on modular_bandastation/balance/code/cargo/packs/security.dm
> +/datum/supply_pack/security/disabler
Не вижу смысла нерфить цену дизейблеров

2025-01-19 17:33 UTC, larentoun commented on modular_bandastation/balance/code/cargo/packs/security.dm
> +/datum/supply_pack/security/armory/energy
Не понятно, зачем нерф Еганов, которые и так достаточно дорогие, а энергоревольверы остались нетронуты?

2025-01-19 17:35 UTC, larentoun commented on modular_bandastation/balance/code/laser.dm
> +	e_cost = LASER_SHOTS(20, STANDARD_CELL_CHARGE) // Original: LASER_SHOTS(40, STANDARD_CELL_CHARGE)
А толк от пушки с 200 урона.
Думаю, стоит вернуть количество выстрелов, ведь это её основная фича, и немногим уменьшить урон и, если всё ещё хочется зачем-то нерфить, еще ниже вунды.

2025-01-19 17:37 UTC, larentoun commented on modular_bandastation/balance/code/cargo/packs/goodies.dm
> +/datum/supply_pack/goody/double_barrel
Двухстволку покупает СБ?

2025-01-19 17:38 UTC, larentoun commented on modular_bandastation/balance/code/cargo/packs/goodies.dm
> +/datum/supply_pack/goody/disabler_single
Дизейблер опять же, лишне

2025-01-19 17:40 UTC, larentoun commented
ИМХО, большая часть изменений должна касаться только прайма

2025-01-19 18:41 UTC, larentoun commented on code/datums/elements/deliver_first.dm
> +	/**
Эти изменения не нужны после мержа апстрима - https://github.com/tgstation/tgstation/pull/88797

2025-01-20 07:51 UTC, AyIong commented
> Вопрос по поводу нового списка снаряжения СБ из карго - что было убрано и по какой причине?

По причине сломанного нахуй карго, с нескончаемым запасом денег
Если хочешь подробностей - заползнай обратно в подвал

2025-01-21 12:54 UTC, AloeNeverDie commented on modular_bandastation/balance/code/cargo/packs/security.dm
> +/datum/supply_pack/security/armory/energy
Ревики говорили не трогать, поэтому их не задели изменения, в целом цены сейчас упали, посмотрим что из этого выйдет

2025-01-21 12:57 UTC, AloeNeverDie commented on modular_bandastation/balance/code/cargo/packs/goodies.dm
> +/datum/supply_pack/goody/double_barrel
Ап цен был для всего вооружения в целом х2, где-то х3, сейчас х1.5, возможно потом ещё раз изменим, смотря от ситуации

2025-01-21 15:07 UTC, larentoun commented on modular_bandastation/balance/code/cargo/packs/goodies.dm
> +/datum/supply_pack/goody/double_barrel
Антаги тоже хотят покупать пушки

2025-01-21 19:12 UTC, dj-34 approved these changes

2025-01-21 19:12 UTC, dj-34 commented on modular_bandastation/balance/code/cargo/exports/materials.dm
> +/datum/export/material/adamantine //For whatever reason, adamantine doesn't truly exist in export list
```suggestion
/datum/export/material/adamantine // For whatever reason, adamantine doesn't truly exist in export list
```

2025-01-21 19:12 UTC, dj-34 commented on modular_bandastation/balance/code/laser.dm
> +// MARK: carbine changes
```suggestion
// MARK: Сarbine changes
```

2025-01-22 13:13 UTC, Gaxeer approved these changes

2025-01-22 20:09 UTC, merged